// Certificate program page for the "Basic & Accounting" category: computer fundamentals, MS Office /
// Advanced Excel, Tally Prime with GST, BUSY and GST/taxation as one 3 · 6 · 9-month career path.
// See ../courseDetails/types.ts for what each field is.
import { site } from "../site";
import type { CourseDetail } from "../courseDetails/types";

export const basicAccountingProgram: CourseDetail = {
  slug: "basic-accounting-courses-in-jalandhar",
  seo: {
    title: `Accounting & Computer Certificate Program in ${site.city} | 3, 6 & 9 Months`,
    description: `One program from computer basics to a complete accounts job at ${site.name} ${site.city}: MS Office, Advanced Excel, Tally Prime with GST, BUSY, GST returns, TDS and income tax basics — in 3, 6 or 9-month tracks with a verifiable certificate and placement support.`,
  },
  hero: {
    crumb: "Basic & Accounting",
    tag: "Certificate Program",
    badge: "Tally + GST + Excel",
    title: `Best Accounting & Computer Certificate Program in ${site.city}`,
    text: `Start with the computer itself and finish able to run a business's books — MS Office and Excel, Tally Prime with GST, BUSY, GST returns and TDS — in one step-by-step program at the ${site.name} ${site.city} centre. Pick a 3, 6 or 9-month track and stop at the level you need.`,
    points: ["Computer to accounts in one path", "Tally, BUSY & Excel", "GST & TDS practice", "Placement support"],
    facts: [
      { label: "Duration", value: "3 · 6 · 9 Months" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "10th / 12th, any stream" },
      { label: "Includes", value: "Certificate · internship letter on 6 & 9-month tracks" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "500+", label: "Hiring partners", note: "for placement support" },
    ],
    hub: {
      center: "tally.png",
      nodes: [
        { logo: "windows.svg" },
        { logo: "word.png" },
        { logo: "excel.png" },
        { logo: "powerpoint.svg" },
        { logo: "outlook.svg" },
        { logo: "google-workspace.svg" },
        { icon: "₹" },
        { icon: "🧾" },
      ],
    },
  },
  overview: {
    eyebrow: "Program overview",
    title: "From your first computer class to a full accounts desk",
    paragraphs: [
      `${site.name}'s Basic & Accounting certificate program in ${site.city} joins the courses most office and accounts jobs ask for into one path, taught in the order you will use them. It is for school leavers, commerce students, graduates, job seekers and business owners who want a steady office or accounts career in Punjab — whether or not they have used a computer much before.`,
      "The program starts with computer fundamentals, the internet and MS Office, then spends real time on Excel, because almost every accounts job runs on it. Next comes accounting itself — the golden rules, journals and ledgers — before Tally Prime: company creation, vouchers, inventory and GST invoicing. Longer tracks go on to GST return data, TDS, payroll, bank reconciliation and final accounts, then BUSY, GST and income tax work on the government portals, and Excel reporting for month-end MIS.",
      "Every module is practised on sample company data on your own lab computer, and trainers check your entries, not just your final answer. You can stop after 3 months with solid office and Tally skills, or continue to 6 or 9 months and leave with a project portfolio, an internship letter and placement support.",
    ],
    image: "tally-gst.webp",
    imageAlt: "Students working on accounts in Tally Prime and Excel at the techcadd lab",
    imageTag: "One path, three lengths",
    getList: [
      "One computer per student, every class",
      "MS Office, Advanced Excel, Tally Prime and BUSY in one program",
      "GST, TDS and payroll practice on sample company data",
      "Verifiable certificate (internship letter on 6 & 9-month tracks)",
      "Placement support with resume help and job drives",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "7", label: "Phases" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who this program is for",
    text: "You only need to be willing to practise. Computer basics are taught from the start and accounting is explained from the ground up, so commerce helps but is not required.",
    items: [
      { icon: "student", title: "10th / 12th pass students", text: "Build computer and accounts skills that lead straight to office jobs, or run alongside college." },
      { icon: "grad", title: "B.Com, BBA & other graduates", text: "Add Tally, GST and Excel — the practical skills interviewers test that a degree alone does not give you." },
      { icon: "job", title: "Job seekers", text: "Office assistant, billing and accountant vacancies in Punjab almost always list MS Office, Tally and GST." },
      { icon: "shop", title: "Shop & business owners", text: "Keep your own books, raise GST invoices and understand what your CA is filing for you." },
      { icon: "office", title: "Office & counter staff", text: "Move up from data entry, billing or reception into proper accounts work and better pay." },
      { icon: "govt", title: "Govt. & banking aspirants", text: "Get the computer and accounting knowledge exams and clerical jobs expect while you prepare." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why one program beats a string of short courses",
    feature: {
      tag: "Access",
      title: "Batches around college, work or the shop",
      text: `Students reach the ${site.city} centre from Model Town, Urban Estate, Adarsh Nagar, Basti Sheikh and Rama Mandi, with weekend learners from Phagwara, Kapurthala, Nakodar and Kartarpur. Morning, evening, weekend and 1-on-1 batches make a 6 or 9-month track realistic without dropping college or leaving a job.`,
      slots: ["Morning", "Afternoon", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Order",
        title: "Each skill sits on the last",
        text: "Computer basics make Excel easy, Excel makes Tally reports useful, and Tally makes GST returns make sense. Nothing is taught before you are ready for it.",
      },
      {
        tag: "Method",
        title: "Accounting first, keys second",
        text: "You learn why an entry is a debit or credit before where to press, so you can handle entries nobody showed you in class.",
      },
      {
        tag: "Range",
        title: "Tally and BUSY, both",
        text: "Many local firms run Tally Prime, many traders and distributors run BUSY. Knowing both on the same accounting logic widens the jobs you can take.",
      },
      {
        tag: "Flexible",
        title: "Stop at the level you need",
        text: "Three months gives office and Tally skills; six adds full accounts and BUSY; nine adds taxation depth and a live project.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Every GST-registered business needs someone at the accounts desk.",
    points: [
      "GST returns are due monthly or quarterly for every registered business, and TDS returns every quarter, so firms need staff who keep clean books all year, not just at year-end.",
      "Fresher office and accounts roles in Punjab typically start around ₹10,000 – ₹18,000 a month, rising with GST, TDS and Excel experience.",
      "Small firms prefer one person who can handle entries, compliance and Excel reports — exactly what the longer tracks train you for.",
    ],
    panel: [
      { k: "Voucher entry", v: "Every working day" },
      { k: "GSTR-1 / GSTR-3B", v: "Monthly or quarterly" },
      { k: "TDS returns", v: "Every quarter" },
      { k: "Excel MIS", v: "Every month-end" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, month by month",
    text: "The 3-month track covers Months 1–3, the 6-month track continues to Month 6, and the 9-month track runs the full path to the live project.",
    phases: [
      {
        id: "01",
        name: "Computer Fundamentals & MS Office",
        weeks: "Month 1",
        summary: "Get comfortable with the computer and everyday office work.",
        topics: [
          "Windows, files, folders, shortcuts and printing",
          "Internet, Gmail, online forms and safe browsing",
          "MS Word — letters, resumes, tables and mail merge",
          "PowerPoint presentations and English typing practice",
        ],
        outcome: "Handle day-to-day office documents, email and files on your own",
      },
      {
        id: "02",
        name: "Excel for Office & Accounts",
        weeks: "Month 2",
        summary: "The spreadsheet skills every accounts desk runs on.",
        topics: [
          "Formatting, formulas, SUM/IF/COUNTIF and percentages",
          "VLOOKUP / XLOOKUP, SUMIFS and text/date functions",
          "Sorting, filtering, pivot tables and charts",
          "Invoice, salary and cash-book sheets for a small business",
        ],
        outcome: "Build working Excel sheets for billing, salaries and reports",
      },
      {
        id: "03",
        name: "Accounting Basics & Tally Prime",
        weeks: "Month 3",
        summary: "Learn the logic of accounts, then keep them in Tally Prime.",
        topics: [
          "Golden rules, journal, ledger and trial balance",
          "Company creation, groups, ledgers and opening balances",
          "Sales, purchase, payment, receipt, contra and journal vouchers",
          "Inventory basics and GST tax invoices (CGST + SGST vs IGST)",
        ],
        outcome: "A sample trading company with a month of entries in Tally Prime",
      },
      {
        id: "04",
        name: "Tally Prime — GST, TDS, Payroll & Final Accounts",
        weeks: "Months 4–5",
        summary: "Take the books all the way from daily entries to the Balance Sheet.",
        topics: [
          "GST set-up, HSN/SAC, RCM, credit/debit notes and GSTR-1 / GSTR-3B reports",
          "TDS on contractors, professionals and rent; payroll with PF and ESI",
          "Bank reconciliation, cost centres and godown-wise stock",
          "Adjustment entries, P&L account, Balance Sheet and ratio reports",
        ],
        outcome: "A full year of books closed for the sample company",
      },
      {
        id: "05",
        name: "BUSY Accounting & Project",
        weeks: "Month 6",
        summary: "Add the billing and stock package traders use, then prove it on a project.",
        topics: [
          "BUSY masters, bill sundries and GST tax categories",
          "Sales, purchase, returns and party outstanding",
          "Batch, expiry and godown-wise inventory",
          "Accounting project in Tally Prime and BUSY, reviewed by your trainer",
        ],
        outcome: "Handle billing and stock in BUSY and complete a trainer-reviewed project",
      },
      {
        id: "06",
        name: "GST, Income Tax & TDS Returns",
        weeks: "Months 7–8",
        summary: "Move from entries to the compliance work firms pay more for.",
        topics: [
          "GST registration types, composition scheme and QRMP",
          "GSTR-1 and GSTR-3B on the portal, ITC matching with GSTR-2B",
          "E-way bills, e-invoicing (IRN) and a GSTR-9 overview",
          "Income tax heads, old vs new regime, TDS returns 24Q / 26Q, Form 16 and an ITR-1 / ITR-4 walkthrough",
        ],
        outcome: "GST and TDS return working papers and a sample ITR computation",
      },
      {
        id: "07",
        name: "Excel MIS & Live Accounting Project",
        weeks: "Month 9",
        summary: "Bring every skill together the way a real accounts job does.",
        topics: [
          "GSTR-2B vs purchase register reconciliation in Excel",
          "Month-end MIS: sales, expense and outstanding reports with pivots and charts",
          "Books of a sample business with GST, TDS and payroll for every month",
          "Final accounts, report pack and trainer review",
        ],
        outcome: "A complete accounting portfolio to show at interviews",
      },
    ],
  },
  tools: {
    eyebrow: "Software you will use",
    title: "The full office and accounts toolkit",
    text: "Office tools, Tally Prime and BUSY are used on your own lab computer; the GST and income tax portals are walked through step by step with sample data.",
    tools: [
      { name: "MS Word & PowerPoint", logo: "word.png", use: "Letters, resumes & presentations" },
      { name: "MS Excel", logo: "excel.png", use: "Formulas, pivots & MIS" },
      { name: "Tally Prime", logo: "tally.png", use: "Accounts, GST, TDS & payroll" },
      { name: "BUSY", mono: "BUSY", use: "Trading billing & stock" },
      { name: "GST Portal", mono: "GST", use: "GSTR-1, GSTR-3B, GSTR-2B" },
      { name: "Income Tax Portal", mono: "ITR", use: "ITR, 26AS, AIS" },
      { name: "Windows", logo: "windows.svg", use: "Files, printing & backups" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Get certified in Basic & Accounting",
    text: "Complete your track and its practical work to receive a techcadd certificate you can attach to any job application — verifiable online. The 6 and 9-month tracks also include an internship letter.",
    courseName: "Basic & Accounting Certificate Program",
    items: [
      { title: "Program certificate", text: "Verifiable online by any employer" },
      { title: "Internship letter", text: "On the 6 and 9-month tracks" },
      { title: "Project portfolio", text: "Books, GST and Excel work you prepared" },
      { title: "Placement support", text: "Resume help, mock tests and job drives" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where the program takes you",
    text: "Indicative starting pay for freshers in Punjab. Actual offers depend on the employer, the track you complete and how you do in the practical test most firms give.",
    roles: [
      { title: "Accountant", pay: "₹12k – 18k", text: "Traders, manufacturers, hospitals and schools" },
      { title: "Accounts / Tax Assistant", pay: "₹10k – 18k", text: "GST, TDS and entries in CA and tax offices" },
      { title: "Billing Executive", pay: "₹10k – 15k", text: "Distributors, wholesalers and showrooms" },
      { title: "Office Assistant / Computer Operator", pay: "₹9k – 14k", text: "Documents, Excel records and data entry" },
    ],
    hiring: ["CA & tax consultant offices", "Traders & distributors", "Manufacturing units", "Hospitals & schools", "Showrooms & retail", "Export houses"],
    qa: [
      {
        q: "What jobs can I get after this program?",
        a: "Office assistant and computer operator roles after the 3-month track; accountant, accounts assistant, billing executive and tax assistant roles become realistic after the 6 and 9-month tracks.",
      },
      {
        q: "Which track should I choose?",
        a: "Choose 3 months for office and Tally basics, 6 months if you want a full accounts job, and 9 months if you also want GST, TDS and income tax work and a live project on your resume.",
      },
      {
        q: "Can I run my own business accounts after this?",
        a: "Yes. Many shop and business owners join to keep their own books, raise GST invoices and check what their CA is filing.",
      },
      {
        q: "Can I grow further after this?",
        a: "Yes. With experience, accountants move into senior accountant, GST/tax consultant or accounts manager roles, and many continue with B.Com, M.Com or professional exams alongside work.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real tasks you will complete",
    text: "Each track ends with work you can show — the longer your track, the more of the business's books you handle yourself.",
    items: [
      { n: "01", title: "Office document & Excel pack", text: "A resume, business letters and Excel sheets for invoices, salaries and a monthly cash book.", tags: ["MS Office", "Excel"] },
      { n: "02", title: "Trading company in Tally Prime", text: "Create a company from a trial balance and enter a month of sales, purchases and GST invoices.", tags: ["Tally Prime", "GST"] },
      { n: "03", title: "Year-end close + BUSY billing", text: "Process payroll and TDS, reconcile the bank, prepare final accounts and run a distributor's billing in BUSY.", tags: ["Final accounts", "BUSY"] },
      { n: "04", title: "Live accounting project", text: "Keep a sample business's books with GST, TDS and payroll, reconcile ITC with GSTR-2B and build an Excel MIS pack.", tags: ["Compliance", "MIS"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "Understand it. Do it. Check it.",
    text: "Every topic follows the same three steps, so you learn the work itself — not just where the buttons are.",
    steps: [
      { title: "Understand it", text: "The trainer explains the task or transaction and why it is done that way.", example: "Goods sold on credit with GST" },
      { title: "Do it", text: "You carry it out yourself on your own lab computer.", example: "Sales voucher in Tally Prime" },
      { title: "Check it", text: "You verify the result in the ledger, report or sheet before moving on.", example: "Party balance and GSTR-1 report" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name} for accounting`,
    text: `Plenty of places in ${site.city} teach computers or Tally. The difference is whether you learn accounting or only menus, how much time you spend on real entries, and whether GST and Excel are taught properly.`,
    items: [
      { title: "One clear path", text: "Computer basics, Office, Excel, Tally, BUSY and GST taught in the order a job uses them." },
      { title: "Accounting before software", text: "Golden rules and journal entries first, so every Tally screen makes sense." },
      { title: "Small batches", text: "The trainer checks your entries, sheets and trial balance, not just the class's." },
      { title: "Flexible timings", text: "Morning, evening, weekend and 1-on-1 batches around college, work or business." },
      { title: "Placement support", text: "Resume help, mock Tally tests and job drives with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any computer or accounting course, including this one.",
    rows: [
      { feature: "Structure", us: "One path from computer basics to accounts, in 3, 6 or 9 months", them: "Separate short courses with gaps" },
      { feature: "Accounting basics", us: "Golden rules and journal taught first", them: "Straight into Tally menus" },
      { feature: "Software covered", us: "MS Office, Advanced Excel, Tally Prime and BUSY", them: "Usually one package only" },
      { feature: "GST & TDS", us: "Invoices, GSTR-1, GSTR-3B, GSTR-2B, TDS returns", them: "Often only GST invoice entry" },
      { feature: "Practice data", us: "Full sample company with real-looking bills", them: "A few isolated entries" },
      { feature: "Batch size", us: "Small batches with individual checking", them: "Large, crowded batches" },
      { feature: "Certificate", us: "Verifiable certificate; internship letter on 6 & 9-month tracks", them: "Varies" },
      { feature: "After the program", us: "Placement support and job drives", them: "Limited or none" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Simranjeet Kaur", role: "B.Com Student · Model Town", text: "Started with Excel and went on to Tally and GST. Each part made the next one easier to understand." },
    { name: "Gurpreet Singh", role: "Accounts Assistant · Jalandhar", text: "I had only used a phone before joining. After the 6-month track I got a job in a trading firm's accounts office." },
    { name: "Neha Arora", role: "12th Commerce · Urban Estate", text: "Small batch, and the trainer checked every entry I made. The notes were simple to revise from at home." },
    { name: "Harjit Singh", role: "Kiryana Wholesaler · Rama Mandi", text: "I wanted to understand my own GST bills and returns. Now I check everything before it goes to my CA." },
    { name: "Manpreet Kaur", role: "Billing Executive · Phagwara", text: "Weekend batch suited my job. Learning both Tally and BUSY helped a lot in interviews." },
    { name: "Arshdeep Singh", role: "Graduate · Kapurthala", text: "The 9-month track covered GST and TDS returns properly. The final project gave me something real to talk about." },
  ],
  faqs: [
    { q: "Do I need a commerce background or computer knowledge to join?", a: "No. The program starts with computer fundamentals and teaches accounting from the golden rules up. Commerce students move a little faster in the accounting months, but anyone who practises can finish." },
    { q: "What is the difference between the 3, 6 and 9-month tracks?", a: "All three follow the same path. The 3-month track covers computer basics, MS Office, Excel and Tally Prime fundamentals; the 6-month track continues to full accounts in Tally, BUSY and a project; the 9-month track adds GST, TDS and income tax work and a live accounting project." },
    { q: "Can I start with 3 months and extend later?", a: "Yes. Each longer track continues where the shorter one ends, so you can talk to a counsellor about extending once you have finished the first three months." },
    { q: "Is GST return filing covered?", a: "Yes. You prepare GST invoices and GSTR-1 / GSTR-3B data in Tally Prime, and the 9-month track goes through the GST portal, ITC matching with GSTR-2B, e-way bills and e-invoicing." },
    { q: "Will I get a certificate and internship letter?", a: "Every track ends with a techcadd certificate that can be verified online. The 6 and 9-month tracks also include an internship letter." },
    { q: "Is this the official Tally or GST certification?", a: "No. The certificate is issued by techcadd for completing our program. It is separate from any certification offered by Tally Solutions, the BUSY software vendor or the government." },
    { q: "What are the batch timings?", a: "Morning, afternoon, evening and weekend batches are available, plus 1-on-1 slots on request." },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, see the lab and meet the trainer before you decide." },
  ],
  program: {
    category: "basic-accounting",
    feeSource: "tally-prime-training-in-jalandhar",
    tracksTitle: "Choose your Basic & Accounting track",
    tracksText: "All three tracks follow the same path from computer basics to accounts work — each longer track picks up exactly where the shorter one ends, so you choose how far to go.",
    tracks: [
      {
        kind: "Program",
        duration: "3 Months",
        text: "Computer fundamentals, MS Office and practical Excel, then accounting basics and Tally Prime with GST invoicing — enough for office, billing and entry-level accounts work.",
      },
      {
        kind: "Certificate Program",
        duration: "6 Months",
        text: "Continues into full Tally Prime accounts — GST return data, TDS, payroll, bank reconciliation and final accounts — then BUSY and a trainer-reviewed project, with an internship letter.",
      },
      {
        kind: "Diploma Program",
        duration: "9 Months",
        text: "Adds GST returns on the portal, income tax and TDS returns and Excel MIS reporting, finished with a live accounting project and an internship letter.",
      },
    ],
    fit: {
      title: "Not sure if Basic & Accounting is the right fit?",
      text: "Book a free demo class or a quick call with a counsellor, and we will help you pick the track that suits your background and goals.",
    },
  },
};
