// Certificate program page for the "Civil / Mechanical" category. See ../courseDetails/types.ts.
import { site } from "../site";
import type { CourseDetail } from "../courseDetails/types";

export const civilMechanicalProgram: CourseDetail = {
  slug: "civil-mechanical-courses-in-jalandhar",
  seo: {
    title: `Civil & Mechanical CAD Certificate Program in ${site.city} | 3, 6 & 9 Months`,
    description: `Build a CAD career at ${site.name} ${site.city}: AutoCAD drafting, then a civil stream (Revit, 3ds Max) or a mechanical stream (SolidWorks, CATIA, CNC & CAM) across 3, 6 or 9 months, with a verifiable certificate, internship letter on 6+ month tracks and placement support.`,
  },
  hero: {
    crumb: "Civil / Mechanical",
    tag: "Civil / Mechanical CAD",
    badge: "Civil & Mechanical Streams",
    title: `Best Civil & Mechanical CAD Certificate Program in ${site.city}`,
    text: `Start with AutoCAD drafting, then follow the stream that fits your field — Revit and 3ds Max for civil and architecture, SolidWorks, CATIA and CNC/CAM for mechanical — building a portfolio of real drawings and models in the ${site.name} ${site.city} CAD lab.`,
    points: ["AutoCAD foundation", "Civil or mechanical stream", "Portfolio of drawings & models", "Placement support"],
    facts: [
      { label: "Duration", value: "3 · 6 · 9 Months" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "10th / 12th, ITI, Diploma, B.Tech" },
      { label: "Includes", value: "Certificate · internship letter on 6 & 9 months" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "500+", label: "Hiring partners", note: "for placement support" },
    ],
    hub: {
      center: "autocad.png",
      nodes: [
        { logo: "solidworks.png" },
        { logo: "catia.svg" },
        { logo: "revit.svg" },
        { logo: "autodesk.svg" },
        { logo: "excel.png" },
        { logo: "windows.svg" },
        { icon: "📐" },
        { icon: "⚙" },
      ],
    },
  },
  overview: {
    eyebrow: "Program overview",
    title: "One CAD career path, two engineering streams",
    paragraphs: [
      `${site.name}'s Civil / Mechanical certificate program in ${site.city} is for diploma, B.Tech and ITI students, site staff and workshop technicians who want more than a single software course — a planned path from drafting to 3D design that ends with a portfolio an employer can judge.`,
      "Everyone starts on the same foundation: AutoCAD drawing setup, draw and modify commands, layers, blocks, dimensioning, layouts and plotting to scale, with isometric and 3D basics. From there you follow your stream. Civil and architecture students move into Revit Architecture for BIM models, sheets and schedules, then 3ds Max for interior and exterior visualisation. Mechanical students move into SolidWorks or CATIA for parts, assemblies, sheet metal and drawings, then CNC Programming & CAM, where G-code and toolpaths are written and verified on simulators and CAM software.",
      "Choose 3, 6 or 9 months depending on how far you want to go. Every module ends with a drawing, model or program that a trainer checks, so whichever track you take you leave with work you made yourself — and on the 6 and 9-month tracks, an internship letter as well.",
    ],
    image: "autocad.webp",
    imageAlt: "Students working on civil and mechanical CAD drawings in the techcadd lab",
    imageTag: "Drafting to 3D, step by step",
    getList: [
      "One CAD workstation per student, every class",
      "AutoCAD foundation common to both streams",
      "Civil stream: Revit Architecture and 3ds Max",
      "Mechanical stream: SolidWorks / CATIA and CNC & CAM",
      "Verifiable certificate + portfolio; internship letter on 6+ months",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "2", label: "Streams" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who this program is for",
    text: "You need basic computer use and the ability to read a simple drawing. You pick the civil or mechanical stream after the AutoCAD foundation, with a counsellor's help if you are unsure.",
    items: [
      { icon: "engineer", title: "Civil & mechanical diploma students", text: "Learn the software your semester projects, industrial training and first job all expect." },
      { icon: "grad", title: "B.Tech / B.E. students", text: "Add a CAD stream and a portfolio to your degree before internships and campus interviews." },
      { icon: "student", title: "ITI draughtsman & fitter trainees", text: "Move from the drawing board or shop floor to drawings, models and programs on computer." },
      { icon: "job", title: "Site & workshop staff", text: "Supervisors, operators and technicians who want to move into a drafting, design or programming role." },
      { icon: "design", title: "Interior & architecture beginners", text: "Plans in AutoCAD, BIM in Revit and client-ready renders in 3ds Max, in one path." },
      { icon: "freelance", title: "Freelance draughtsmen & modellers", text: "Offer house plans, BIM models, renders or part drawings to local builders and workshops." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why a CAD program instead of a single course",
    feature: {
      tag: "Access",
      title: "Batches around college, site and shift hours",
      text: `Students reach the ${site.city} centre from Model Town, Urban Estate, Basti Sheikh and Rama Mandi, and from polytechnics and engineering colleges on the Kapurthala and Phagwara roads, while working technicians come in from the Focal Point industrial area. Morning, evening, weekend and 1-on-1 slots let you keep studying or working while you train.`,
      slots: ["Morning", "Afternoon", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Path",
        title: "Each step builds on the last",
        text: "AutoCAD drawing discipline carries into Revit, SolidWorks and CATIA, and 3D models feed renders or CAM toolpaths — so nothing is learned twice.",
      },
      {
        tag: "Streams",
        title: "Practice for your field",
        text: "Civil students work on plans, sections and BIM models; mechanical students on part drawings, assemblies and machining programs.",
      },
      {
        tag: "Output",
        title: "A portfolio, not just certificates",
        text: "Plotted sheets, 3D models, renders or verified programs — the work an employer actually asks to see at an interview.",
      },
      {
        tag: "Proof",
        title: "Internship letter on longer tracks",
        text: "The 6 and 9-month tracks include an internship letter alongside the certificate, which helps when applying for your first role.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Construction and manufacturing around you run on CAD.",
    points: [
      `${site.city}'s housing colonies, commercial projects and interior work need drawings, BIM models and renders, while its hand-tool, valve, sports-goods and auto-parts units design and machine parts from 3D models.`,
      "Fresher CAD roles in Punjab typically start around ₹10k – 20k a month, and pay grows as you add a second tool, site or shop-floor experience and a stronger portfolio.",
      "A planned 6 or 9-month path gets you job-ready in one stream, instead of collecting unrelated short courses.",
    ],
    panel: [
      { k: "House plans & BIM", v: "Builders & architects" },
      { k: "Renders", v: "Interior & real-estate firms" },
      { k: "Parts & assemblies", v: "Manufacturers & fabricators" },
      { k: "CNC programs", v: "Machine shops & production units" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, month by month",
    text: "The 3-month track covers Months 1–3, the 6-month track continues to Month 6, and the 9-month track runs the full path. From Month 4 the civil and mechanical streams follow separate modules.",
    phases: [
      {
        id: "01",
        name: "AutoCAD 2D Drafting",
        weeks: "Month 1",
        summary: "Set up drawings properly and learn the draw and modify commands until they are automatic. Common to both streams.",
        topics: [
          "Interface, units, limits and drawing templates",
          "Coordinates, object snaps, ortho and polar tracking",
          "Line, polyline, offset, trim, fillet, array and hatching",
          "Layers, blocks, attributes and title blocks",
        ],
        outcome: "Accurate, layered 2D plans and part views drawn from dimensions",
      },
      {
        id: "02",
        name: "Dimensioning, Layouts & Plotting",
        weeks: "Month 2",
        summary: "Dimension drawings to standard and turn them into scaled, printed sheets. Common to both streams.",
        topics: [
          "Dimension and text styles for civil and mechanical drawings",
          "Tolerances, multileaders and tables",
          "Model space, paper space, viewports and scales",
          "Page setups, plot styles and plotting to PDF / A3 / A1",
        ],
        outcome: "Fully dimensioned drawings plotted to scale with a title block",
      },
      {
        id: "03",
        name: "Isometric, 3D Basics & Stream Drawings",
        weeks: "Month 3",
        summary: "Move into pictorial and 3D views, then produce a set of drawings for your own stream.",
        topics: [
          "Isometric drawing and 3D basics: extrude, revolve, solid editing",
          "Civil: floor plan, elevation and section of a house",
          "Mechanical: orthographic, sectional and assembly views of components",
          "Introduction to your stream's 3D software",
        ],
        outcome: "A stream-specific drawing portfolio — end of the 3-month track",
      },
      {
        id: "04",
        name: "3D Modelling: Revit (Civil) or SolidWorks / CATIA (Mechanical)",
        weeks: "Months 4–5",
        summary: "Learn your stream's main 3D tool in depth, one project at a time.",
        topics: [
          "Civil: Revit levels, grids, walls, floors, roofs, stairs and families",
          "Civil: rooms, areas and a complete building model",
          "Mechanical: sketches, part features, patterns and configurations",
          "Mechanical: assemblies, mates, interference checks and exploded views",
        ],
        outcome: "A complete building model (civil) or a working mechanical assembly (mechanical)",
      },
      {
        id: "05",
        name: "Documentation & Detailing",
        weeks: "Month 6",
        summary: "Turn 3D models into the sheets and data that go to site or the shop floor.",
        topics: [
          "Civil: Revit sheets, sections, schedules and quantity take-off",
          "Civil: annotation, tags and exporting to DWG / PDF",
          "Mechanical: sheet metal, weldments and flat patterns",
          "Mechanical: manufacturing drawings with tolerances, balloons and BOM",
        ],
        outcome: "A documented drawing set from your model — end of the 6-month track",
      },
      {
        id: "06",
        name: "Visualisation (Civil) or CNC Programming (Mechanical)",
        weeks: "Month 7",
        summary: "Take your models to the next stage: presentation for civil, machining for mechanical.",
        topics: [
          "Civil: 3ds Max modelling of interiors and building exteriors from AutoCAD / Revit data",
          "Civil: materials, textures and camera setup",
          "Mechanical: CNC axes, work and tool offsets, G & M codes",
          "Mechanical: turning and milling programs verified on a CNC simulator",
        ],
        outcome: "A textured 3D scene (civil) or simulator-verified CNC programs (mechanical)",
      },
      {
        id: "07",
        name: "Rendering (Civil) or CAM Toolpaths (Mechanical)",
        weeks: "Month 8",
        summary: "Finish the stream with client-ready output or production-ready code.",
        topics: [
          "Civil: lighting, V-Ray rendering and post-production",
          "Civil: walkthrough and presentation images",
          "Mechanical: 2D and 3D toolpaths from CAD models in CAM software",
          "Mechanical: tooling, speeds and feeds, simulation and post-processing",
        ],
        outcome: "Rendered interior / exterior views (civil) or posted CAM programs with setup sheets (mechanical)",
      },
      {
        id: "08",
        name: "Live Project, Portfolio & Interview Prep",
        weeks: "Month 9",
        summary: "Apply the whole stream to one project and prepare to apply for jobs.",
        topics: [
          "Civil: a house or small commercial building from plan to BIM model to render",
          "Mechanical: a product or fixture from drawing to assembly to CAM program",
          "Portfolio review and presentation of your work",
          "Resume, mock interviews and placement support",
        ],
        outcome: "A complete project and portfolio — end of the 9-month track",
      },
    ],
  },
  tools: {
    eyebrow: "Software you will use",
    title: "Installed on every lab workstation",
    text: "Everyone learns AutoCAD first; the rest depends on your stream. You work on your own workstation in every class.",
    tools: [
      { name: "AutoCAD", logo: "autocad.png", use: "2D drafting & 3D basics (both streams)" },
      { name: "Revit Architecture", logo: "revit.svg", use: "BIM models & sheets (civil)" },
      { name: "3ds Max", logo: "autodesk.svg", use: "Interior & exterior renders (civil)" },
      { name: "SolidWorks", logo: "solidworks.png", use: "Parts, assemblies & drawings (mechanical)" },
      { name: "CATIA V5", logo: "catia.svg", use: "Solids & surfaces (mechanical)" },
      { name: "CNC Simulator & CAM", mono: "CAM", use: "G-code & toolpath verification (mechanical)" },
      { name: "MS Excel", logo: "excel.png", use: "Schedules, BOMs & cutting data" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Get certified in Civil / Mechanical CAD",
    text: "Complete your track and its assignments to receive a techcadd certificate you can attach to job applications — verifiable online. The 6 and 9-month tracks also include an internship letter.",
    courseName: "Civil / Mechanical CAD Program",
    items: [
      { title: "Program certificate", text: "Verifiable online by employers" },
      { title: "Internship letter", text: "Included on the 6 and 9-month tracks" },
      { title: "Portfolio", text: "Drawings, models, renders or CNC programs" },
      { title: "Placement support", text: "Resume help and job-drive updates" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where this program takes you",
    text: "Indicative starting pay for fresher roles in Punjab. Actual offers depend on the employer, your stream, your track length, your portfolio and how you interview.",
    roles: [
      { title: "CAD Draughtsman", pay: "₹10k – 18k", text: "Architects, builders, consultants and workshops" },
      { title: "Revit / BIM Modeller", pay: "₹12k – 20k", text: "Architecture and construction design offices" },
      { title: "Mechanical Design Engineer", pay: "₹12k – 20k", text: "Machine builders and product manufacturers" },
      { title: "CNC Programmer", pay: "₹12k – 20k", text: "Machine shops and production units" },
    ],
    hiring: ["Architects & consultants", "Builders & contractors", "Interior design firms", "Manufacturing units", "Fabrication & machine shops", "Auto-parts suppliers"],
    qa: [
      {
        q: "Should I choose the civil or mechanical stream?",
        a: "Usually your qualification decides it — civil and architecture students take Revit and 3ds Max, mechanical and ITI students take SolidWorks / CATIA and CNC & CAM. Both start with the same AutoCAD foundation, so you can decide after Month 1.",
      },
      {
        q: "Is the 3-month track enough to get a job?",
        a: "It is enough for draughtsman and design-assistant roles if your drawings are accurate. The 6 and 9-month tracks add a 3D tool, an internship letter and a bigger portfolio, which widens your options.",
      },
      {
        q: "Is CNC taught on a real machine?",
        a: "CNC programming is taught on CNC simulators and CAM software. Every program is verified in simulation, which is how programmers check code before it reaches a machine.",
      },
      {
        q: "Can I freelance after this program?",
        a: "Many students take house-plan, BIM, rendering or part-drawing work from local builders and workshops. The portfolio you build here is a good starting point.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Projects you will complete",
    text: "Each module ends with work you finish yourself. How many of these you complete depends on your track and stream.",
    items: [
      { n: "01", title: "House drawing set", text: "Dimensioned floor plan, elevation and section of a 2-storey house, plotted to scale on an A3 sheet.", tags: ["AutoCAD", "Plotting", "Both streams"] },
      { n: "02", title: "Machine part & assembly views", text: "Orthographic, sectional and assembly views of a component with tolerances and a title block.", tags: ["AutoCAD", "Mechanical"] },
      { n: "03", title: "BIM model & render", text: "A residential building modelled in Revit with sheets and schedules, then rendered in 3ds Max.", tags: ["Revit", "3ds Max", "Civil"] },
      { n: "04", title: "Assembly to CNC program", text: "A mechanical assembly in SolidWorks or CATIA, with drawings and a CAM toolpath verified on a simulator.", tags: ["SolidWorks / CATIA", "CAM", "Mechanical"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "See it. Build it. Check it.",
    text: "Every command and feature is learned inside a real drawing, model or program, then checked before you move on.",
    steps: [
      { title: "See it", text: "The trainer demonstrates the step on a live project on the big screen.", example: "Offsetting walls / revolving a shaft" },
      { title: "Build it", text: "You apply it to your own project while the trainer checks your screen.", example: "Drafting your floor plan or flange" },
      { title: "Check it", text: "Your work is checked for accuracy, standards and a clean model before you move on.", example: "Plotting to scale or simulating the code" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose the CAD program at ${site.name}`,
    text: `There are many places to learn CAD software in ${site.city}. What differs is whether you follow a planned path, produce real drawings and models, and have someone check your work.`,
    items: [
      { title: "A planned path", text: "AutoCAD first, then one stream in depth — no unrelated short courses." },
      { title: "One workstation each", text: "You draft, model or program every minute of lab time." },
      { title: "Small batches", text: "Small enough that every drawing and model gets checked." },
      { title: "Stream-specific practice", text: "Civil and mechanical students work on projects from their own field." },
      { title: "Placement support", text: "Resume help, portfolio review and job drives with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any CAD program, including this one.",
    rows: [
      { feature: "Structure", us: "3, 6 or 9-month path, each continuing the last", them: "Separate short courses with no plan" },
      { feature: "Practice time", us: "One workstation per student, every class", them: "Shared systems or demo-only classes" },
      { feature: "Batch size", us: "Small batches with work checked", them: "Large batches, little feedback" },
      { feature: "Streams", us: "Separate civil and mechanical modules", them: "One generic syllabus" },
      { feature: "CNC & CAM", us: "Programs verified on simulators and CAM software", them: "Often theory only" },
      { feature: "Timings", us: "Morning, evening, weekend, 1-on-1", them: "Fixed single slot" },
      { feature: "Portfolio", us: "Drawings, models and projects you made", them: "Usually none" },
      { feature: "Certificate", us: "Verifiable certificate, internship letter on 6+ months, placement support", them: "Varies" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Manpreet Singh", role: "Civil Diploma Student · Jalandhar", text: "Did AutoCAD and then Revit in the 6-month track. My house model and sheets were the first thing the interviewer looked at." },
    { name: "Simranjeet Kaur", role: "B.Tech Civil · Kapurthala", text: "Weekend batch worked with college. Trainer checked every drawing, and the 3ds Max renders came out much better than I expected." },
    { name: "Lovepreet Singh", role: "ITI Fitter · Nakodar", text: "Started from AutoCAD and moved to SolidWorks and CNC programming. Writing and simulating the G-code myself made it clear." },
    { name: "Gagandeep Sharma", role: "Mechanical Diploma · Phagwara", text: "The assembly and drawing set from the course helped me get a CAD job. Small batch, so doubts got cleared the same day." },
    { name: "Ramandeep Kaur", role: "Interior Design Student · Model Town", text: "Plans in AutoCAD, then 3ds Max for rendering. Good step-by-step order, nothing felt rushed." },
    { name: "Jaskaran Singh", role: "Production Staff · Focal Point", text: "Came in the evening batch after duty. Now I can model fixtures and read CAM programs at work." },
  ],
  faqs: [
    { q: "What is the difference between the 3, 6 and 9-month tracks?", a: "The 3-month track covers the AutoCAD foundation and stream drawings. The 6-month track adds one 3D stream — Revit for civil, SolidWorks or CATIA for mechanical. The 9-month track completes the stream with 3ds Max rendering or CNC Programming & CAM, plus a live project." },
    { q: "Do I need a technical background?", a: "No, but it helps to read simple drawings. Basic computer use is enough to start; the program begins from drawing setup and coordinates." },
    { q: "When do I choose civil or mechanical?", a: "The first months are common to both. You choose your stream by Month 3, and a counsellor or trainer can help you decide based on your qualification and goals." },
    { q: "Is CNC taught on a real machine?", a: "No. CNC programming is taught on simulators and CAM software, where every program is verified before it is accepted." },
    { q: "Will I get a certificate and internship letter?", a: "Every track gives a techcadd certificate that can be verified online. The 6 and 9-month tracks also include an internship letter." },
    { q: "What batch timings are available?", a: "Morning, afternoon, evening and weekend batches, plus 1-on-1 slots on request." },
    { q: "Is there placement support?", a: "Yes — resume help, portfolio review and job-drive updates with 500+ hiring partners. We do not promise a job, but we help you prepare and apply." },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, see the CAD lab and talk to a counsellor before you decide." },
  ],
  program: {
    category: "civil-mechanical",
    feeSource: "autocad-training-in-jalandhar",
    tracksTitle: "Choose your Civil / Mechanical CAD track",
    tracksText: "Every track starts with AutoCAD; the longer ones continue into a civil or mechanical 3D stream. Pick the length that matches how far you want to go.",
    tracks: [
      {
        kind: "Program",
        duration: "3 Months",
        text: "The AutoCAD foundation: 2D drafting, dimensioning, layouts, plotting, isometric and 3D basics, with a drawing set for your civil or mechanical stream.",
      },
      {
        kind: "Certificate Program",
        duration: "6 Months",
        text: "Everything in 3 months, then one 3D stream in depth — Revit Architecture for civil or SolidWorks / CATIA for mechanical — with documentation and an internship letter.",
      },
      {
        kind: "Diploma Program",
        duration: "9 Months",
        text: "Everything in 6 months, then the full stream — 3ds Max rendering for civil or CNC Programming & CAM on simulators for mechanical — finished with a live project and portfolio.",
      },
    ],
    fit: {
      title: "Not sure if CAD is the right fit?",
      text: "Book a free demo class or a quick counsellor call — we will help you choose the civil or mechanical stream and the track length that suits your goals.",
    },
  },
};
