// Certificate program page for the "Digital Marketing" category, served at
// /internship-training/digital-marketing-courses-in-jalandhar. Same shape as a course detail page
// (see ../courseDetails/types.ts) plus `program` (tracks and the "right fit?" banner). Track fees are
// read from lib/referenceContent.ts via program.feeSource, so no fees are written here.
import { site } from "../site";
import type { CourseDetail } from "../courseDetails/types";

export const digitalMarketingProgram: CourseDetail = {
  slug: "digital-marketing-courses-in-jalandhar",
  seo: {
    title: `Digital Marketing Training in ${site.city} | 3, 6 & 9-Month Certificate Programs`,
    description: `Certificate programs in digital marketing at ${site.name} ${site.city}: marketing funnels, WordPress, SEO, Google Ads, Meta Ads, social media, email and WhatsApp marketing and GA4 reporting, with live client work, an internship letter on 6 and 9-month tracks and placement support.`,
  },
  hero: {
    crumb: "Digital Marketing",
    tag: "Certificate Program",
    badge: "Live Client Work",
    title: `Best Digital Marketing Training in ${site.city}`,
    text: `One program that takes you from how customers find a business online to running SEO, Google Ads, Meta Ads, social media and email for real clients, and reporting the results. Choose a 3, 6 or 9-month track at ${site.name} ${site.city}. Every track uses live websites and ad accounts, not slides.`,
    points: ["3, 6 or 9 months", "Live client work", "Google & Meta ads", "Placement support"],
    facts: [
      { label: "Mode", value: "Classroom & 1-on-1" },
      { label: "Project", value: "Live Client Work" },
      { label: "Certificate", value: "Verifiable online" },
      { label: "Includes", value: "Internship letter (6 & 9 months)" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "500+", label: "Hiring partners", note: "for placement support" },
    ],
    hub: {
      center: "google-ads.svg",
      nodes: [
        { logo: "meta.svg" },
        { logo: "google-analytics.svg" },
        { logo: "search-console.svg" },
        { logo: "wordpress.svg" },
        { logo: "semrush.svg" },
        { logo: "canva.svg" },
        { icon: "📈" },
        { icon: "@" },
      ],
    },
  },
  overview: {
    eyebrow: "Program overview",
    title: "The whole digital marketing job, at the length that suits you",
    paragraphs: [
      `${site.name}'s Digital Marketing certificate program in ${site.city} is for people who want to be hired as digital marketers, take on clients of their own, or bring a family business online. It teaches the subject as one connected system rather than a pile of separate tools.`,
      "Everything starts with the customer: who they are, how they search and what makes them enquire. Then you build a WordPress website and landing pages, earn traffic through SEO and social media, buy it through Google Ads and Meta Ads, and bring people back through email and WhatsApp. GA4 and Search Console are set up in the first weeks and used in every module after that, so decisions come from numbers, not guesswork.",
      "The 3-month track gives you a strong organic foundation. The 6-month Certificate Program adds paid ads, retention marketing and live client work, and the 9-month Diploma Program adds advanced analytics, attribution and a full client project with placement preparation. Whichever track you pick, you leave with work you can show in an interview or to a first client.",
    ],
    image: "digital-marketing.webp",
    imageAlt: "Students planning a digital marketing campaign in the techcadd lab",
    imageTag: "Live accounts, real data",
    getList: [
      "A WordPress website and landing pages you build and own",
      "Hands-on SEO, Google Ads and Meta Ads work on live accounts",
      "Content calendars, email flows and WhatsApp follow-ups",
      "GA4, Search Console and Looker Studio reports",
      "Certificate verifiable online + a client-work portfolio",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "3", label: "Track lengths" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who this program is for",
    text: "You need basic computer and internet skills and the patience to test, measure and adjust. No coding and no marketing degree are needed.",
    items: [
      { icon: "grad", title: "Graduates & final-year students", text: "BBA, B.Com, BA or BCA students who want a practical skill that agencies and local businesses hire for directly." },
      { icon: "job", title: "Job seekers & career switchers", text: "Move from sales, telecalling or office work into a marketing role where your results can be measured and shown." },
      { icon: "shop", title: "Business owners", text: "Run your own Google, Instagram and WhatsApp marketing, and judge whether an agency is really delivering." },
      { icon: "freelance", title: "Aspiring freelancers", text: "Learn the services local clients pay for, such as Google Business Profile, ads, social media handling and SEO." },
      { icon: "chart", title: "Sales & marketing staff", text: "Understand leads, cost per lead and campaign reports so you can plan marketing, not just forward agency PDFs." },
      { icon: "home", title: "Homemakers & home entrepreneurs", text: "Promote a home bakery, boutique or tuition class online, with weekend and 1-on-1 slots that fit your day." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why a structured program beats collecting tutorials",
    feature: {
      tag: "Access",
      title: "Batches that fit around work and college",
      text: `Students join the ${site.city} centre from Model Town, Urban Estate, Rama Mandi and Basti Sheikh, and weekend learners come in from Phagwara, Kapurthala, Nakodar and Hoshiarpur. Morning, evening, weekend and 1-on-1 slots let you learn alongside a job or college, and ad-account work can continue from home between classes.`,
      slots: ["Morning", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Complete",
        title: "Every channel, in the right order",
        text: "Funnel, website, SEO, social, ads, retention and analytics are taught in the order a real campaign is built, so you see how a search or a reel turns into a phone call.",
      },
      {
        tag: "Method",
        title: "Live accounts, not screenshots",
        text: "You set up campaigns, tracking and reports yourself inside the real tools, and the trainer reviews your account settings, not just your answers.",
      },
      {
        tag: "Client work",
        title: "Briefs from real businesses",
        text: "On the 6 and 9-month tracks you work on live client briefs under supervision: the deadlines, feedback and reporting a marketing job actually involves.",
      },
      {
        tag: "Current",
        title: "Taught as the platforms work today",
        text: "GA4, Performance Max, Meta Advantage+ campaigns, AI-generated search results and WhatsApp Business are all covered, and the syllabus changes as the tools do.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Local businesses are moving online and need people who can run it",
    points: [
      `Immigration consultancies, coaching centres, clinics, showrooms and export houses around ${site.city} now get most of their enquiries from Google, Instagram and WhatsApp, and many still have no trained person in-house to manage it.`,
      "Entry-level digital marketing roles in Punjab typically start around ₹12,000 – ₹20,000 a month, and pay grows with results you can prove rather than years served.",
      "The same skills work for a job, for freelancing or for your own business, and a longer track lets you reach the level where clients trust you with a budget.",
    ],
    panel: [
      { k: "Google Search", v: "Where buyers look first" },
      { k: "Instagram & Reels", v: "Where brands are discovered" },
      { k: "WhatsApp", v: "Where enquiries close" },
      { k: "GA4 reports", v: "How results are proven" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, month by month",
    text: "The full nine-month path, in the order a real campaign is built. The 3-month track covers Months 1–3, the 6-month Certificate Program continues to Month 6, and the 9-month Diploma Program runs to the end.",
    phases: [
      {
        id: "01",
        name: "Marketing Funnels, Audiences & Positioning",
        weeks: "Month 1",
        summary: "Understand how customers find, compare and choose a business online.",
        topics: [
          "The marketing funnel: awareness, consideration, conversion, loyalty",
          "Buyer personas and audience research for local businesses",
          "Positioning, offers and competitor comparison",
          "Key metrics: CTR, CPC, CPL, conversion rate and ROAS",
        ],
        outcome: "A one-page marketing plan for a sample business",
      },
      {
        id: "02",
        name: "Website Basics, Landing Pages & WordPress",
        weeks: "Months 1–2",
        summary: "Build the website and landing pages every other module sends traffic to.",
        topics: [
          "Domain, hosting and WordPress set-up",
          "Themes, page builders and essential plugins",
          "Landing pages, lead forms and WhatsApp buttons",
          "Speed, mobile layout, GA4 and Search Console set-up",
        ],
        outcome: "Your own live WordPress site with a working landing page",
      },
      {
        id: "03",
        name: "SEO: Keywords, On-Page & Technical",
        weeks: "Months 2–3",
        summary: "Earn steady, free traffic from Google search and maps.",
        topics: [
          "Keyword research and search intent",
          "On-page SEO: titles, headings, content and internal links",
          "Technical SEO: indexing, sitemaps and Core Web Vitals",
          "Local SEO, Google Business Profile and link building",
        ],
        outcome: "An SEO audit and keyword plan for your website",
      },
      {
        id: "04",
        name: "Social Media Planning & Content",
        weeks: "Month 3",
        summary: "Plan and create content that grows a brand on Instagram, Facebook and YouTube.",
        topics: [
          "Platform strategy and brand voice",
          "Reels, carousels and posting schedules",
          "Content calendars and Canva design",
          "Community management and handling enquiries",
        ],
        outcome: "A one-month content calendar with designed posts",
      },
      {
        id: "05",
        name: "Google Ads: Search, Display & Shopping",
        weeks: "Months 4–5",
        summary: "Buy targeted traffic and account for every rupee spent.",
        topics: [
          "Account structure, keywords, match types and bidding",
          "Responsive search ads, assets and conversion tracking",
          "Display, YouTube and Demand Gen campaigns",
          "Merchant Center, Shopping and Performance Max basics",
        ],
        outcome: "A Search campaign built and launched on a live account",
      },
      {
        id: "06",
        name: "Meta Ads, Email & WhatsApp Marketing",
        weeks: "Months 5–6",
        summary: "Run the lead campaigns local businesses rely on, then bring enquiries back.",
        topics: [
          "Meta campaign structure, audiences, Pixel and creative testing",
          "Lead forms, Click-to-WhatsApp and Advantage+ campaigns",
          "Email lists, newsletters and automated sequences",
          "WhatsApp Business: catalogues, labels, broadcasts and follow-ups",
        ],
        outcome: "A Meta lead campaign plus an email and WhatsApp follow-up flow for a live client brief",
      },
      {
        id: "07",
        name: "Analytics, Attribution & Reporting",
        weeks: "Months 7–8",
        summary: "Prove what worked across every channel, and explain it to a client.",
        topics: [
          "GA4 events, key events and custom reports",
          "UTM tagging and Google Tag Manager basics",
          "Attribution: comparing channels and paths to conversion",
          "Monthly client dashboards in Looker Studio",
        ],
        outcome: "A multi-channel monthly report with recommendations",
      },
      {
        id: "08",
        name: "Live Project Work & Placement Preparation",
        weeks: "Months 8–9",
        summary: "Run a full client project end to end and get ready for interviews.",
        topics: [
          "A supervised live client project across SEO, ads and social",
          "Budgets, proposals and client communication",
          "Preparing for Google Skillshop and Meta certification exams",
          "Portfolio, resume and mock interviews",
        ],
        outcome: "A complete client project and portfolio presented to the batch",
      },
    ],
  },
  tools: {
    eyebrow: "Tools you will use",
    title: "The same tools agencies use every day",
    text: "Each tool is used hands-on in class: you set up the accounts, build the campaigns and pull the reports yourself.",
    tools: [
      { name: "Google Ads", logo: "google-ads.svg", use: "Search, Display, YouTube & Shopping" },
      { name: "Meta Ads Manager", logo: "meta.svg", use: "Facebook & Instagram ads" },
      { name: "Google Analytics 4", logo: "google-analytics.svg", use: "Traffic, conversions & attribution" },
      { name: "Search Console", logo: "search-console.svg", use: "Google search performance" },
      { name: "WordPress", logo: "wordpress.svg", use: "Websites & landing pages" },
      { name: "Canva", logo: "canva.svg", use: "Posts, reels & ad creatives" },
      { name: "SEMrush", logo: "semrush.svg", use: "Keyword & competitor research" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Get certified in Digital Marketing",
    text: `Complete your track and its practical projects to receive a ${site.name} certificate, verifiable online. The 6 and 9-month tracks also include an internship letter for your live client work. We prepare you for Google's free Skillshop exams and Meta's certification exams, which you sit on your own account.`,
    courseName: "Digital Marketing",
    items: [
      { title: "Program certificate", text: "Verifiable online by any employer" },
      { title: "Internship letter", text: "On the 6 and 9-month tracks" },
      { title: "Certification prep", text: "Google Skillshop and Meta exam practice" },
      { title: "Placement support", text: "Resume, mock interviews and job drives" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where this program takes you",
    text: "Indicative monthly starting pay for freshers in Punjab. Actual offers depend on the employer, your portfolio and how you interview. Freelance income depends entirely on the clients you find.",
    roles: [
      { title: "Digital Marketing Executive", pay: "₹12k – 20k", text: "Agencies and in-house teams handling SEO, ads and social" },
      { title: "SEO Executive", pay: "₹10k – 18k", text: "Keyword research, on-page work and reporting" },
      { title: "Social Media Executive", pay: "₹10k – 18k", text: "Content calendars, reels and page growth for brands" },
      { title: "Performance Marketing Executive", pay: "₹14k – 22k", text: "Google and Meta ad campaigns, budgets and tracking" },
    ],
    hiring: ["Digital marketing agencies", "Immigration & IELTS consultancies", "Coaching centres & schools", "Hospitals & clinics", "Export houses & manufacturers", "Real estate & showrooms"],
    qa: [
      {
        q: "Which track should I choose?",
        a: "Choose 3 months if you want a solid foundation or are marketing your own business. Choose 6 or 9 months if you are aiming for a job or clients, because those tracks add paid ads, live client work and an internship letter.",
      },
      {
        q: "Can I get a job without experience?",
        a: "Yes, many agencies and local businesses hire freshers as executives. The website, audits, campaign reports and client work from your track serve as your experience in the interview.",
      },
      {
        q: "Can I start freelancing?",
        a: "You can, but expect it to grow slowly. Most people start with one or two small local clients, for example Google Business Profile, social handling or basic ads, and build from there. We guide you on pricing, proposals and reporting.",
      },
      {
        q: "Is placement guaranteed?",
        a: "No institute can honestly guarantee a job. We give placement support: resume and portfolio help, mock interviews, and openings and job drives from our 500+ hiring partners.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real projects you will complete",
    text: "Every project is built on a live website or account, reviewed by your trainer and added to the portfolio you take to interviews. The later projects belong to the 6 and 9-month tracks.",
    items: [
      { n: "01", title: "Your own business website", text: "Build a WordPress site with a landing page, lead form and WhatsApp button, connected to GA4 and Search Console.", tags: ["WordPress", "GA4"] },
      { n: "02", title: "SEO audit & content calendar", text: "Audit a local business website, write a prioritised fix list, and plan a month of social content around its keywords.", tags: ["SEO", "Canva"] },
      { n: "03", title: "Live ad campaigns", text: "Set up a Google Search campaign and a Meta lead campaign on small budgets, then report cost per lead and what you changed.", tags: ["Google Ads", "Meta Ads"] },
      { n: "04", title: "Live client project & report", text: "Work on a real client brief across channels, then present a monthly Looker Studio report with next steps.", tags: ["Client work", "Reporting"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "Learn it. Launch it. Measure it.",
    text: "Digital marketing is learned by doing and checking the numbers, so every topic follows the same three steps.",
    steps: [
      { title: "Learn it", text: "The trainer explains the idea and shows it inside the real tool.", example: "Keyword match types" },
      { title: "Launch it", text: "You set it up yourself on your own website or a client account.", example: "Building an ad group" },
      { title: "Measure it", text: "You check the data, find what to change and adjust.", example: "Pausing costly keywords" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name}`,
    text: `There is no shortage of digital marketing courses in ${site.city}. What matters is how much time you spend inside real tools, whether your work is reviewed, and whether anyone helps you after the certificate.`,
    items: [
      { title: "Trainers who run campaigns", text: "Taught by people who work in ad accounts and analytics, not just from slides." },
      { title: "Live client work", text: "Supervised client briefs on the 6 and 9-month tracks, with an internship letter." },
      { title: "Small batches", text: "Your campaigns and reports get individual review, not a quick glance." },
      { title: "Flexible timings", text: "Morning, evening, weekend and 1-on-1 batches to fit work or college." },
      { title: "Placement support", text: "Resume and portfolio help, mock interviews and job drives with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any digital marketing program, including this one.",
    rows: [
      { feature: "Practice", us: "Live websites and ad accounts", them: "Mostly theory and screenshots" },
      { feature: "Client work", us: "Supervised live client briefs (6 & 9 months)", them: "Dummy projects only" },
      { feature: "Paid ads", us: "Google Ads and Meta Ads both covered", them: "Usually only one platform" },
      { feature: "Analytics", us: "GA4, attribution and client reporting", them: "One short session" },
      { feature: "Batch size", us: "Small batches with account reviews", them: "Large batches" },
      { feature: "Track length", us: "3, 6 or 9 months, continuing step by step", them: "One fixed course" },
      { feature: "Timings", us: "Morning, evening, weekend, 1-on-1", them: "Fixed single slot" },
      { feature: "After the course", us: "Placement and freelancing guidance", them: "Limited or none" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Gurpreet Singh", role: "Digital Marketing Executive · Jalandhar", text: "The 6-month track had real client work. I showed that report in my interview and it made the conversation easy." },
    { name: "Simran Kaur", role: "B.Com Graduate · Model Town", text: "Building our own website first helped a lot. After that every SEO and ads class made sense because I could see my own data." },
    { name: "Manpreet Kaur", role: "Boutique Owner · Urban Estate", text: "Did the 3-month track for my shop. Now I post regularly and handle my Google Business Profile myself." },
    { name: "Arshdeep Singh", role: "Freelancer · Phagwara", text: "Picked up two small local clients after the course. Slow start, but the proposal and reporting guidance was useful." },
    { name: "Navneet Sharma", role: "Marketing Assistant · Kapurthala", text: "The analytics and Looker Studio part was the best. I make our monthly report myself now instead of waiting for the agency." },
    { name: "Rajveer Singh", role: "Evening Batch Student · Rama Mandi", text: "Evening batch worked with my job. Small group, and sir actually checked our ad accounts every week." },
  ],
  faqs: [
    { q: "What is the difference between the 3, 6 and 9-month tracks?", a: "They are the same program at three lengths. 3 months covers funnels, WordPress, SEO and social media. 6 months adds Google Ads, Meta Ads, email and WhatsApp marketing and live client work. 9 months adds advanced analytics, attribution, a full client project and placement preparation." },
    { q: "Do I need any technical or coding knowledge?", a: "No. Basic computer and internet use is enough. WordPress is set up without coding, and everything else is taught step by step." },
    { q: "Can I start with 3 months and extend later?", a: "Yes. Each longer track continues from where the shorter one ends, so you can extend without repeating what you have already learned. Ask a counsellor about the timing." },
    { q: "Will I run real ad campaigns?", a: "Yes. You build and launch campaigns on live accounts with small daily budgets, and the trainer helps you set limits so spending stays under control." },
    { q: "Do I get a certificate and internship letter?", a: `Every track ends with a ${site.name} certificate, verifiable online. The 6 and 9-month tracks also include an internship letter for your live client work.` },
    { q: "Are Google and Meta certifications included?", a: "We prepare you for Google's free Skillshop exams and Meta's certification exams. They are the platforms' own exams, which you take on your own account." },
    { q: "Is placement support available?", a: "Yes. We help with your resume and portfolio, run mock interviews and share openings and job drives from our hiring partners. Placement support is not a job guarantee." },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, see the lab and meet the trainer before you decide." },
  ],
  program: {
    category: "digital-marketing",
    feeSource: "digital-marketing-training-in-jalandhar",
    tracksTitle: "Choose your Digital Marketing track",
    tracksText: "The same subject at three lengths. Each longer track continues where the shorter one ends, so you can start small and extend later without repeating anything.",
    tracks: [
      {
        kind: "Program",
        duration: "3 Months",
        text: "Marketing funnels, a WordPress website with landing pages, SEO and social media content: a strong organic foundation for your own business or a first step into the field.",
      },
      {
        kind: "Certificate Program",
        duration: "6 Months",
        text: "Everything in 3 months, then Google Ads, Meta Ads, email and WhatsApp marketing on live accounts, with supervised client work and an internship letter.",
      },
      {
        kind: "Diploma Program",
        duration: "9 Months",
        text: "Everything in 6 months, then advanced analytics, attribution and client reporting, a full live client project, and placement preparation with certification exam practice.",
      },
    ],
    fit: {
      title: "Not sure if Digital Marketing is the right fit?",
      text: "One call with a counsellor is usually enough to find out. Book a free demo class and see the lab before you decide.",
    },
  },
};
