// Certificate program page for the "Graphic Designing" category. See ../courseDetails/types.ts.
import { site } from "../site";
import type { CourseDetail } from "../courseDetails/types";

export const graphicDesignProgram: CourseDetail = {
  slug: "graphic-design-courses-in-jalandhar",
  seo: {
    title: `Graphic Design Certificate Program in ${site.city} | 3, 6 & 9 Month Tracks`,
    description: `Build a graphic design career at ${site.name} ${site.city}: Photoshop, Illustrator, CorelDRAW, InDesign and Canva, then branding, print production, social creatives, packaging and a portfolio. 3, 6 and 9 month tracks with a verifiable certificate and placement support.`,
  },
  hero: {
    crumb: "Graphic Designing",
    tag: "Graphic Design Program",
    badge: "3 · 6 · 9 Month Tracks",
    title: `Best Graphic Design Certificate Program in ${site.city}`,
    text: `A step-by-step path into design work: learn the tools local studios, printers and agencies use, then branding, print production, social creatives and packaging, and finish with a portfolio. Choose a 3, 6 or 9 month track at ${site.name} ${site.city} and go as far as your goals need.`,
    points: ["5 design tools", "Branding, print & social", "Portfolio you can show", "Placement support"],
    facts: [
      { label: "Duration", value: "3 · 6 · 9 Months" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "10th pass, basic computer use" },
      { label: "Includes", value: "Certificate + portfolio; internship letter on 6 & 9 months" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "500+", label: "Hiring partners", note: "for placement support" },
    ],
    hub: {
      center: "illustrator.svg",
      nodes: [
        { logo: "photoshop.png" },
        { logo: "coreldraw.png" },
        { logo: "indesign.svg" },
        { logo: "canva.svg" },
        { logo: "meta.svg" },
        { logo: "photoshop.png" },
        { icon: "🎨" },
        { icon: "✎" },
      ],
    },
  },
  overview: {
    eyebrow: "Program overview",
    title: "One program, a complete design career path",
    paragraphs: [
      `${site.name}'s Graphic Design certificate program in ${site.city} is built for people who want design to be their work, not just a skill on a CV — at a printing press, an ad agency, an in-house marketing team, or taking small freelance jobs alongside.`,
      "Every track starts with the basics that make a design look right — layout, colour and typography — and the core tools: Photoshop for photos and social posts, Illustrator for logos and vector artwork, CorelDRAW for the flex, cards and print jobs Punjab's printers run on, and Canva for quick resizing. Longer tracks add brand identity, print production and social media campaigns, then InDesign publications, packaging and live client-style work.",
      "Because the tracks build on each other, you can start with three months and extend later without repeating anything. Every design you make is reviewed by a trainer the way a client or art director would review it, and it all adds up to a portfolio you can show at interviews.",
    ],
    image: "graphic-design.webp",
    imageAlt: "Students working on design projects in the techcadd lab",
    imageTag: "Design every class",
    getList: [
      "Photoshop, Illustrator, CorelDRAW, InDesign and Canva on your own lab computer",
      "Branding, print production and social media work on longer tracks",
      "Client-style briefs with trainer feedback on every design",
      "A portfolio of print and digital work, ready for interviews",
      "Verifiable certificate, internship letter on 6 & 9 month tracks",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "3", label: "Track options" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who this program is for",
    text: "You do not need to be good at drawing. You need basic computer use, an eye for what looks neat, and the patience to redo a design until it is right.",
    items: [
      { icon: "student", title: "10th & 12th pass students", text: "Start a creative career early, with a portfolio to show instead of just a marksheet." },
      { icon: "grad", title: "BA / B.Com / BFA students", text: "Add a practical design skill alongside your degree and build work you can show employers." },
      { icon: "design", title: "Aspiring designers", text: "Turn a hobby with Canva or phone apps into professional work in the tools studios expect." },
      { icon: "shop", title: "Print shop & studio staff", text: "Move from running machines to designing the flex, cards and invitations yourself." },
      { icon: "freelance", title: "Homemakers & freelancers", text: "Learn to design logos, posts and invitations for local clients, with flexible batch timings." },
      { icon: "office", title: "Business owners & marketers", text: "Make your own brochures, packaging and social posts instead of waiting on an outside designer." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why a full program, not just one tool",
    feature: {
      tag: "Access",
      title: "Batches that fit around college or work",
      text: `Design students come to the ${site.city} centre from Model Town, Urban Estate, Basti Sheikh, Rama Mandi and Jalandhar Cantt, with weekend learners travelling in from Phagwara, Kapurthala, Nakodar and Hoshiarpur. Morning, evening, weekend and 1-on-1 slots let you keep college or a job going while you train.`,
      slots: ["Morning", "Afternoon", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Range",
        title: "Employers want more than one tool",
        text: "A local studio may need a logo in Illustrator, a flex in CorelDRAW and a post in Photoshop on the same day. The program covers them all.",
      },
      {
        tag: "Depth",
        title: "Beyond buttons to real jobs",
        text: "Longer tracks cover branding, print production, packaging and publications — the work that separates a designer from a software operator.",
      },
      {
        tag: "Portfolio",
        title: "Designers are hired on their work",
        text: "Every track ends with finished pieces you can show. The longer the track, the broader and stronger the portfolio.",
      },
      {
        tag: "Flexibility",
        title: "Start short, extend later",
        text: "Begin with three months and continue to six or nine without repeating topics — the tracks are built to follow on from each other.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Design work in Punjab is steady and growing",
    points: [
      "Shops, salons, coaching centres, clinics and restaurants now post creatives every week, so design has become a regular need rather than a one-time job.",
      `${site.city}'s print shops, flex printers, wedding card makers and sports goods exporters need designers who can prepare files that print correctly the first time.`,
      "Fresher designers in Punjab typically start around ₹10,000 – ₹18,000 a month; pay tends to rise with a stronger portfolio and experience.",
    ],
    panel: [
      { k: "Social creatives", v: "Weekly posts & campaigns" },
      { k: "Print & flex", v: "Cards, banners, brochures" },
      { k: "Branding", v: "Logos & identity kits" },
      { k: "Packaging", v: "Boxes, labels, catalogues" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, month by month",
    text: "The 3-month track covers Months 1–3, the 6-month track continues to Month 6, and the 9-month track runs through all phases.",
    phases: [
      {
        id: "01",
        name: "Design Principles, Colour & Typography",
        weeks: "Month 1",
        summary: "Learn why some designs look professional and others do not.",
        topics: [
          "Layout, alignment, balance and white space",
          "Colour theory, RGB vs CMYK and colour palettes",
          "Choosing and pairing fonts, hierarchy and readability",
          "Reading a design brief and sketching ideas first",
        ],
        outcome: "Critique and fix a poorly designed poster",
      },
      {
        id: "02",
        name: "Photoshop & Canva",
        weeks: "Months 1–2",
        summary: "Edit photos and build image-based designs quickly.",
        topics: [
          "Layers, selections, masks and adjustment layers",
          "Background removal, retouching and colour correction",
          "Compositing, text effects and social post sizes",
          "Quick templates and resizing in Canva",
        ],
        outcome: "A retouched portrait and a festival sale poster",
      },
      {
        id: "03",
        name: "Illustrator & CorelDRAW",
        weeks: "Months 2–3",
        summary: "Draw clean vector artwork and prepare everyday print jobs.",
        topics: [
          "Pen tool, Shape Builder, Pathfinder and logo lettering",
          "Icons, simple illustrations and patterns",
          "CorelDRAW nodes, curves and real-size layouts",
          "Visiting cards, letterheads, flex banners and invitations",
        ],
        outcome: "A vector icon set, a visiting card set and a shop flex",
      },
      {
        id: "04",
        name: "Logo & Brand Identity",
        weeks: "Month 4",
        summary: "Design a brand from brief to final files.",
        topics: [
          "Research, mood boards and concept sketches",
          "Logo design, colour and font selection",
          "Stationery: card, letterhead, envelope",
          "A simple brand guideline sheet",
        ],
        outcome: "A complete identity kit for a local business",
      },
      {
        id: "05",
        name: "Print Production & Social Media Creatives",
        weeks: "Months 5–6",
        summary: "Make designs that print right and stay consistent online.",
        topics: [
          "Bleed, safe margins, CMYK, resolution and print-ready PDFs",
          "Flyers, tri-fold brochures and standees",
          "Post, story and ad sizes for Instagram and Facebook",
          "Monthly content templates in one brand style",
        ],
        outcome: "A print-ready brochure and a 9-post Instagram grid",
      },
      {
        id: "06",
        name: "InDesign & Publication Layout",
        weeks: "Month 7",
        summary: "Lay out multi-page documents neatly and consistently.",
        topics: [
          "Master pages, grids and text frames",
          "Paragraph and character styles",
          "Catalogues, magazines and menu cards",
          "Preflight and exporting print PDFs",
        ],
        outcome: "An 8–12 page product catalogue",
      },
      {
        id: "07",
        name: "Packaging Design",
        weeks: "Month 8",
        summary: "Design things that get printed, folded and sold.",
        topics: [
          "Box dielines, folds and panel layout",
          "Labels, stickers and product pouches",
          "3D mock-ups for presenting packaging",
        ],
        outcome: "A product box and label set with dielines",
      },
      {
        id: "08",
        name: "Live Client Work & Portfolio",
        weeks: "Month 9",
        summary: "Work on real-style briefs and present your best work.",
        topics: [
          "Client-style projects with feedback and revisions",
          "Mocking up and organising your best pieces",
          "A PDF portfolio and an online portfolio page",
          "Interview preparation and pricing small freelance jobs",
        ],
        outcome: "A finished portfolio ready for interviews",
      },
    ],
  },
  tools: {
    eyebrow: "Software you will use",
    title: "The industry's design tools, on every lab computer",
    text: "Each program is used on your own lab computer for the kind of work it is best at — not just shown on a projector.",
    tools: [
      { name: "Photoshop", logo: "photoshop.png", use: "Photo editing & social posts" },
      { name: "Illustrator", logo: "illustrator.svg", use: "Logos & vector artwork" },
      { name: "CorelDRAW", logo: "coreldraw.png", use: "Flex, cards & print jobs" },
      { name: "InDesign", logo: "indesign.svg", use: "Brochures & catalogues" },
      { name: "Canva", logo: "canva.svg", use: "Quick templates & resizing" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Get certified in Graphic Design",
    text: `Complete your track and its projects to receive a ${site.name} certificate — verifiable online — alongside the portfolio that actually gets designers hired.`,
    courseName: "Graphic Design Certificate Program",
    items: [
      { title: "Program certificate", text: "Verifiable online by any employer" },
      { title: "Design portfolio", text: "Print and digital work from your track" },
      { title: "Internship letter", text: "On the 6 and 9 month tracks" },
      { title: "Placement support", text: "Portfolio review, interviews and job updates" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where this program takes you",
    text: "Indicative starting pay for freshers in Punjab. Actual offers depend on the employer, your portfolio and how you interview.",
    roles: [
      { title: "Graphic Designer", pay: "₹10k – 18k", text: "Ad agencies, studios and in-house marketing teams" },
      { title: "DTP Operator", pay: "₹9k – 15k", text: "Printing presses, flex printers and publishers" },
      { title: "Social Media Designer", pay: "₹10k – 18k", text: "Agencies and brands posting creatives every week" },
      { title: "Freelance Designer", pay: "Varies", text: "Income depends on clients; most start small alongside a job" },
    ],
    hiring: ["Printing presses & flex printers", "Ad & digital agencies", "Sports goods & export houses", "Wedding card & studio shops", "Schools & coaching institutes", "Retail & real-estate brands"],
    qa: [
      {
        q: "Which track should I choose?",
        a: "If you want to learn the core tools for a job at a print shop or to design your own business material, 3 months is enough. For agency or in-house designer roles, 6 or 9 months gives you branding, print production and a stronger portfolio.",
      },
      {
        q: "Can I freelance after this program?",
        a: "Many students take small local jobs — logos, invitations, social posts — while they study or work. Income is irregular at first, so we suggest treating it as a side income until you have steady clients.",
      },
      {
        q: "Which program do employers ask for most?",
        a: "Print shops and flex printers in Punjab mostly use CorelDRAW; agencies and social media teams lean on Photoshop and Illustrator. The program covers all of them.",
      },
      {
        q: "What should I learn after this?",
        a: "Digital marketing pairs naturally with design, since you will already be making the creatives. Video editing or UI design are also popular next steps.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real projects in your portfolio",
    text: "Every phase ends with a client-style brief. These are the headline projects that anchor your portfolio, depending on your track.",
    items: [
      { n: "01", title: "Print-ready flex & visiting cards", text: "Design a shop flex and visiting card set at real sizes, prepared correctly for printing.", tags: ["CorelDRAW", "Print"] },
      { n: "02", title: "Brand identity kit", text: "Create a logo, colour palette, stationery and a simple guideline sheet for a local business.", tags: ["Illustrator", "Branding"] },
      { n: "03", title: "Social media campaign", text: "Plan and design a 9-post Instagram grid and festive offer creatives in one brand style.", tags: ["Photoshop", "Canva"] },
      { n: "04", title: "Catalogue & packaging", text: "Lay out a multi-page product catalogue and design a box and label with dielines.", tags: ["InDesign", "Packaging"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "Brief. Design. Review.",
    text: "Every topic is taught the way design work happens in a studio, so you learn to work with feedback, not just with software.",
    steps: [
      { title: "Brief", text: "The trainer explains the task and demonstrates the key technique on the big screen.", example: "A café needs a menu flyer" },
      { title: "Design", text: "You create your own version on your computer while the trainer checks your progress.", example: "Layout, fonts and photos" },
      { title: "Review", text: "Your design is reviewed like a client would review it, and you revise it until it is ready.", example: "Fixing spacing and colours" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name}`,
    text: `Plenty of places in ${site.city} teach a design program or two. What differs is whether you learn the full range employers ask for, get honest feedback on your work, and leave with a portfolio instead of just notes.`,
    items: [
      { title: "Trainers who review your work", text: "Every design gets specific feedback on layout, colour and type — not just a tick." },
      { title: "Small batches", text: "Small enough that the trainer sees and corrects your work every class." },
      { title: "Flexible timings", text: "Morning, evening, weekend and 1-on-1 batches around college or work." },
      { title: "Print knowledge included", text: "Bleed, CMYK and file preparation so your designs print correctly." },
      { title: "Placement support", text: "Portfolio reviews, mock interviews and job updates with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any graphic design program, including this one.",
    rows: [
      { feature: "Tools covered", us: "Photoshop, Illustrator, CorelDRAW, InDesign, Canva", them: "Often one or two programs" },
      { feature: "Track options", us: "3, 6 or 9 months, each building on the last", them: "One fixed length" },
      { feature: "Design basics", us: "Colour, typography and layout taught first", them: "Straight into tool buttons" },
      { feature: "Projects", us: "Client-style briefs with feedback", them: "Copying tutorials" },
      { feature: "Print readiness", us: "Bleed, CMYK and real sizes covered", them: "Rarely covered" },
      { feature: "Batch size", us: "Small batches with individual attention", them: "Large, crowded batches" },
      { feature: "Internship letter", us: "On 6 and 9 month tracks", them: "Not usually offered" },
      { feature: "After the program", us: "Placement support + portfolio review", them: "Certificate only" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Simranjeet Kaur", role: "Graphic Designer · Jalandhar", text: "I did the 6 month track. The branding and brochure work in my portfolio got more questions at the interview than my certificate." },
    { name: "Karan Sharma", role: "BA Student · Model Town", text: "Started with 3 months to see if I liked it, then extended. Nothing was repeated, it just carried on." },
    { name: "Manpreet Singh", role: "DTP Operator · Rama Mandi", text: "I used to print other people's files at a flex shop. Now I make the designs myself in CorelDRAW." },
    { name: "Ritika Arora", role: "Freelancer · Urban Estate", text: "The trainer told me honestly when a design was not working. My logos got much better because of that." },
    { name: "Amandeep Singh", role: "In-house Designer · Basti Sheikh", text: "The packaging and catalogue months were useful for my job at a sports goods unit. Small batch, so I got proper attention." },
    { name: "Gurleen Kaur", role: "Homemaker · Kapurthala", text: "Weekend batch suited me. I now make invitations and festival posts for people I know." },
  ],
  faqs: [
    { q: "What is the difference between the 3, 6 and 9 month tracks?", a: "The 3-month track covers design basics and the core tools. The 6-month track adds brand identity, print production and social media creatives. The 9-month track adds InDesign publications, packaging, live client-style work and a full portfolio." },
    { q: "Do I need drawing skills or a design background?", a: "No. The program starts with design basics and each tool from its first screen. Basic computer use is enough to begin." },
    { q: "Can I start with 3 months and extend later?", a: "Yes. The tracks build on each other, so you can continue to 6 or 9 months without repeating what you have already learned." },
    { q: "Will I get a certificate and internship letter?", a: `Every track gets a ${site.name} certificate that can be verified online. The 6 and 9 month tracks also include an internship letter.` },
    { q: "What are the batch timings?", a: "Morning, afternoon, evening and weekend batches are available, plus 1-on-1 slots on request." },
    { q: "Do I need my own laptop?", a: "No. Every student gets a lab computer with the software installed. A laptop helps for practice at home but is not required." },
    { q: "Do you help with jobs?", a: "Yes. We help you finish your portfolio, prepare for interviews and share openings from our 500+ hiring partners. We do not promise a job, but we support you through the search." },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, see the lab and some student work, and meet the trainer before you decide." },
  ],
  program: {
    category: "graphic-design",
    feeSource: "graphic-design-course-in-jalandhar",
    tracksTitle: "Choose your Graphic Design track",
    tracksText: "Each track builds on the one before it, so you can start short and extend later without repeating anything.",
    tracks: [
      {
        kind: "Program",
        duration: "3 Months",
        text: "Design principles, colour and typography with the core tools — Photoshop, Illustrator, CorelDRAW and Canva — for posters, logos, cards and flex.",
      },
      {
        kind: "Certificate Program",
        duration: "6 Months",
        text: "Everything in 3 months, plus brand identity, print production and social media campaigns, with an internship letter.",
      },
      {
        kind: "Diploma Program",
        duration: "9 Months",
        text: "Everything in 6 months, plus InDesign publications, packaging design, live client-style work and a finished portfolio for interviews.",
      },
    ],
    fit: {
      title: "Not sure if Graphic Design is the right fit?",
      text: "Talk to a counsellor or book a free demo class to see the lab, some student work and how a design class runs before you decide.",
    },
  },
};
