// Course pages for the accounting courses (Tally, BUSY, diploma, GST). See ./types.ts for what each field is.
import { site } from "../site";
import type { CourseDetail } from "./types";

const tallyPrimeGst: CourseDetail = {
  slug: "tally-prime-gst",
  seo: {
    title: `Tally Prime with GST Course in ${site.city} | 3-Month Practical Program`,
    description: `Learn Tally Prime at ${site.name} ${site.city}: vouchers, inventory, GST invoicing and returns, TDS, payroll, bank reconciliation and final accounts on real company data, with a certificate and placement support.`,
  },
  hero: {
    crumb: "Tally Prime",
    tag: "Tally Prime",
    badge: "GST Ready",
    title: `Best Tally Prime with GST Course in ${site.city}`,
    text: `Learn to keep a real business's books in Tally Prime — from the golden rules of accounting to GST invoices, GSTR-1 and GSTR-3B data, TDS, payroll and the balance sheet — practised on sample company data in the ${site.name} ${site.city} lab.`,
    points: ["Real company case studies", "GST return practice", "Payroll & TDS", "Placement support"],
    facts: [
      { label: "Duration", value: "3 Months" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "10+2, any stream" },
      { label: "Includes", value: "Certificate + practice company data" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "12", label: "Weeks", note: "of hands-on Tally practice" },
    ],
    hub: {
      center: "tally.png",
      nodes: [
        { logo: "excel.png" },
        { logo: "tally.png" },
        { logo: "word.png" },
        { logo: "google-workspace.svg" },
        { logo: "outlook.svg" },
        { logo: "windows.svg" },
        { icon: "₹" },
        { icon: "🧾" },
      ],
    },
  },
  overview: {
    eyebrow: "Course overview",
    title: "Keep the complete books of a business in Tally Prime",
    paragraphs: [
      `${site.name}'s Tally Prime with GST course in ${site.city} is for anyone who wants to do the accounts work that almost every shop, trader, factory and CA office in Punjab runs on Tally — whether you are a commerce student, a job seeker or a business owner tired of depending on an outside accountant.`,
      "You start with the accounting logic itself — debit and credit, the golden rules, groups and ledgers — so Tally makes sense rather than being a list of shortcuts. Then you create a company, pass sales, purchase, payment, receipt, contra and journal vouchers, maintain stock with godowns and units, and switch on GST to raise tax invoices and prepare the data behind GSTR-1 and GSTR-3B. The last month covers TDS, payroll, bank reconciliation and the final accounts.",
      "Every module is practised on a sample company with a month of real-looking transactions, so by the end you have maintained a full set of books from opening balances to the Profit & Loss account and Balance Sheet — the same work an accounts executive does on the job.",
    ],
    image: "tally-gst.webp",
    imageAlt: "Student entering vouchers in Tally Prime at the techcadd lab",
    imageTag: "Real company data",
    getList: [
      "One computer per student with Tally Prime installed",
      "Sample company data sets for every module",
      "GST invoice and return-data practice",
      "Printed notes with voucher and shortcut guides",
      "Certificate + your completed company books",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "8", label: "Modules" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who should do this course",
    text: "You need basic computer use and simple arithmetic. Commerce helps but is not required — the course teaches accounting from the ground up before it touches the software.",
    items: [
      { icon: "student", title: "Commerce students (12th / B.Com)", text: "Turn your book-keeping theory into the practical Tally skill employers actually test in interviews." },
      { icon: "grad", title: "Graduates of any stream", text: "B.A., B.Sc. or BCA — Tally with GST is one of the quickest routes into a steady office job." },
      { icon: "job", title: "Job seekers", text: "Accountant and accounts executive vacancies in Punjab almost always ask for Tally and GST knowledge." },
      { icon: "shop", title: "Shop & business owners", text: "Keep your own books, raise GST invoices and understand what your CA is filing for you." },
      { icon: "office", title: "Working office staff", text: "Move from billing or data entry into proper accounts work and a better-paid role." },
      { icon: "chart", title: "CA / CMA aspirants", text: "Get practical software experience alongside your exams before articleship or a first job." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why three months of Tally are worth it",
    feature: {
      tag: "Access",
      title: "Batches around your college or job",
      text: `Students come to the ${site.city} centre from Model Town, Urban Estate, Adarsh Nagar, Lajpat Nagar and Rama Mandi, with weekend learners from Phagwara, Kapurthala, Nakodar and Kartarpur. Morning, evening, weekend and 1-on-1 slots let you learn Tally without dropping college or leaving your current job.`,
      slots: ["Morning", "Afternoon", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Demand",
        title: "Tally runs local business",
        text: "Traders, wholesalers, factories, hospitals and CA offices across Punjab keep their books in Tally. Knowing it well opens doors in almost every town.",
      },
      {
        tag: "Method",
        title: "Accounting first, keys second",
        text: "You learn why an entry is a debit or credit before you learn where to press. That is what lets you handle entries nobody showed you in class.",
      },
      {
        tag: "Compliance",
        title: "GST is part of every job",
        text: "Every invoice carries GST. You learn tax ledgers, HSN/SAC, CGST/SGST vs IGST and how the return data comes out of Tally.",
      },
      {
        tag: "Next step",
        title: "A base for bigger roles",
        text: "With Tally done, GST & Taxation, Advanced Excel or the Computerised Accounting diploma build straight on top of it.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Every GST-registered business needs someone who knows Tally.",
    points: [
      "GST returns are monthly or quarterly for every registered business, so clean day-to-day entries are no longer optional — they are the return.",
      "Fresher accountant and accounts executive roles in Punjab typically start around ₹12,000 – ₹20,000 a month, rising with GST and TDS experience.",
      "Three months of daily practice is enough to handle a small business's books independently.",
    ],
    panel: [
      { k: "Voucher entry", v: "Every working day" },
      { k: "GSTR-1 / GSTR-3B", v: "Monthly or quarterly" },
      { k: "TDS & payroll", v: "Every month" },
      { k: "Final accounts", v: "Every financial year" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, week by week",
    text: "The course follows the order an accountant works in: principles, company set-up, daily vouchers, stock, GST, then month-end and year-end work.",
    phases: [
      {
        id: "01",
        name: "Accounting Fundamentals",
        weeks: "Weeks 1–2",
        summary: "Understand the logic behind every entry before touching the software.",
        topics: [
          "Types of accounts and the golden rules of accounting",
          "Journal, ledger and trial balance by hand",
          "Capital vs revenue, assets, liabilities, income and expenses",
          "Source documents — invoices, bills, receipts and vouchers",
        ],
        outcome: "Pass correct journal entries for common business transactions",
      },
      {
        id: "02",
        name: "Company Creation & Ledgers",
        weeks: "Week 3",
        summary: "Set up a company in Tally Prime the way a real business needs it.",
        topics: [
          "Gateway of Tally, company creation and features (F11)",
          "Groups, ledgers and opening balances",
          "Financial year, security and data backup/restore",
          "Chart of accounts for a trading business",
        ],
        outcome: "A fully set-up sample company with correct ledgers",
      },
      {
        id: "03",
        name: "Voucher Entry",
        weeks: "Weeks 4–5",
        summary: "Record a business's daily transactions quickly and accurately.",
        topics: [
          "Sales (F8), purchase (F9), payment (F5) and receipt (F6) vouchers",
          "Contra (F4) and journal (F7) entries",
          "Credit notes, debit notes and bill-wise details",
          "Cost centres and day book checking",
        ],
        outcome: "A month of transactions entered and balanced",
      },
      {
        id: "04",
        name: "Inventory Management",
        weeks: "Week 6",
        summary: "Track stock alongside the accounts.",
        topics: [
          "Stock groups, categories, units and stock items",
          "Godowns and stock transfers",
          "Purchase and sales orders, delivery and receipt notes",
          "Stock summary, reorder levels and valuation",
        ],
        outcome: "Stock records that tie up with the purchase and sales books",
      },
      {
        id: "05",
        name: "GST Setup, Invoicing & Returns",
        weeks: "Weeks 7–8",
        summary: "Make every invoice GST-correct and pull clean return data.",
        topics: [
          "Enabling GST, GSTIN, HSN/SAC and tax rates",
          "CGST + SGST vs IGST, tax ledgers and RCM entries",
          "GST tax invoices, credit/debit notes and e-way bill details",
          "GSTR-1 and GSTR-3B reports, JSON export and GSTR-2B matching",
        ],
        outcome: "GST-ready invoices and return summaries for a sample month",
      },
      {
        id: "06",
        name: "TDS & Payroll",
        weeks: "Weeks 9–10",
        summary: "Handle tax deductions and staff salaries in Tally.",
        topics: [
          "TDS nature of payments — contractors, professionals, rent",
          "TDS deduction, payment and outstanding reports",
          "Payroll masters — employees, pay heads, attendance",
          "Salary processing with PF and ESI, payslips",
        ],
        outcome: "A month of salaries and TDS entries processed",
      },
      {
        id: "07",
        name: "Bank Reconciliation",
        weeks: "Week 11",
        summary: "Match the books to the bank statement.",
        topics: [
          "Cheque, NEFT/UPI and bank charges entries",
          "Bank reconciliation statement in Tally Prime",
          "Handling uncleared cheques and differences",
          "Cheque printing and deposit slips",
        ],
        outcome: "A reconciled bank account for the sample company",
      },
      {
        id: "08",
        name: "Final Accounts & MIS Reports",
        weeks: "Week 12",
        summary: "Close the year and read what the numbers say.",
        topics: [
          "Adjustment entries — depreciation, outstanding and prepaid",
          "Trial balance, Profit & Loss account and Balance Sheet",
          "Ratio analysis, cash flow and funds flow reports",
          "Exporting reports to Excel and PDF",
        ],
        outcome: "Final accounts for the company you maintained all course",
      },
    ],
  },
  tools: {
    eyebrow: "Software you will use",
    title: "The tools an accounts desk actually uses",
    text: "Each of these is used in class — Tally Prime on your own lab computer every day, and the GST portal walked through step by step.",
    tools: [
      { name: "Tally Prime", logo: "tally.png", use: "Accounts, inventory, GST" },
      { name: "MS Excel", logo: "excel.png", use: "Reports & reconciliations" },
      { name: "GST Portal", mono: "GST", use: "Returns & GSTR-2B" },
      { name: "E-way Bill Portal", mono: "EWB", use: "Goods movement" },
      { name: "MS Word", logo: "word.png", use: "Letters & documentation" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Get certified in Tally Prime with GST",
    text: "Complete the course and the final company project to receive a techcadd certificate you can attach to any job application — verifiable online.",
    courseName: "Tally Prime with GST",
    items: [
      { title: "Course certificate", text: "Verifiable online by any employer" },
      { title: "Company project", text: "A full year of books you maintained" },
      { title: "GST practice record", text: "Invoices and return summaries you prepared" },
      { title: "Placement support", text: "Resume help and job-drive updates" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where Tally with GST takes you",
    text: "Indicative starting pay for freshers in Punjab. Actual offers depend on the employer, your accounting basics and how you do in the practical test most firms give.",
    roles: [
      { title: "Accountant", pay: "₹12k – 20k", text: "Traders, small manufacturers and hospitals" },
      { title: "Accounts Executive", pay: "₹12k – 18k", text: "Company accounts teams and CA offices" },
      { title: "GST Assistant", pay: "₹10k – 16k", text: "Invoice checks and return data in tax offices" },
      { title: "Billing Executive", pay: "₹10k – 15k", text: "Wholesale, distribution and showrooms" },
    ],
    hiring: ["CA & tax consultant offices", "Traders & wholesalers", "Manufacturing units", "Hospitals & schools", "Showrooms & distributors", "Export houses"],
    qa: [
      {
        q: "What jobs can I get after Tally Prime with GST?",
        a: "Accountant, accounts executive, GST assistant and billing executive roles in local businesses and CA offices. Most employers give a short Tally practical test at the interview.",
      },
      {
        q: "Can I manage my own business accounts?",
        a: "Yes. Many shop and business owners join to keep their own books, raise GST invoices and check what their CA is filing.",
      },
      {
        q: "Is Tally still relevant with so much online software?",
        a: "Yes. Tally Prime remains one of the most widely used accounting packages among small and medium businesses in India, including across Punjab.",
      },
      {
        q: "What should I learn after this?",
        a: "GST & Taxation for deeper return filing and ITR work, Advanced Excel for reporting, or the 6-month Diploma in Computerised Accounting for a complete career track.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real tasks you will complete",
    text: "Every module adds to one sample company, so by the last week you have kept its books from start to finish.",
    items: [
      { n: "01", title: "Trading company set-up", text: "Create a company, its ledgers, stock items and opening balances from a given trial balance.", tags: ["Tally Prime", "Masters"] },
      { n: "02", title: "One month of transactions", text: "Enter sales, purchases, payments, receipts and expenses from a bundle of sample bills.", tags: ["Vouchers", "Inventory"] },
      { n: "03", title: "GST month-end", text: "Raise GST invoices, match purchases with GSTR-2B and prepare GSTR-1 and GSTR-3B summaries.", tags: ["GST", "Returns"] },
      { n: "04", title: "Year-end close", text: "Process salaries and TDS, reconcile the bank and produce the P&L and Balance Sheet.", tags: ["Payroll", "Final accounts"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "Understand it. Enter it. Check it.",
    text: "Every topic follows the same three steps, so you learn accounting — not just keystrokes.",
    steps: [
      { title: "Understand it", text: "The trainer explains the transaction and its debit/credit on the board.", example: "Goods sold on credit" },
      { title: "Enter it", text: "You pass the entry in Tally Prime on your own computer.", example: "Sales voucher with GST" },
      { title: "Check it", text: "You verify the effect in the ledger, GST report and trial balance.", example: "Party balance and GSTR-1" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name} for Tally`,
    text: `Plenty of places in ${site.city} teach Tally. The difference is whether you learn accounting or only menus, how much time you spend on real entries, and whether GST is taught properly.`,
    items: [
      { title: "Trainers with accounts experience", text: "Taught by people who understand how books are kept in real businesses." },
      { title: "Accounting before software", text: "Golden rules and journal entries first, so every Tally screen makes sense." },
      { title: "Small batches", text: "The trainer checks your entries and your trial balance, not just the class's." },
      { title: "Real-looking company data", text: "Practise on bills and statements like the ones you will see at work." },
      { title: "Placement support", text: "Resume help, mock Tally tests and job drives with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any Tally course, including this one.",
    rows: [
      { feature: "Accounting basics", us: "Golden rules and journal taught first", them: "Straight into Tally menus" },
      { feature: "Practice data", us: "Full sample company with real-looking bills", them: "A few isolated entries" },
      { feature: "GST coverage", us: "Invoices, RCM, GSTR-1, GSTR-3B, GSTR-2B", them: "Often only GST invoice entry" },
      { feature: "TDS & payroll", us: "Included with practice", them: "Frequently skipped" },
      { feature: "Batch size", us: "Small batches with individual checking", them: "Large, crowded batches" },
      { feature: "Timings", us: "Morning, evening, weekend, 1-on-1", them: "Fixed single slot" },
      { feature: "Certificate", us: "Verifiable certificate + company project", them: "Varies" },
      { feature: "After the course", us: "Placement support and job drives", them: "Limited or none" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Harpreet Kaur", role: "B.Com Student · Model Town", text: "College taught me theory; here I actually kept a company's books in Tally. The GST part was explained very clearly." },
    { name: "Rohit Bansal", role: "Accounts Executive · Jalandhar", text: "Joined after graduation with no accounts background. Got placed in a trading firm soon after finishing." },
    { name: "Jaswinder Singh", role: "Hardware Store Owner · Basti Sheikh", text: "I now make my own GST bills and check the returns data before sending it to my CA. Very practical course." },
    { name: "Priya Malhotra", role: "Billing Executive · Urban Estate", text: "Evening batch fitted around my job. The trainer checked every entry and trial balance I made." },
    { name: "Kulwinder Singh", role: "Accountant · Kapurthala", text: "The TDS and payroll modules were what my employer asked about in the interview. Glad they were covered." },
    { name: "Ritika Sharma", role: "12th Commerce · Phagwara", text: "Weekend classes, small group and lots of practice. The notes with shortcuts helped me revise at home." },
  ],
  faqs: [
    { q: "Do I need a commerce background to learn Tally?", a: "No. The course starts with accounting basics — debit, credit and the golden rules — before moving into Tally Prime. Basic computer use is enough." },
    { q: "What is the duration and class timing?", a: "The course runs for 3 months. Morning, afternoon, evening and weekend batches are available, plus 1-on-1 slots on request." },
    { q: "Is GST return filing covered?", a: "Yes. You set up GST in Tally Prime, raise GST invoices, match purchases with GSTR-2B and prepare GSTR-1 and GSTR-3B data, with a walkthrough of how returns are filed on the GST portal." },
    { q: "Are TDS and payroll included?", a: "Yes. TDS on contractors, professionals and rent, plus payroll with pay heads, attendance, PF and ESI are covered with practice entries." },
    { q: "Will I get a certificate?", a: "Yes. You receive a techcadd certificate on completing the course and the final company project, which can be verified online." },
    { q: "Is this the official Tally certification?", a: "The certificate is issued by techcadd for completing our course. It is separate from any certification offered by Tally Solutions." },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, see the lab and meet the trainer before you decide." },
  ],
};

const busyAccounting: CourseDetail = {
  slug: "busy-accounting",
  seo: {
    title: `BUSY Accounting Software Course in ${site.city} | 2-Month Program`,
    description: `Learn BUSY accounting software at ${site.name} ${site.city}: masters, GST billing, batches, godowns, outstanding and reports — practised on trading and distribution data, with a certificate and placement support.`,
  },
  hero: {
    crumb: "BUSY Accounting",
    tag: "BUSY Software",
    badge: "GST Billing",
    title: `BUSY Accounting Software Course in ${site.city}`,
    text: `Learn the billing, stock and GST accounting software used by many traders, distributors and manufacturers — from setting up masters to batch-wise stock, party outstanding and GST reports — practised hands-on in the ${site.name} ${site.city} lab.`,
    points: ["Trading & distribution workflows", "GST billing", "Stock & batch management", "Placement support"],
    facts: [
      { label: "Duration", value: "2 Months" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "10th / 12th + basic computer" },
      { label: "Includes", value: "Certificate + practice company data" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "8", label: "Weeks", note: "of billing & stock practice" },
    ],
    hub: {
      center: "excel.png",
      nodes: [
        { logo: "windows.svg" },
        { logo: "word.png" },
        { logo: "excel.png" },
        { logo: "outlook.svg" },
        { logo: "google-workspace.svg" },
        { logo: "windows.svg" },
        { icon: "₹" },
        { icon: "📦" },
      ],
    },
  },
  overview: {
    eyebrow: "Course overview",
    title: "Billing, stock and GST accounts the way distributors run them",
    paragraphs: [
      `${site.name}'s BUSY course in ${site.city} is built around the work done at the billing and accounts counter of a trader, wholesaler, distributor or small manufacturer — the businesses where BUSY is most commonly installed.`,
      "You begin by creating a company and its masters — account groups, parties, item groups, units and GST rates. Then comes the daily work: sales and purchase invoices with bill sundries for discount and freight, returns, and payment and receipt entries. Inventory goes further than a basic course, with batch numbers, expiry dates, MRP-wise stock and multiple material centres (godowns). The final weeks cover GST invoicing and reports, bill-by-bill party outstanding and the reports and backups an owner asks for.",
      "Each module is practised on a sample distribution business, so you finish having billed, stocked and reconciled a realistic month of trade — exactly what a billing executive or store accountant is hired to do.",
    ],
    image: "tally-gst.webp",
    imageAlt: "Student preparing GST invoices on accounting software at the techcadd lab",
    imageTag: "Built for trading businesses",
    getList: [
      "One computer per student with BUSY installed",
      "Sample trading and distribution data",
      "Batch, expiry and godown-wise stock practice",
      "Printed step-by-step notes for every screen",
      "Certificate + your completed practice company",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "6", label: "Modules" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who should do this course",
    text: "If you can use a computer and do simple calculations, you can learn BUSY. Accounting terms are explained as they come up, with a trading business as the example throughout.",
    items: [
      { icon: "student", title: "12th / B.Com students", text: "Add a second accounting package to your resume — many local firms use BUSY rather than Tally." },
      { icon: "job", title: "Job seekers", text: "Billing and store-accounts jobs at distributors and wholesalers often ask specifically for BUSY." },
      { icon: "shop", title: "Traders & distributors", text: "Run billing, stock and party balances for your own business without outside help." },
      { icon: "office", title: "Billing & counter staff", text: "Already making bills? Learn the stock, GST and outstanding side and move up to accounts." },
      { icon: "chart", title: "Tally users", text: "Know Tally already? Pick up BUSY quickly so you can take jobs using either package." },
      { icon: "home", title: "Family business members", text: "Help run the family shop or agency's accounts on the software it already has." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why two months of BUSY are worth it",
    feature: {
      tag: "Access",
      title: "Timings that suit working people",
      text: `Learners reach the ${site.city} centre from Rama Mandi, Maqsudan, Adarsh Nagar, Garha and Basti Bawa Khel, with weekend students from Phagwara, Kapurthala, Goraya and Adampur. Morning, evening, weekend and 1-on-1 slots mean shop and counter staff can learn without taking time off.`,
      slots: ["Morning", "Afternoon", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Demand",
        title: "Where trade happens, BUSY is common",
        text: "Pharma, FMCG, hardware and electrical distributors frequently choose BUSY for its billing and batch-wise stock. Those desks need trained operators.",
      },
      {
        tag: "Method",
        title: "A real billing counter, simulated",
        text: "You work through a stack of orders, purchase bills and returns just as a distributor's counter would — not isolated examples.",
      },
      {
        tag: "Stock",
        title: "Batches, expiry and godowns",
        text: "The stock features that matter most in trading — batch numbers, expiry dates, MRP and material centres — are practised properly.",
      },
      {
        tag: "Next step",
        title: "Pairs well with Tally",
        text: "Knowing both BUSY and Tally Prime makes you employable at almost any local business. The Computerised Accounting diploma covers both.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Every sale is a GST invoice. Someone has to get it right.",
    points: [
      "GST-registered traders must issue correct tax invoices and file returns on time, so billing staff who understand GST are in steady demand.",
      "Fresher billing executive and store accountant roles in Punjab typically start around ₹10,000 – ₹16,000 a month.",
      "Two months of daily practice is enough to run a trading business's billing and stock on BUSY.",
    ],
    panel: [
      { k: "GST invoices", v: "Every sale" },
      { k: "Batch & expiry", v: "Pharma, FMCG" },
      { k: "Party outstanding", v: "Every week" },
      { k: "GST reports", v: "Every return period" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, week by week",
    text: "The course follows the working day of a trading business: set up once, bill every day, manage stock, then GST, collections and reports.",
    phases: [
      {
        id: "01",
        name: "BUSY Setup & Masters",
        weeks: "Week 1",
        summary: "Create a company and every master it needs.",
        topics: [
          "Company creation, financial year and configuration",
          "Account groups and party masters with GSTIN",
          "Item groups, units, items and HSN codes",
          "Tax categories and bill sundries (discount, freight)",
        ],
        outcome: "A configured trading company ready for billing",
      },
      {
        id: "02",
        name: "Sales, Purchase & Billing",
        weeks: "Weeks 2–3",
        summary: "Handle the daily billing counter with speed and accuracy.",
        topics: [
          "Sales and purchase invoices with discounts and freight",
          "Sales and purchase returns, credit and debit notes",
          "Payment, receipt, contra and journal vouchers",
          "Orders, challans and invoice printing formats",
        ],
        outcome: "Two weeks of sales and purchase billing completed",
      },
      {
        id: "03",
        name: "Inventory, Batches & Godowns",
        weeks: "Week 4",
        summary: "Keep stock exactly right across batches and locations.",
        topics: [
          "Batch-wise and expiry-wise stock",
          "MRP-wise and serial-number tracking",
          "Material centres (godowns) and stock transfers",
          "Stock status, reorder levels and valuation",
        ],
        outcome: "Batch and godown-wise stock that matches the bills",
      },
      {
        id: "04",
        name: "GST Invoicing & Reports",
        weeks: "Weeks 5–6",
        summary: "Make every transaction GST-correct and pull return data.",
        topics: [
          "Intra-state (CGST + SGST) vs inter-state (IGST) billing",
          "Reverse charge, exempt and nil-rated supplies",
          "E-way bill details and e-invoice fields on invoices",
          "GSTR-1 and GSTR-3B reports and data export",
        ],
        outcome: "GST return summaries for the sample business",
      },
      {
        id: "05",
        name: "Outstanding & Ledger Management",
        weeks: "Week 7",
        summary: "Know exactly who owes what, and since when.",
        topics: [
          "Bill-by-bill references and adjustments",
          "Receivable and payable ageing reports",
          "Party ledgers, statements and reminders",
          "Credit limits and interest on late payment",
        ],
        outcome: "An ageing report and party statements ready to send",
      },
      {
        id: "06",
        name: "Reports & Data Backup",
        weeks: "Week 8",
        summary: "Give the owner the reports they need and keep data safe.",
        topics: [
          "Day book, cash/bank book and trial balance",
          "Sales and purchase analysis, item-wise profit",
          "Profit & Loss and Balance Sheet",
          "Data backup, restore and year-end carry forward",
        ],
        outcome: "A month-end report pack and a tested backup",
      },
    ],
  },
  tools: {
    eyebrow: "Software you will use",
    title: "What a trading accounts desk works with",
    text: "BUSY is used on your own lab computer every class, with Excel for the reports owners like to receive.",
    tools: [
      { name: "BUSY", mono: "BUSY", use: "Billing, stock & accounts" },
      { name: "MS Excel", logo: "excel.png", use: "Report exports & analysis" },
      { name: "GST Portal", mono: "GST", use: "Understanding return data" },
      { name: "E-way Bill Portal", mono: "EWB", use: "Goods movement" },
      { name: "Windows", logo: "windows.svg", use: "Files, printing & backups" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Get certified in BUSY Accounting",
    text: "Complete the course and the practice company to receive a techcadd certificate you can attach to any job application — verifiable online.",
    courseName: "BUSY Accounting Software",
    items: [
      { title: "Course certificate", text: "Verifiable online by any employer" },
      { title: "Practice company", text: "A month of billing and stock you handled" },
      { title: "GST report pack", text: "Return summaries you prepared" },
      { title: "Placement support", text: "Resume help and job-drive updates" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where BUSY takes you",
    text: "Indicative starting pay for freshers in Punjab. Actual offers depend on the employer, your billing speed and your grasp of GST.",
    roles: [
      { title: "Billing Executive", pay: "₹10k – 15k", text: "Distributors, wholesalers and showrooms" },
      { title: "Accounts Assistant", pay: "₹10k – 16k", text: "Day-to-day entries and party ledgers" },
      { title: "Store Accountant", pay: "₹10k – 16k", text: "Stock, godowns and purchase records" },
      { title: "Inventory / Stock Clerk", pay: "₹9k – 14k", text: "Batch, expiry and stock reconciliation" },
    ],
    hiring: ["Pharma distributors", "FMCG & grocery wholesalers", "Hardware & electrical traders", "Manufacturing units", "Auto parts dealers", "Retail chains"],
    qa: [
      {
        q: "What jobs can I get after learning BUSY?",
        a: "Billing executive, accounts assistant and store accountant roles, mainly at distributors, wholesalers and small manufacturers who use BUSY.",
      },
      {
        q: "Should I learn BUSY or Tally?",
        a: "Both are used locally. Tally is more common overall; BUSY is popular with traders and distributors. Many students learn one and then the other — the accounting logic is the same.",
      },
      {
        q: "Is it useful for my own shop?",
        a: "Yes. Owners learn to bill, track stock and batches, and see who owes them money without waiting for an accountant.",
      },
      {
        q: "What should I learn after this?",
        a: "Tally Prime with GST, GST & Taxation for return filing, or the 6-month Diploma in Computerised Accounting that covers both packages.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real tasks you will complete",
    text: "All four tasks use one sample distribution business, so the work builds into a complete month of trade.",
    items: [
      { n: "01", title: "Distributor set-up", text: "Create the company, parties, items with HSN, units, tax categories and bill sundries.", tags: ["BUSY", "Masters"] },
      { n: "02", title: "Billing counter week", text: "Bill a stack of sample orders and purchases, including returns, discounts and freight.", tags: ["Invoicing", "GST"] },
      { n: "03", title: "Batch & godown stock", text: "Track pharma-style stock by batch and expiry across two godowns and reconcile it.", tags: ["Inventory", "Batches"] },
      { n: "04", title: "Month-end pack", text: "Produce GST summaries, an outstanding ageing report, P&L and a verified backup.", tags: ["Reports", "Backup"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "See it. Bill it. Check it.",
    text: "Every topic follows the same three steps, so each feature is tied to a real transaction.",
    steps: [
      { title: "See it", text: "The trainer walks through one transaction from paper bill to screen.", example: "Purchase from a supplier" },
      { title: "Bill it", text: "You enter it yourself in BUSY while the trainer checks your screen.", example: "Batch-wise purchase invoice" },
      { title: "Check it", text: "You confirm the effect on stock, party balance and GST reports.", example: "Stock status and GSTR-3B" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name} for BUSY`,
    text: `Fewer institutes in ${site.city} teach BUSY in depth. What matters is whether the stock features and GST are covered properly, and how much time you actually spend billing.`,
    items: [
      { title: "Trading-focused training", text: "Examples come from distributors, wholesalers and shops — where BUSY is used." },
      { title: "One student, one computer", text: "You bill every transaction yourself; nobody else drives your screen." },
      { title: "Small batches", text: "The trainer checks your stock and party balances, not just the final answer." },
      { title: "Stock features in depth", text: "Batches, expiry, MRP and godowns practised, not just mentioned." },
      { title: "Placement support", text: "Resume help, mock tests and job drives with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any BUSY course, including this one.",
    rows: [
      { feature: "Practice data", us: "Full sample distribution business", them: "A handful of demo entries" },
      { feature: "Inventory", us: "Batches, expiry, MRP and godowns", them: "Basic stock items only" },
      { feature: "GST", us: "CGST/SGST, IGST, RCM and return reports", them: "Tax invoice entry only" },
      { feature: "Outstanding", us: "Bill-by-bill and ageing reports", them: "Often skipped" },
      { feature: "Batch size", us: "Small batches with individual checking", them: "Large, crowded batches" },
      { feature: "Timings", us: "Morning, evening, weekend, 1-on-1", them: "Fixed single slot" },
      { feature: "Certificate", us: "Verifiable certificate + practice company", them: "Varies" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Gagandeep Singh", role: "Billing Executive · Maqsudan", text: "My new job used BUSY, not Tally. Two months here and I was handling the billing counter on my own." },
    { name: "Mandeep Kaur", role: "B.Com Student · Garha", text: "The batch and expiry stock practice was very useful. Now I know both Tally and BUSY for interviews." },
    { name: "Sanjay Gupta", role: "Hardware Trader · Rama Mandi", text: "I wanted to check my own stock and party balances. The outstanding reports alone were worth it." },
    { name: "Amandeep Kaur", role: "Store Accountant · Goraya", text: "Weekend batch suited me. The trainer explained godown transfers until I got them right." },
    { name: "Vikas Kumar", role: "Accounts Assistant · Phagwara", text: "Practical from the first day. We billed real-looking orders every class, not just theory." },
    { name: "Navneet Kaur", role: "Family Business · Kapurthala", text: "I now run the billing and GST reports for our family agency myself. Simple notes, patient teaching." },
  ],
  faqs: [
    { q: "Do I need to know Tally before learning BUSY?", a: "No. BUSY is taught from the start, including the accounting terms you need. If you already know Tally, you will pick it up faster." },
    { q: "What is the duration and class timing?", a: "The course runs for 2 months. Morning, afternoon, evening and weekend batches are available, plus 1-on-1 slots on request." },
    { q: "Is GST covered?", a: "Yes. GST billing for intra-state and inter-state sales, reverse charge, credit and debit notes, e-way bill details and GSTR-1 / GSTR-3B reports are all part of the course." },
    { q: "Is batch and expiry tracking included?", a: "Yes. Batch-wise, expiry-wise and MRP-wise stock, along with multiple godowns (material centres), are practised in detail." },
    { q: "Will I get a certificate?", a: "Yes. You receive a techcadd certificate on completing the course and practice company, which can be verified online. It is separate from any certification offered by the software vendor." },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, see the lab and meet the trainer before you decide." },
    { q: "What should I learn after BUSY?", a: "Tally Prime with GST, GST & Taxation, or the 6-month Diploma in Computerised Accounting." },
  ],
};

const computerisedAccountingDiploma: CourseDetail = {
  slug: "computerised-accounting-diploma",
  seo: {
    title: `Diploma in Computerised Accounting in ${site.city} | 6-Month Career Program`,
    description: `A 6-month accounting career track at ${site.name} ${site.city}: Tally Prime, BUSY, GST returns, income tax and TDS basics, Advanced Excel and a live accounting project, with a diploma, internship letter and placement support.`,
  },
  hero: {
    crumb: "Accounting Diploma",
    tag: "Diploma",
    badge: "Internship Letter",
    title: `Diploma in Computerised Accounting in ${site.city}`,
    text: `A complete six-month route into accounts work: accounting principles, Tally Prime and BUSY, GST returns, income tax and TDS basics and Advanced Excel — finished with a live accounting project at the ${site.name} ${site.city} centre.`,
    points: ["Tally + BUSY + Excel", "GST & TDS practice", "Internship letter", "Placement support"],
    facts: [
      { label: "Duration", value: "6 Months" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "10+2, any stream" },
      { label: "Includes", value: "Diploma + internship letter" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "500+", label: "Hiring partners", note: "for placement support" },
    ],
    hub: {
      center: "tally.png",
      nodes: [
        { logo: "excel.png" },
        { logo: "word.png" },
        { logo: "tally.png" },
        { logo: "google-workspace.svg" },
        { logo: "outlook.svg" },
        { logo: "windows.svg" },
        { icon: "₹" },
        { icon: "📊" },
      ],
    },
  },
  overview: {
    eyebrow: "Course overview",
    title: "A complete accounting career track in six months",
    paragraphs: [
      `${site.name}'s Diploma in Computerised Accounting in ${site.city} is for students who want to make accounts their career, not just learn one software. It combines everything a fresher accountant is expected to know in one programme, taught in the order you will use it.`,
      "The first month builds solid accounting principles — journals, ledgers, adjustments and final accounts. You then spend the longest block on Tally Prime with GST, followed by BUSY so you can work on either package. After that come the compliance skills: preparing GSTR-1 and GSTR-3B, reconciling input tax credit with GSTR-2B, income tax basics, TDS sections and returns. Advanced Excel — lookups, pivot tables and reconciliation sheets — ties it together.",
      "The last month is a live accounting project: a full set of books for a sample business, with GST, TDS, bank reconciliation and final accounts, reviewed by your trainer. You finish with a diploma, an internship letter and a portfolio of work to show employers.",
    ],
    image: "tally-gst.webp",
    imageAlt: "Accounting diploma students working in Tally Prime at the techcadd lab",
    imageTag: "Six months, job-ready",
    getList: [
      "Tally Prime, BUSY and Advanced Excel in one programme",
      "GST return and TDS practice on sample data",
      "Live accounting project reviewed by your trainer",
      "Diploma certificate + internship letter",
      "Placement support with resume and mock interviews",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "7", label: "Modules" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who should do this diploma",
    text: "The diploma assumes only basic computer use. Commerce students move faster in the first month, but the programme is designed so that any 12th pass can finish it job-ready.",
    items: [
      { icon: "student", title: "12th pass students", text: "Start an accounts career straight after school, or alongside a distance/regular B.Com." },
      { icon: "grad", title: "B.Com / BBA graduates", text: "Add the practical software and GST skills that a degree alone does not give you." },
      { icon: "job", title: "Job seekers", text: "Show employers Tally, BUSY, GST and Excel together — the full set most accounts jobs ask for." },
      { icon: "office", title: "Working staff moving into accounts", text: "Step up from billing, data entry or front desk into a proper accounts role." },
      { icon: "shop", title: "Business owners & successors", text: "Understand your own books, GST and TDS well enough to run them or supervise them." },
      { icon: "govt", title: "Govt. & banking aspirants", text: "Build a practical accounting and computer base while you prepare for exams." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why six months beat a string of short courses",
    feature: {
      tag: "Access",
      title: "A long programme that fits your routine",
      text: `Students join the ${site.city} centre from Model Town, Urban Estate, Guru Teg Bahadur Nagar, Adarsh Nagar and Basti Sheikh, with weekend learners from Phagwara, Kapurthala, Nakodar and Bhogpur. Morning, evening, weekend and 1-on-1 batches make six months realistic alongside college or work.`,
      slots: ["Morning", "Afternoon", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Depth",
        title: "Two software, one logic",
        text: "Learning Tally and BUSY on the same accounting foundation means you can walk into almost any local office and start working.",
      },
      {
        tag: "Compliance",
        title: "GST and TDS, not just entries",
        text: "Return data, ITC matching, TDS sections and due dates — the compliance work firms actually pay experienced staff for.",
      },
      {
        tag: "Experience",
        title: "A project that counts",
        text: "The final month's live project and internship letter give you something concrete to discuss at interviews.",
      },
      {
        tag: "Excel",
        title: "The skill behind every report",
        text: "Advanced Excel for reconciliations and MIS makes you useful beyond data entry from your first week at work.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Firms want accountants who can do it all.",
    points: [
      "With GST returns, TDS returns and e-invoicing, small firms prefer one person who can handle entries, compliance and Excel reporting.",
      "Fresher accountants with Tally, GST and Excel skills in Punjab typically start around ₹12,000 – ₹20,000 a month, growing steadily with experience.",
      "Six months gives enough time to practise every skill until it is routine — not just see it once.",
    ],
    panel: [
      { k: "Tally & BUSY", v: "Daily bookkeeping" },
      { k: "GSTR-1 / GSTR-3B", v: "Monthly compliance" },
      { k: "TDS returns", v: "Every quarter" },
      { k: "Excel MIS", v: "Every month-end" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, month by month",
    text: "Principles first, then the two main accounting packages, then compliance and Excel, ending with a live project that uses everything together.",
    phases: [
      {
        id: "01",
        name: "Financial Accounting Principles",
        weeks: "Weeks 1–3",
        summary: "A solid base in how accounts are kept and closed.",
        topics: [
          "Golden rules, journal, ledger and subsidiary books",
          "Trial balance, rectification of errors",
          "Depreciation, provisions and adjustments",
          "Trading, P&L account and Balance Sheet by hand",
        ],
        outcome: "Prepare final accounts manually from a trial balance",
      },
      {
        id: "02",
        name: "Tally Prime with GST",
        weeks: "Weeks 4–9",
        summary: "Full business accounting in India's most widely used package.",
        topics: [
          "Company creation, masters, vouchers and inventory",
          "GST set-up, tax invoices, RCM and GST reports",
          "Payroll with PF/ESI and bank reconciliation",
          "Cost centres, budgets and MIS reports",
        ],
        outcome: "A complete sample company maintained in Tally Prime",
      },
      {
        id: "03",
        name: "BUSY Accounting",
        weeks: "Weeks 10–12",
        summary: "The billing and stock package popular with traders and distributors.",
        topics: [
          "Masters, bill sundries and GST tax categories",
          "Sales, purchase, returns and vouchers",
          "Batch, expiry and godown-wise inventory",
          "Outstanding, ageing and data backup",
        ],
        outcome: "A month of trading billing and stock handled in BUSY",
      },
      {
        id: "04",
        name: "GST Returns – GSTR-1, GSTR-3B",
        weeks: "Weeks 13–15",
        summary: "Turn a month's entries into correct GST returns.",
        topics: [
          "GST registration types, composition and due dates",
          "GSTR-1 (and IFF under QRMP) — B2B, B2C, credit notes",
          "GSTR-3B, tax payment and ITC matching with GSTR-2B",
          "E-way bills, e-invoicing (IRN) and GSTR-9 overview",
        ],
        outcome: "Return working papers for GSTR-1 and GSTR-3B",
      },
      {
        id: "05",
        name: "Income Tax & TDS Basics",
        weeks: "Weeks 16–18",
        summary: "The direct-tax work every accounts desk touches.",
        topics: [
          "Heads of income, old vs new regime, common deductions",
          "TDS sections — 192, 194C, 194J, 194I, 194H — and rates",
          "TDS returns 24Q and 26Q, Form 16 / 16A",
          "Form 26AS, AIS and ITR-1 / ITR-4 walkthrough",
        ],
        outcome: "A TDS working and a sample salaried ITR computation",
      },
      {
        id: "06",
        name: "Advanced Excel for Accountants",
        weeks: "Weeks 19–21",
        summary: "Excel for reconciliations, analysis and MIS.",
        topics: [
          "VLOOKUP / XLOOKUP, SUMIFS and IF-based formulas",
          "Pivot tables and charts for sales and expense analysis",
          "GSTR-2B vs purchase register reconciliation",
          "Data validation, protection and MIS templates",
        ],
        outcome: "Reusable reconciliation and MIS workbooks",
      },
      {
        id: "07",
        name: "Live Accounting Project",
        weeks: "Weeks 22–24",
        summary: "Keep a full year's books end to end, reviewed like real work.",
        topics: [
          "Books of a sample business from opening balances",
          "GST, TDS and payroll for every month",
          "Bank reconciliation and year-end adjustments",
          "Final accounts, MIS pack and trainer review",
        ],
        outcome: "A complete accounting project for your portfolio",
      },
    ],
  },
  tools: {
    eyebrow: "Software you will use",
    title: "The complete accounts toolkit",
    text: "Tally, BUSY and Excel are used on your own lab computer; the government portals are walked through step by step with sample data.",
    tools: [
      { name: "Tally Prime", logo: "tally.png", use: "Accounts, GST, payroll" },
      { name: "BUSY", mono: "BUSY", use: "Trading billing & stock" },
      { name: "MS Excel", logo: "excel.png", use: "Reconciliation & MIS" },
      { name: "GST Portal", mono: "GST", use: "GSTR-1, GSTR-3B, GSTR-2B" },
      { name: "Income Tax Portal", mono: "ITR", use: "ITR, 26AS, AIS" },
      { name: "MS Word", logo: "word.png", use: "Letters & reports" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Earn your Diploma in Computerised Accounting",
    text: "Complete all modules and the live project to receive a techcadd diploma and an internship letter — both verifiable online.",
    courseName: "Diploma in Computerised Accounting",
    items: [
      { title: "Diploma certificate", text: "Verifiable online by any employer" },
      { title: "Internship letter", text: "For the live accounting project" },
      { title: "Project portfolio", text: "Books, GST and TDS work you prepared" },
      { title: "Placement support", text: "Resume, mock interviews and job drives" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where the diploma takes you",
    text: "Indicative starting pay for freshers in Punjab. Actual offers depend on the employer, your practical test and interview.",
    roles: [
      { title: "Accountant", pay: "₹12k – 20k", text: "Traders, manufacturers, hospitals and schools" },
      { title: "Accounts Executive", pay: "₹12k – 20k", text: "Company accounts teams and CA offices" },
      { title: "Tax Assistant", pay: "₹10k – 18k", text: "GST, TDS and ITR work in tax offices" },
      { title: "Audit Assistant", pay: "₹10k – 15k", text: "Vouching and checks in CA firms" },
    ],
    hiring: ["CA & tax consultant firms", "Manufacturing units", "Traders & distributors", "Hospitals & schools", "Export houses", "Real estate & builders"],
    qa: [
      {
        q: "What jobs can I get after this diploma?",
        a: "Accountant, accounts executive, tax assistant and audit assistant roles. Knowing Tally, BUSY, GST and Excel together widens the number of firms you can apply to.",
      },
      {
        q: "Is this better than just a Tally course?",
        a: "If you want a career in accounts, yes. The diploma adds BUSY, GST returns, TDS, income tax basics, Advanced Excel and a live project on top of Tally.",
      },
      {
        q: "Does the internship letter help?",
        a: "It records the live accounting project you completed, which gives interviewers something concrete to ask about when you have no job experience yet.",
      },
      {
        q: "Can I grow further after this?",
        a: "Yes. With experience, accountants move into senior accountant, GST/tax consultant or accounts manager roles. Many also continue with B.Com, M.Com or professional exams.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real work in your portfolio",
    text: "Each block ends with a task you complete on your own. The last one is a full live accounting project.",
    items: [
      { n: "01", title: "Manual final accounts", text: "Prepare trading, P&L and Balance Sheet by hand from a trial balance with adjustments.", tags: ["Principles", "Final accounts"] },
      { n: "02", title: "Tally + BUSY company", text: "Maintain a trading company in Tally Prime, then a distributor's billing and stock in BUSY.", tags: ["Tally Prime", "BUSY"] },
      { n: "03", title: "GST & TDS month", text: "Prepare GSTR-1, GSTR-3B and a GSTR-2B reconciliation, plus the month's TDS working.", tags: ["GST", "TDS", "Excel"] },
      { n: "04", title: "Live accounting project", text: "Keep a sample business's books for a full year and present the final accounts and MIS.", tags: ["Project", "Internship"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "Learn it. Post it. Reconcile it.",
    text: "Every topic follows the same three steps, so theory, software and compliance stay connected.",
    steps: [
      { title: "Learn it", text: "The trainer explains the rule or transaction with a real example.", example: "Purchase with RCM" },
      { title: "Post it", text: "You record it in Tally or BUSY on your own computer.", example: "Journal with tax ledgers" },
      { title: "Reconcile it", text: "You check it against the report, return or Excel working.", example: "GSTR-3B and GSTR-2B" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name} for accounts`,
    text: `A six-month commitment deserves a proper look. In ${site.city}, the questions that matter are depth of syllabus, how much you practise and what support you get after the diploma.`,
    items: [
      { title: "Complete syllabus", text: "Principles, Tally, BUSY, GST, TDS, income tax basics and Excel in one track." },
      { title: "Live accounting project", text: "A full year of books, reviewed by your trainer, with an internship letter." },
      { title: "Small batches", text: "Your entries, returns and reconciliations are checked individually." },
      { title: "One student, one computer", text: "Every minute of lab time is your own practice." },
      { title: "Placement support", text: "Resume help, mock interviews and job drives with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any accounting diploma, including this one.",
    rows: [
      { feature: "Software", us: "Tally Prime + BUSY + Advanced Excel", them: "Usually Tally only" },
      { feature: "GST", us: "GSTR-1, GSTR-3B, GSTR-2B, e-way bill, e-invoice", them: "Invoice entry only" },
      { feature: "Direct tax", us: "TDS returns and ITR basics included", them: "Rarely covered" },
      { feature: "Project", us: "Full-year live accounting project", them: "Short exercises" },
      { feature: "Internship", us: "Internship letter on completion", them: "Not offered" },
      { feature: "Batch size", us: "Small batches with individual checking", them: "Large batches" },
      { feature: "Timings", us: "Morning, evening, weekend, 1-on-1", them: "Fixed single slot" },
      { feature: "After the diploma", us: "Placement support and job drives", them: "Limited or none" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Parminder Kaur", role: "Accountant · Jalandhar", text: "Six months felt long at first, but by the project month I was doing GST and TDS work confidently. Got my job soon after." },
    { name: "Karan Arora", role: "B.Com Graduate · Urban Estate", text: "Learning both Tally and BUSY helped a lot — my employer uses BUSY for billing and Tally for accounts." },
    { name: "Sukhwinder Singh", role: "Tax Assistant · Nakodar", text: "The GSTR-2B reconciliation in Excel is something I now do every month at work. Very practical." },
    { name: "Anjali Verma", role: "Accounts Executive · Model Town", text: "The live project gave me something real to talk about in interviews. Trainers reviewed every entry." },
    { name: "Harjit Singh", role: "Family Business · Kapurthala", text: "I joined to understand our own accounts properly. Now I handle the books and talk to our CA with confidence." },
    { name: "Jasleen Kaur", role: "12th Commerce · Phagwara", text: "Weekend batch alongside college. Small group, clear notes and plenty of practice." },
  ],
  faqs: [
    { q: "Do I need a commerce background?", a: "No. The first month teaches accounting principles from the ground up. Commerce students find it familiar, but any 12th pass can follow it." },
    { q: "What is the duration and class timing?", a: "The diploma runs for 6 months. Morning, afternoon, evening and weekend batches are available, plus 1-on-1 slots on request." },
    { q: "Which software is covered?", a: "Tally Prime, BUSY and MS Excel (advanced), with walkthroughs of the GST portal and income tax portal using sample data." },
    { q: "Will I get an internship letter?", a: "Yes. Students who complete the live accounting project receive an internship letter along with the diploma." },
    { q: "Is the diploma verifiable?", a: "Yes. The techcadd diploma can be verified online by employers. It is issued by techcadd and is separate from any software vendor's certification." },
    { q: "Do you help with placement?", a: "Yes. Placement support includes resume preparation, mock interviews and updates on job drives with our 500+ hiring partners." },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, see the lab and meet the trainer before you decide." },
  ],
};

const gstTaxation: CourseDetail = {
  slug: "gst-taxation",
  seo: {
    title: `GST & Taxation Course in ${site.city} | 2-Month Practical Program`,
    description: `Practical GST and income tax training at ${site.name} ${site.city}: registration, input tax credit, GSTR-1, GSTR-3B, e-way bills, e-invoicing, ITR and TDS returns, with portal walkthroughs and a certificate.`,
  },
  hero: {
    crumb: "GST & Taxation",
    tag: "GST & Taxation",
    badge: "Portal Practice",
    title: `Practical GST & Taxation Course in ${site.city}`,
    text: `Go beyond invoice entry: learn GST registration, input tax credit, GSTR-1, GSTR-3B and annual returns, e-way bills and e-invoicing, then income tax, ITR and TDS returns — with step-by-step portal walkthroughs at ${site.name} ${site.city}.`,
    points: ["Live portal walkthroughs", "Return filing workflow", "ITR preparation", "Placement support"],
    facts: [
      { label: "Duration", value: "2 Months" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "Basic accounting / Tally" },
      { label: "Includes", value: "Certificate + return working files" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "8", label: "Weeks", note: "of GST & income tax practice" },
    ],
    hub: {
      center: "tally.png",
      nodes: [
        { logo: "excel.png" },
        { logo: "tally.png" },
        { logo: "word.png" },
        { logo: "google-workspace.svg" },
        { logo: "outlook.svg" },
        { logo: "windows.svg" },
        { icon: "🧾" },
        { icon: "₹" },
      ],
    },
  },
  overview: {
    eyebrow: "Course overview",
    title: "GST and income tax, the way a tax office actually works",
    paragraphs: [
      `${site.name}'s GST & Taxation course in ${site.city} is for people who already understand basic accounting and want to handle the compliance side — the returns, reconciliations and filings that CA offices and businesses need done correctly and on time.`,
      "The GST part starts with concepts and registration — supply, place of supply, CGST/SGST vs IGST, thresholds and the composition scheme — then moves to input tax credit and its conditions, GSTR-2B matching, and the monthly and quarterly returns: GSTR-1, IFF, GSTR-3B, and an overview of GSTR-9. You also learn when an e-way bill is needed and how e-invoicing with IRN works.",
      "The final weeks cover income tax: heads of income, old and new regimes, deductions, Form 26AS and AIS, preparing ITR-1 and ITR-4, and TDS deduction with 24Q/26Q returns. Every topic is practised on sample client data with portal walkthroughs, so you leave with the working files and a clear filing routine.",
    ],
    image: "tally-gst.webp",
    imageAlt: "Student preparing GST return working papers at the techcadd lab",
    imageTag: "Returns, not just theory",
    getList: [
      "Step-by-step GST and income tax portal walkthroughs",
      "Sample client data for every return",
      "Excel templates for GSTR-2B and ITC reconciliation",
      "Due-date calendar and filing checklists",
      "Certificate + a folder of return working papers",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "6", label: "Modules" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who should do this course",
    text: "This is an intermediate course. You should know basic accounting entries, and ideally Tally — if not, start with our Tally Prime with GST course first.",
    items: [
      { icon: "chart", title: "Tally / accounts learners", text: "Take the next step from entering GST invoices to preparing and filing the returns." },
      { icon: "grad", title: "B.Com / M.Com graduates", text: "Turn your tax theory into the portal skills CA offices and tax consultants hire for." },
      { icon: "office", title: "Working accountants", text: "Handle GST, TDS and ITR work yourself instead of passing it on — and earn more for it." },
      { icon: "shop", title: "Business owners", text: "Understand your own returns, ITC and notices, and check what is filed in your name." },
      { icon: "freelance", title: "Aspiring tax consultants", text: "Build the practical base to assist a GST practitioner or start handling small clients." },
      { icon: "job", title: "Job seekers in accounts", text: "GST and TDS knowledge is what separates a tax assistant from a data entry operator." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why two months of GST & tax are worth it",
    feature: {
      tag: "Access",
      title: "Learn around your working hours",
      text: `Many learners here already work in accounts. They reach the ${site.city} centre from Model Town, Lajpat Nagar, Urban Estate and Adarsh Nagar, and from Phagwara, Kapurthala, Nakodar and Kartarpur at weekends. Evening, weekend and 1-on-1 slots are built for working people.`,
      slots: ["Morning", "Afternoon", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Demand",
        title: "Deadlines never stop",
        text: "GSTR-1, GSTR-3B, TDS returns and ITR come round every month, quarter or year. Firms need people who can meet them without errors.",
      },
      {
        tag: "Method",
        title: "Working papers first",
        text: "You prepare each return in Excel from books and statements, then see exactly where each figure goes on the portal.",
      },
      {
        tag: "ITC",
        title: "Where the money is saved",
        text: "Matching purchases with GSTR-2B and knowing which input tax credit is blocked is one of the most valued skills in any tax office.",
      },
      {
        tag: "Breadth",
        title: "GST and income tax together",
        text: "Covering ITR and TDS alongside GST means you can support a client's full compliance, not just one part of it.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Compliance keeps growing. So does the need for trained hands.",
    points: [
      "GST returns, GSTR-2B matching, e-invoicing for larger businesses and TDS returns have made tax compliance a monthly routine for most firms.",
      "Fresher tax assistant and GST assistant roles in Punjab typically start around ₹10,000 – ₹18,000 a month, with more for those who can handle filings independently.",
      "Two months is enough to learn a complete, repeatable filing workflow for common returns.",
    ],
    panel: [
      { k: "GSTR-1", v: "Monthly or quarterly" },
      { k: "GSTR-3B", v: "Monthly or quarterly" },
      { k: "TDS returns", v: "Every quarter" },
      { k: "ITR", v: "Every year" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, week by week",
    text: "GST first, from concepts to annual returns, then income tax and TDS — each module practised on sample client data.",
    phases: [
      {
        id: "01",
        name: "GST Concepts & Registration",
        weeks: "Weeks 1–2",
        summary: "Understand how GST works before filing anything.",
        topics: [
          "Supply, place of supply, CGST/SGST/IGST and cess",
          "Registration thresholds, GSTIN and documents required",
          "Composition scheme, CMP-08 and GSTR-4",
          "Tax invoice rules, HSN/SAC and reverse charge",
        ],
        outcome: "Identify the correct tax and registration for sample cases",
      },
      {
        id: "02",
        name: "Input Tax Credit",
        weeks: "Week 3",
        summary: "Claim every rupee of credit that is allowed, and none that is not.",
        topics: [
          "Conditions for ITC and blocked credits (Section 17(5))",
          "GSTR-2A vs GSTR-2B and supplier compliance",
          "Purchase register vs GSTR-2B reconciliation in Excel",
          "ITC reversal and utilisation order",
        ],
        outcome: "A completed ITC reconciliation for a sample month",
      },
      {
        id: "03",
        name: "GSTR-1, GSTR-3B & Annual Returns",
        weeks: "Weeks 4–5",
        summary: "Prepare and walk through the core GST returns.",
        topics: [
          "GSTR-1 — B2B, B2CS, credit/debit notes, HSN summary",
          "QRMP scheme and IFF",
          "GSTR-3B, tax liability, cash vs credit ledger, late fee and interest",
          "GSTR-9 and GSTR-9C overview",
        ],
        outcome: "GSTR-1 and GSTR-3B working papers for a sample client",
      },
      {
        id: "04",
        name: "E-way Bills & E-invoicing",
        weeks: "Week 6",
        summary: "Handle goods movement and invoice registration rules.",
        topics: [
          "When an e-way bill is required, Part A and Part B",
          "Generating, extending and cancelling e-way bills",
          "E-invoicing applicability, IRP, IRN and QR code",
          "Linking e-invoices with GSTR-1 auto-population",
        ],
        outcome: "Sample e-way bills and e-invoice data prepared",
      },
      {
        id: "05",
        name: "Income Tax Basics",
        weeks: "Week 7",
        summary: "The direct-tax foundation behind every ITR.",
        topics: [
          "Residential status and the five heads of income",
          "Old vs new tax regime, slabs and rebate",
          "Common deductions — 80C, 80D and others",
          "Form 26AS, AIS and advance tax",
        ],
        outcome: "Tax computations for salaried and small-business cases",
      },
      {
        id: "06",
        name: "ITR Filing & TDS Returns",
        weeks: "Week 8",
        summary: "Prepare returns and TDS filings end to end.",
        topics: [
          "ITR-1 (Sahaj) and ITR-4 (Sugam) preparation and e-verification",
          "TDS sections — 192, 194C, 194J, 194I, 194H",
          "TDS payment, 24Q and 26Q returns",
          "Form 16 / 16A and correcting mismatches",
        ],
        outcome: "A sample ITR and quarterly TDS working",
      },
    ],
  },
  tools: {
    eyebrow: "Software you will use",
    title: "The portals and tools of a tax desk",
    text: "Returns are prepared in Excel and Tally on your lab computer, then walked through on the government portals step by step.",
    tools: [
      { name: "GST Portal", mono: "GST", use: "Registration & returns" },
      { name: "Income Tax Portal", mono: "ITR", use: "ITR, 26AS, AIS" },
      { name: "E-way Bill Portal", mono: "EWB", use: "Goods movement" },
      { name: "E-invoice (IRP)", mono: "IRN", use: "Invoice registration" },
      { name: "Tally Prime", logo: "tally.png", use: "GST reports from books" },
      { name: "MS Excel", logo: "excel.png", use: "Reconciliation & working papers" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Get certified in GST & Taxation",
    text: "Complete the course and the return working papers to receive a techcadd certificate you can attach to any job application — verifiable online.",
    courseName: "GST & Taxation",
    items: [
      { title: "Course certificate", text: "Verifiable online by any employer" },
      { title: "Return working papers", text: "GSTR-1, GSTR-3B and ITC reconciliation" },
      { title: "ITR & TDS file", text: "Computations and TDS workings you prepared" },
      { title: "Placement support", text: "Resume help and job-drive updates" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where GST & Taxation takes you",
    text: "Indicative starting pay for freshers in Punjab. Actual offers depend on the employer, your accounting base and how independently you can file.",
    roles: [
      { title: "GST Practitioner Assistant", pay: "₹10k – 16k", text: "Client returns and reconciliations" },
      { title: "Tax Assistant", pay: "₹10k – 18k", text: "GST, TDS and ITR work in CA offices" },
      { title: "Accounts Executive", pay: "₹12k – 18k", text: "Books plus compliance in businesses" },
      { title: "TDS / Compliance Executive", pay: "₹12k – 18k", text: "TDS returns and statutory due dates" },
    ],
    hiring: ["CA firms", "Tax consultants & GST practitioners", "Manufacturing units", "Traders & distributors", "Export houses", "Hospitals & institutions"],
    qa: [
      {
        q: "What jobs can I get after this course?",
        a: "Tax assistant, GST practitioner assistant, accounts executive and compliance roles, mostly in CA offices, tax consultancies and businesses with their own accounts team.",
      },
      {
        q: "Can I become a GST practitioner after this?",
        a: "Enrolling as a GST Practitioner has its own eligibility conditions and an exam conducted by the government. This course builds the practical knowledge that helps with that path.",
      },
      {
        q: "Do I need Tally before this course?",
        a: "Basic accounting is required and Tally is recommended. If you are new to accounts, take Tally Prime with GST first.",
      },
      {
        q: "Can I handle my own business's GST?",
        a: "Yes. Many owners take this course to understand their returns, ITC and notices, and to review filings before they are submitted.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real tasks you will complete",
    text: "Each task uses sample client data, so you practise the same workflow a tax office follows every month.",
    items: [
      { n: "01", title: "Registration case file", text: "Decide registration type and tax for sample businesses and list the documents each needs.", tags: ["GST", "Registration"] },
      { n: "02", title: "ITC reconciliation", text: "Match a purchase register with GSTR-2B in Excel and list credits to claim, follow up or reverse.", tags: ["ITC", "Excel"] },
      { n: "03", title: "Monthly GST returns", text: "Prepare GSTR-1 and GSTR-3B working papers, including credit notes and tax payment.", tags: ["GSTR-1", "GSTR-3B"] },
      { n: "04", title: "ITR & TDS file", text: "Compute tax for a salaried client, prepare an ITR-1 and a quarterly 26Q working.", tags: ["ITR", "TDS"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "Learn the rule. Prepare it. Walk the portal.",
    text: "Every topic follows the same three steps, so law, working papers and filing stay linked.",
    steps: [
      { title: "Learn the rule", text: "The trainer explains the provision with a simple business example.", example: "Blocked ITC on a car" },
      { title: "Prepare it", text: "You prepare the working in Excel or Tally on your own computer.", example: "GSTR-2B reconciliation" },
      { title: "Walk the portal", text: "You follow where each figure goes on the portal, step by step.", example: "GSTR-3B Table 4" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name} for GST`,
    text: `GST and tax theory is easy to find. What is harder to find in ${site.city} is a course that makes you prepare the actual returns and reconciliations, and explains where every number comes from.`,
    items: [
      { title: "Practical tax trainers", text: "Taught by trainers who work with real return cycles and due dates." },
      { title: "Working papers, not just slides", text: "You prepare every return from sample books and statements yourself." },
      { title: "Small batches", text: "Your reconciliations and computations are checked individually." },
      { title: "GST and income tax together", text: "GST, ITC, ITR and TDS in one course for complete client support." },
      { title: "Placement support", text: "Resume help, mock interviews and job drives with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any GST or taxation course, including this one.",
    rows: [
      { feature: "Approach", us: "Working papers + portal walkthroughs", them: "Mostly theory and sections" },
      { feature: "ITC", us: "GSTR-2B reconciliation in Excel", them: "Explained, not practised" },
      { feature: "Returns", us: "GSTR-1, IFF, GSTR-3B, GSTR-9 overview", them: "Often GSTR-3B only" },
      { feature: "E-way bill & e-invoice", us: "Included with sample data", them: "Briefly mentioned" },
      { feature: "Income tax", us: "ITR-1, ITR-4, TDS returns", them: "Separate course or skipped" },
      { feature: "Batch size", us: "Small batches with individual checking", them: "Large batches" },
      { feature: "Timings", us: "Morning, evening, weekend, 1-on-1", them: "Fixed single slot" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Rajdeep Singh", role: "Tax Assistant · Jalandhar", text: "I knew Tally but not the returns. After this course I prepare GSTR-1 and GSTR-3B for clients at a CA office." },
    { name: "Meenakshi Sharma", role: "M.Com Graduate · Lajpat Nagar", text: "The GSTR-2B reconciliation in Excel was the most useful part. It is exactly what I was asked in my interview." },
    { name: "Baljit Singh", role: "Auto Parts Dealer · Kartarpur", text: "Now I understand my own ITC and what my consultant files. Explained in simple language." },
    { name: "Simranjeet Kaur", role: "Accounts Executive · Phagwara", text: "Evening classes after work. TDS returns and ITR were covered step by step with sample data." },
    { name: "Ankit Mehta", role: "B.Com Final Year · Model Town", text: "Clear teaching, small batch and lots of practice files to revise from." },
    { name: "Gurpreet Kaur", role: "Accountant · Kapurthala", text: "The e-way bill and e-invoice module cleared many doubts I had at my job. Worth the time." },
  ],
  faqs: [
    { q: "Do I need to know accounting before joining?", a: "Yes, basic accounting is needed and Tally is recommended. If you are new to accounts, we suggest Tally Prime with GST first." },
    { q: "What is the duration and class timing?", a: "The course runs for 2 months. Morning, afternoon, evening and weekend batches are available, plus 1-on-1 slots on request." },
    { q: "Will I file returns on the real portal?", a: "You prepare every return on sample client data and follow the complete filing steps on the GST and income tax portals with your trainer. Actual filing needs a taxpayer's own login, so live submissions are done only for real clients at work." },
    { q: "Is income tax covered along with GST?", a: "Yes. Heads of income, old vs new regime, deductions, Form 26AS/AIS, ITR-1 and ITR-4 preparation and TDS returns (24Q, 26Q) are part of the course." },
    { q: "Are e-way bills and e-invoicing included?", a: "Yes. You learn when an e-way bill is required, how to generate and extend one, and how e-invoicing with IRN and QR code works for businesses it applies to." },
    { q: "Will I get a certificate?", a: "Yes. You receive a techcadd certificate on completing the course and working papers, which can be verified online." },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, see the lab and meet the trainer before you decide." },
  ],
};

export const accounting: CourseDetail[] = [tallyPrimeGst, busyAccounting, computerisedAccountingDiploma, gstTaxation];
