// Course pages for the "Digital Marketing" category. See ./types.ts for what each field is.
import { site } from "../site";
import type { CourseDetail } from "./types";

const digitalMarketingCourse: CourseDetail = {
  slug: "digital-marketing",
  seo: {
    title: `Digital Marketing Course in ${site.city} | 4-Month Practical Program`,
    description: `Learn SEO, Google Ads, Meta Ads, social media, email, WhatsApp marketing and GA4 at ${site.name} ${site.city}, with live campaigns, a WordPress website of your own, a certificate and placement support.`,
  },
  hero: {
    crumb: "Digital Marketing",
    tag: "Digital Marketing",
    badge: "Live Campaigns",
    title: `Best Digital Marketing Course in ${site.city}`,
    text: `Build a website, rank it on Google, run Search and Meta ad campaigns, and read the numbers in Google Analytics — a four-month, hands-on program at ${site.name} ${site.city} where every module ends in real work on a live account.`,
    points: ["Live ad campaigns", "Your own website", "Certification prep", "Placement support"],
    facts: [
      { label: "Duration", value: "4 Months" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "12th pass or above" },
      { label: "Includes", value: "Certificate + campaign portfolio" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "9", label: "Modules", note: "SEO, ads, social, analytics" },
    ],
    hub: {
      center: "google-ads.svg",
      nodes: [
        { logo: "meta.svg" },
        { logo: "google-analytics.svg" },
        { logo: "search-console.svg" },
        { logo: "wordpress.svg" },
        { logo: "canva.svg" },
        { logo: "semrush.svg" },
        { icon: "📈" },
        { icon: "@" },
      ],
    },
  },
  overview: {
    eyebrow: "Course overview",
    title: "One program that covers the whole digital marketing job",
    paragraphs: [
      `${site.name}'s Digital Marketing course in ${site.city} is for people who want to be hired as a digital marketer, take on clients as a freelancer, or bring their own family business online — without having to piece the subject together from scattered YouTube videos.`,
      "You start by building a WordPress website of your own, because every other module needs somewhere to send traffic. Then you learn to earn traffic (SEO, content, social media) and to buy it (Google Ads and Meta Ads), and to bring people back through email and WhatsApp. Google Analytics 4 and Search Console run through the whole course, so every decision is based on numbers rather than guesswork.",
      "By the end you have a live website, audit and campaign reports, a content calendar and a results sheet you can show in an interview or to a first client — plus the preparation to sit Google's free Skillshop certification exams on your own.",
    ],
    image: "digital-marketing.webp",
    imageAlt: "Students planning an online ad campaign in the techcadd lab",
    imageTag: "Real accounts, real data",
    getList: [
      "A WordPress website you build and own",
      "Hands-on practice in Google Ads and Meta Ads Manager",
      "GA4 and Search Console reports read every week",
      "Ready-made templates for audits, calendars and reports",
      "Certificate + a portfolio of campaign work",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "16", label: "Weeks" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who this course is for",
    text: "You need basic computer and internet skills and the patience to test, measure and adjust. No coding and no marketing degree are required.",
    items: [
      { icon: "grad", title: "Graduates & final-year students", text: "BBA, B.Com, BA or BCA — add a practical, in-demand skill that agencies and businesses hire for directly." },
      { icon: "job", title: "Job seekers & career switchers", text: "Move from sales, telecalling or office work into a marketing role where your results can be measured and shown." },
      { icon: "shop", title: "Business owners", text: "Run your own Google and Instagram campaigns and stop paying for promotions you cannot measure." },
      { icon: "freelance", title: "Aspiring freelancers", text: "Learn the services local clients actually pay for — Google Business Profile, ads, social handling and SEO." },
      { icon: "chart", title: "Sales & marketing staff", text: "Understand leads, cost per lead and reports so you can work with agencies instead of just forwarding their PDFs." },
      { icon: "home", title: "Homemakers & home entrepreneurs", text: "Promote a home bakery, boutique or tuition class online, with flexible weekend and 1-on-1 slots." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why four months of structured practice beats random tutorials",
    feature: {
      tag: "Access",
      title: "Batches that fit around work and college",
      text: `Students join the ${site.city} centre from Model Town, Urban Estate, Rama Mandi and Guru Teg Bahadur Nagar, and weekend learners come in from Phagwara, Kapurthala, Nakodar and Hoshiarpur. Morning, evening, weekend and 1-on-1 slots let you learn alongside a job or college, and ad-account work can continue from home between classes.`,
      slots: ["Morning", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Complete",
        title: "Every channel, in the right order",
        text: "Website, SEO, ads, social, email and analytics are taught as one system, so you understand how a lead actually moves from a search or a reel to a phone call.",
      },
      {
        tag: "Method",
        title: "Live accounts, not screenshots",
        text: "You set up campaigns, tracking and reports yourself inside real tools. The trainer reviews your account settings, not just your answers.",
      },
      {
        tag: "Portfolio",
        title: "Proof you can show",
        text: "Interviews and clients ask what you have done. You leave with a website, an SEO audit, ad reports and a content calendar to point to.",
      },
      {
        tag: "Current",
        title: "Taught as the platforms work today",
        text: "GA4, Performance Max, Meta Advantage+ campaigns, Google's AI-generated search results and WhatsApp Business — the syllabus follows the tools as they change.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Local businesses are moving online and need people who can run it",
    points: [
      `Immigration consultancies, coaching centres, clinics, showrooms and export houses around ${site.city} now get most of their enquiries from Google, Instagram and WhatsApp — and most of them still manage it with no trained person in-house.`,
      "Entry-level digital marketing roles in Punjab typically start around ₹12,000 – ₹20,000 a month, and pay grows with results you can prove rather than with years served.",
      "The same skills work for a job, for freelancing or for your own business — very few courses give you all three options.",
    ],
    panel: [
      { k: "Google Search", v: "Where buyers look first" },
      { k: "Instagram & Reels", v: "Where brands are discovered" },
      { k: "WhatsApp", v: "Where enquiries close" },
      { k: "GA4 reports", v: "How results are proven" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, week by week",
    text: "Sixteen weeks that follow how a real campaign is built: first a website, then free traffic, then paid traffic, then retention and measurement — finishing with a full campaign plan of your own.",
    phases: [
      {
        id: "01",
        name: "Digital Marketing Fundamentals",
        weeks: "Week 1",
        summary: "Understand how customers find and choose a business online.",
        topics: [
          "Marketing funnel: awareness, consideration, conversion",
          "Owned, earned and paid media",
          "Buyer personas for local businesses",
          "Key metrics: CTR, CPC, CPL, conversion rate, ROAS",
        ],
        outcome: "A one-page marketing plan for a sample business",
      },
      {
        id: "02",
        name: "Website Building with WordPress",
        weeks: "Weeks 2–3",
        summary: "Build the website every other module sends traffic to.",
        topics: [
          "Domain, hosting and WordPress installation",
          "Themes, page builders and essential plugins",
          "Landing pages, contact forms and WhatsApp buttons",
          "Speed, mobile layout and basic security",
        ],
        outcome: "Your own live WordPress website with a landing page",
      },
      {
        id: "03",
        name: "Search Engine Optimisation (SEO)",
        weeks: "Weeks 4–6",
        summary: "Earn free, steady traffic from Google.",
        topics: [
          "Keyword research and search intent",
          "On-page SEO: titles, headings, content, internal links",
          "Technical basics: indexing, sitemaps, Core Web Vitals",
          "Local SEO and Google Business Profile, link building",
        ],
        outcome: "An SEO audit and keyword plan for your website",
      },
      {
        id: "04",
        name: "Google Ads (Search, Display, YouTube)",
        weeks: "Weeks 7–9",
        summary: "Buy targeted traffic and measure every rupee.",
        topics: [
          "Account structure, keywords, match types and bidding",
          "Responsive search ads and assets",
          "Display, YouTube and Demand Gen campaigns",
          "Performance Max overview and budget control",
        ],
        outcome: "A Search campaign built and launched on a live account",
      },
      {
        id: "05",
        name: "Social Media Marketing",
        weeks: "Weeks 10–11",
        summary: "Grow a brand on Instagram, Facebook, YouTube and LinkedIn.",
        topics: [
          "Platform strategy and brand voice",
          "Reels, carousels and posting schedules",
          "Content calendars and Canva design",
          "Community management and handling enquiries",
        ],
        outcome: "A one-month content calendar with designed posts",
      },
      {
        id: "06",
        name: "Meta (Facebook & Instagram) Ads",
        weeks: "Weeks 12–13",
        summary: "Run lead and traffic campaigns that local businesses rely on.",
        topics: [
          "Business Manager, pages, ad accounts and Pixel",
          "Campaign objectives, audiences and placements",
          "Lead forms, Click-to-WhatsApp and Advantage+ campaigns",
          "Creative testing and cost-per-lead tracking",
        ],
        outcome: "A lead-generation campaign with a results sheet",
      },
      {
        id: "07",
        name: "Email & WhatsApp Marketing",
        weeks: "Week 14",
        summary: "Bring enquiries back and turn them into customers.",
        topics: [
          "Building a permission-based contact list",
          "Email campaigns, automation and newsletters",
          "WhatsApp Business: catalogues, labels, broadcasts",
          "Follow-up sequences and avoiding spam",
        ],
        outcome: "An email newsletter and a WhatsApp follow-up flow",
      },
      {
        id: "08",
        name: "Google Analytics & Search Console",
        weeks: "Week 15 (used throughout)",
        summary: "Prove what worked and what did not.",
        topics: [
          "GA4 setup, events and key events (conversions)",
          "Traffic sources, UTM links and campaign reports",
          "Search Console: queries, pages and indexing",
          "Monthly client reports with Looker Studio",
        ],
        outcome: "A monthly performance report for your website",
      },
      {
        id: "09",
        name: "Content & Influencer Marketing + Capstone",
        weeks: "Week 16",
        summary: "Tie everything into one complete campaign.",
        topics: [
          "Blog, video and content planning around keywords",
          "Using AI tools responsibly for drafts and ideas",
          "Working with local creators and influencers",
          "Capstone: full campaign plan with budget and KPIs",
        ],
        outcome: "A complete digital campaign plan presented to the batch",
      },
    ],
  },
  tools: {
    eyebrow: "Tools you will use",
    title: "The same tools agencies use every day",
    text: "Each tool is used hands-on during class — you set up accounts, build campaigns and pull reports yourself.",
    tools: [
      { name: "Google Ads", logo: "google-ads.svg", use: "Search, Display & YouTube ads" },
      { name: "Meta Ads Manager", logo: "meta.svg", use: "Facebook & Instagram ads" },
      { name: "Google Analytics 4", logo: "google-analytics.svg", use: "Traffic & conversions" },
      { name: "Search Console", logo: "search-console.svg", use: "Google search performance" },
      { name: "WordPress", logo: "wordpress.svg", use: "Websites & landing pages" },
      { name: "Canva", logo: "canva.svg", use: "Posts, reels & ad creatives" },
      { name: "SEMrush", logo: "semrush.svg", use: "Keyword & competitor research" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Get certified in Digital Marketing",
    text: `Complete the course and your practical projects to receive a ${site.name} certificate, verifiable online. We also prepare you to sit Google's free Skillshop certification exams, which you take on your own account.`,
    courseName: "Digital Marketing",
    items: [
      { title: "Course certificate", text: "Verifiable online by any employer" },
      { title: "Google certification prep", text: "Practice for Skillshop Ads & Analytics exams" },
      { title: "Campaign portfolio", text: "Website, audit, ad reports and calendar" },
      { title: "Placement support", text: "Resume, mock interviews and job drives" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where this course takes you",
    text: "Indicative monthly starting pay for freshers in Punjab. Actual offers depend on the employer, your portfolio and how you interview; freelance income depends entirely on the clients you find.",
    roles: [
      { title: "Digital Marketing Executive", pay: "₹12k – 20k", text: "Agencies and in-house teams handling SEO, ads and social" },
      { title: "SEO Executive", pay: "₹10k – 18k", text: "Keyword research, on-page work and reporting" },
      { title: "Social Media Manager", pay: "₹10k – 18k", text: "Content calendars, reels and page growth for brands" },
      { title: "PPC Specialist", pay: "₹14k – 22k", text: "Google and Meta ad campaigns, budgets and tracking" },
    ],
    hiring: ["Digital marketing agencies", "Immigration & IELTS consultancies", "Coaching centres & schools", "Hospitals & clinics", "Export houses & manufacturers", "Real estate & showrooms"],
    qa: [
      {
        q: "Can I get a job after this course without experience?",
        a: "Yes, many agencies and local businesses hire freshers for executive roles. Your website, audit and campaign reports from the course act as your experience in the interview.",
      },
      {
        q: "Can I start freelancing?",
        a: "You can, but expect it to grow slowly. Most students begin with one or two small local clients — Google Business Profile, social handling or basic ads — and build from there. We guide you on pricing and proposals.",
      },
      {
        q: "Will this help my own business?",
        a: "Yes. Business owners use the course to run their own Google and Instagram campaigns, track enquiries and judge whether an agency is actually delivering.",
      },
      {
        q: "Which area should I specialise in later?",
        a: "Most people pick one after the course — SEO, performance ads or social media — based on what they enjoyed most. Our shorter SEO, Social Media and Google Ads courses go deeper into each.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real projects you will complete",
    text: "Every project is built on a live website or account, reviewed by your trainer, and goes into the portfolio you take to interviews.",
    items: [
      { n: "01", title: "Your own business website", text: "Build a WordPress site with a landing page, contact form and WhatsApp button, connected to GA4 and Search Console.", tags: ["WordPress", "GA4"] },
      { n: "02", title: "SEO audit & keyword plan", text: "Audit a local business website and write a prioritised fix list with target keywords for each page.", tags: ["SEO", "Search Console"] },
      { n: "03", title: "Live ad campaigns", text: "Set up a Google Search campaign and a Meta lead campaign on small budgets, then report cost per lead.", tags: ["Google Ads", "Meta Ads"] },
      { n: "04", title: "Content calendar & report", text: "Plan and design a month of posts and reels, then present a monthly performance report.", tags: ["Canva", "Reporting"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "Learn it. Launch it. Measure it.",
    text: "Digital marketing is learned by doing and checking the numbers, so every topic follows the same three steps.",
    steps: [
      { title: "Learn it", text: "The trainer explains the idea and shows it inside the real tool.", example: "Keyword match types" },
      { title: "Launch it", text: "You set it up yourself on your own website or account.", example: "Building an ad group" },
      { title: "Measure it", text: "You check the data, find what to change and adjust.", example: "Pausing costly keywords" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name}`,
    text: `There is no shortage of digital marketing courses in ${site.city}. The difference is how much time you spend inside real tools, whether your work is reviewed, and whether anyone helps you after the certificate.`,
    items: [
      { title: "Trainers who run campaigns", text: "Taught by people who work in ad accounts and analytics, not just from slides." },
      { title: "Hands-on in every class", text: "One computer per student and live tools open in every session." },
      { title: "Small batches", text: "Your campaigns and reports get individual review, not a quick glance." },
      { title: "Updated syllabus", text: "GA4, Performance Max, Advantage+ and AI search changes are covered as they happen." },
      { title: "Placement support", text: "Resume and portfolio help, mock interviews and job drives with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any digital marketing course, including this one.",
    rows: [
      { feature: "Practice", us: "Live websites and ad accounts", them: "Mostly theory and screenshots" },
      { feature: "Website", us: "You build your own WordPress site", them: "Often skipped" },
      { feature: "Paid ads", us: "Google Ads and Meta Ads both covered", them: "Usually only one platform" },
      { feature: "Analytics", us: "GA4 and Search Console every week", them: "One short session" },
      { feature: "Batch size", us: "Small batches with account reviews", them: "Large batches" },
      { feature: "Portfolio", us: "Website, audit, ad reports, calendar", them: "Certificate only" },
      { feature: "Timings", us: "Morning, evening, weekend, 1-on-1", them: "Fixed single slot" },
      { feature: "After the course", us: "Placement and freelancing guidance", them: "Limited or none" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Harpreet Singh", role: "Digital Marketing Executive · Jalandhar", text: "The Meta ads and GA4 modules were the most useful. I showed my campaign report in the interview and got my first agency job." },
    { name: "Ritika Bansal", role: "B.Com Graduate · Model Town", text: "I liked that we built our own website first. Everything after that made more sense because I could see my own data." },
    { name: "Jaspreet Kaur", role: "Boutique Owner · Urban Estate", text: "I now run my own Instagram ads and track enquiries on WhatsApp. I know exactly what I am spending per lead." },
    { name: "Karan Mehta", role: "Freelancer · Phagwara", text: "Started with two small local clients after the course. Slow in the beginning, but the proposal and reporting guidance helped a lot." },
    { name: "Amandeep Kaur", role: "Marketing Assistant · Immigration Consultancy", text: "Our office used to depend fully on an outside agency. Now I handle the Google Business Profile and lead forms myself." },
    { name: "Rohit Sharma", role: "Evening Batch Student · Rama Mandi", text: "Evening batch worked with my job. Small group, and the trainer actually checked our ad accounts every week." },
  ],
  faqs: [
    { q: "Do I need any technical or coding knowledge?", a: "No. Basic computer and internet use is enough. WordPress is set up without coding, and everything else is taught step by step." },
    { q: "What is the duration and class timing?", a: "The course runs for 4 months. Morning, evening and weekend batches are available, plus 1-on-1 slots on request." },
    { q: "Will I run real ad campaigns?", a: "Yes. You build and launch campaigns on live accounts, usually with small daily budgets on your own or a practice business's account. The trainer helps you set limits so spending stays under control." },
    { q: "Are Google and Meta certifications included?", a: "We prepare you for Google's free Skillshop certification exams (Google Ads and Analytics), which you take on your own account. Meta's certifications can be prepared for in the same way, but they are Meta's own exams." },
    { q: "Will I get a certificate from the institute?", a: `Yes. You receive a ${site.name} certificate on completing the course and projects, which can be verified online.` },
    { q: "Is placement support available?", a: "Yes. We help with your resume and portfolio, run mock interviews and share openings and job drives from our hiring partners." },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, see the lab and meet the trainer before you decide." },
  ],
};

const seoCourse: CourseDetail = {
  slug: "seo",
  seo: {
    title: `SEO Course in ${site.city} | 2-Month Practical SEO Training`,
    description: `Learn keyword research, on-page, technical, off-page and local SEO at ${site.name} ${site.city}, practised on live websites with Search Console, GA4 and SEMrush — plus a certificate and placement support.`,
  },
  hero: {
    crumb: "SEO",
    tag: "SEO",
    badge: "Live Website Practice",
    title: `Best SEO Course in ${site.city}`,
    text: `Learn how Google decides what to show, then practise ranking real web pages — keyword research, on-page fixes, technical checks, local SEO and monthly reporting — in a two-month, hands-on course at ${site.name} ${site.city}.`,
    points: ["Live websites", "Local SEO", "Audit reports", "Placement support"],
    facts: [
      { label: "Duration", value: "2 Months" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "12th pass, basic computer use" },
      { label: "Includes", value: "Certificate + SEO audit report" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "7", label: "Modules", note: "on-page to local SEO" },
    ],
    hub: {
      center: "search-console.svg",
      nodes: [
        { logo: "google-analytics.svg" },
        { logo: "semrush.svg" },
        { logo: "wordpress.svg" },
        { logo: "search-console.svg" },
        { logo: "google-workspace.svg" },
        { logo: "canva.svg" },
        { icon: "🔍" },
        { icon: "📍" },
      ],
    },
  },
  overview: {
    eyebrow: "Course overview",
    title: "Practical SEO, learned on websites that are actually live",
    paragraphs: [
      `${site.name}'s SEO course in ${site.city} is for anyone who wants to get websites found on Google — freshers aiming for an SEO executive role, content writers who want their articles to rank, and business owners tired of paying for results they cannot check.`,
      "You begin with how search engines crawl, index and rank pages, and how Google's AI-generated answers are changing what a search result looks like. Then you work through keyword research, on-page optimisation, technical SEO, link building and local SEO with Google Business Profile — each one applied to a live WordPress website rather than a dummy example.",
      "The course ends with a full SEO audit and a monthly report built from Search Console and GA4 data — the two documents clients and employers most often ask to see.",
    ],
    image: "digital-marketing.webp",
    imageAlt: "Student reviewing Google Search Console data in the techcadd lab",
    imageTag: "Rank real pages",
    getList: [
      "Practice on a live WordPress website",
      "Search Console and GA4 used every week",
      "Keyword research in SEMrush and free tools",
      "Audit and reporting templates you keep",
      "Certificate + a complete SEO audit report",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "8", label: "Weeks" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who this course is for",
    text: "SEO rewards patience and attention to detail more than any technical background. If you can use a browser and write clear English, you can learn it.",
    items: [
      { icon: "grad", title: "Graduates & students", text: "Start a career in SEO, one of the most common entry points into digital marketing agencies." },
      { icon: "job", title: "Content writers & bloggers", text: "Write articles that match what people search for and get them indexed and ranked." },
      { icon: "shop", title: "Local business owners", text: "Show up in Google Maps and 'near me' searches for your shop, clinic or institute." },
      { icon: "freelance", title: "Freelancers", text: "Offer SEO audits, Google Business Profile setup and monthly SEO as client services." },
      { icon: "chart", title: "Digital marketers", text: "Add solid SEO skills to ads and social media knowledge you already have." },
      { icon: "office", title: "Web designers & developers", text: "Build websites that are fast, indexable and easy for Google to understand from day one." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why SEO is still worth learning properly",
    feature: {
      tag: "Access",
      title: "Two months, at a time that suits you",
      text: `Students come to the ${site.city} centre from Model Town, Adarsh Nagar, Basti Sheikh and Urban Estate, with weekend learners from Kapurthala, Phagwara and Nakodar. Morning, evening, weekend and 1-on-1 slots are available, and SEO tasks on your practice website continue between classes.`,
      slots: ["Morning", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Free traffic",
        title: "Traffic that doesn't stop when the budget does",
        text: "Ads stop the day payment stops. A well-optimised page can keep bringing enquiries for months, which is why businesses keep paying for SEO.",
      },
      {
        tag: "Local",
        title: "'Near me' searches decide footfall",
        text: "Coaching centres, clinics and consultancies depend on Google Maps. Local SEO and Google Business Profile skills are needed by almost every local business.",
      },
      {
        tag: "Method",
        title: "Live pages, real data",
        text: "You make changes to a real website and watch the effect in Search Console, so you learn what actually moves rankings.",
      },
      {
        tag: "Current",
        title: "Taught for today's search results",
        text: "AI-generated answers, helpful-content signals and Core Web Vitals are covered, not SEO tricks that stopped working years ago.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Every business wants to be found on Google — few know how",
    points: [
      `Immigration consultancies, coaching centres, hospitals and export houses around ${site.city} compete for the same searches, and most still lack anyone who understands SEO.`,
      "SEO executive roles in Punjab typically start around ₹10,000 – ₹18,000 a month for freshers, with growth tied to the results you can show.",
      "Search is changing with AI answers, so people who understand content quality and technical basics are more useful than ever.",
    ],
    panel: [
      { k: "Google Search", v: "Where buyers start" },
      { k: "Google Maps", v: "Where local customers look" },
      { k: "Search Console", v: "How rankings are tracked" },
      { k: "Content", v: "What gets cited and ranked" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, week by week",
    text: "Eight weeks that follow the order of a real SEO project: understand the search, choose the keywords, fix the pages, fix the site, build authority, win local searches and report the results.",
    phases: [
      {
        id: "01",
        name: "How Search Engines Work",
        weeks: "Week 1",
        summary: "Understand crawling, indexing and ranking before touching a page.",
        topics: [
          "Crawling, indexing and ranking explained",
          "Search results: ads, maps, snippets and AI answers",
          "Google's guidelines, helpful content and E-E-A-T",
          "Setting up Search Console and GA4 on your site",
        ],
        outcome: "A practice website connected to Search Console and GA4",
      },
      {
        id: "02",
        name: "Keyword Research",
        weeks: "Week 2",
        summary: "Find the searches worth ranking for.",
        topics: [
          "Search intent: informational, commercial, local",
          "Keyword Planner, SEMrush and free tools",
          "Long-tail and local keywords",
          "Keyword mapping to pages",
        ],
        outcome: "A keyword map for a local business website",
      },
      {
        id: "03",
        name: "On-Page SEO",
        weeks: "Week 3",
        summary: "Make each page clearly relevant to its keyword.",
        topics: [
          "Title tags, meta descriptions and headings",
          "Writing and improving content for intent",
          "Internal linking and URL structure",
          "Image optimisation and schema basics",
        ],
        outcome: "Three optimised pages on your practice website",
      },
      {
        id: "04",
        name: "Technical SEO",
        weeks: "Weeks 4–5",
        summary: "Make sure Google can crawl, render and trust the site.",
        topics: [
          "XML sitemaps, robots.txt and canonical tags",
          "Crawling a site with Screaming Frog",
          "Core Web Vitals, page speed and mobile usability",
          "Fixing indexing, redirect and duplicate-content issues",
        ],
        outcome: "A technical issue list with fixes applied",
      },
      {
        id: "05",
        name: "Off-Page SEO & Link Building",
        weeks: "Week 6",
        summary: "Build authority the safe way.",
        topics: [
          "How links and brand mentions help rankings",
          "Local citations, directories and PR opportunities",
          "Guest posts and outreach emails",
          "Spotting and avoiding spammy links",
        ],
        outcome: "A link-building plan with real outreach targets",
      },
      {
        id: "06",
        name: "Local SEO",
        weeks: "Week 7",
        summary: "Win Google Maps and 'near me' searches.",
        topics: [
          "Google Business Profile setup and optimisation",
          "Categories, photos, posts and Q&A",
          "Getting and replying to reviews",
          "Consistent name, address and phone across the web",
        ],
        outcome: "An optimised Google Business Profile checklist",
      },
      {
        id: "07",
        name: "SEO Audits & Reporting",
        weeks: "Week 8",
        summary: "Show what you found, what you fixed and what changed.",
        topics: [
          "Full SEO audit structure",
          "Rank tracking and Search Console reports",
          "GA4 organic traffic and conversions",
          "Monthly client reports in Looker Studio",
        ],
        outcome: "A complete SEO audit and a monthly report",
      },
    ],
  },
  tools: {
    eyebrow: "Tools you will use",
    title: "The tools SEO professionals rely on",
    text: "Every tool is used hands-on on your practice website — you pull the data and act on it yourself.",
    tools: [
      { name: "Google Search Console", logo: "search-console.svg", use: "Indexing & search queries" },
      { name: "Google Analytics 4", logo: "google-analytics.svg", use: "Organic traffic & conversions" },
      { name: "SEMrush / Ahrefs", logo: "semrush.svg", use: "Keywords & competitors" },
      { name: "Screaming Frog", mono: "SF", use: "Technical site crawls" },
      { name: "WordPress", logo: "wordpress.svg", use: "On-page changes" },
      { name: "Google Business Profile", mono: "GBP", use: "Local SEO & Maps" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Get certified in SEO",
    text: `Complete the course and your audit project to receive a ${site.name} certificate, verifiable online. Your SEO audit and monthly report are yours to show employers and clients.`,
    courseName: "Search Engine Optimisation (SEO)",
    items: [
      { title: "Course certificate", text: "Verifiable online by any employer" },
      { title: "SEO audit report", text: "A complete audit you prepared yourself" },
      { title: "Reporting templates", text: "Audit, keyword map and monthly report" },
      { title: "Placement support", text: "Resume, mock interviews and job drives" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where this course takes you",
    text: "Indicative monthly starting pay for freshers in Punjab. Actual offers depend on the employer, your audit work and how you interview.",
    roles: [
      { title: "SEO Executive", pay: "₹10k – 18k", text: "On-page, technical fixes and reporting at agencies" },
      { title: "SEO Analyst", pay: "₹12k – 20k", text: "Audits, keyword research and performance tracking" },
      { title: "Content Strategist", pay: "₹10k – 18k", text: "Planning and optimising content around search intent" },
      { title: "Local SEO Specialist", pay: "₹10k – 16k", text: "Google Business Profile and Maps for local businesses" },
    ],
    hiring: ["Digital marketing agencies", "IT & web development companies", "Immigration consultancies", "Coaching institutes", "E-commerce sellers", "Hospitals & clinics"],
    qa: [
      {
        q: "Is SEO still worth learning with AI search?",
        a: "Yes. Google still sends most website traffic, and AI answers draw on well-structured, trustworthy pages. The fundamentals — useful content, clean technical setup and authority — matter more, not less.",
      },
      {
        q: "How soon can I see ranking results?",
        a: "SEO takes time. Small on-page fixes can show movement in a few weeks, but competitive keywords often take months. The course teaches you to report progress honestly.",
      },
      {
        q: "Can I do SEO as a freelancer?",
        a: "Yes. Local SEO and Google Business Profile work are common first projects. Income depends on the clients you find, so most start part-time alongside a job.",
      },
      {
        q: "What should I learn after SEO?",
        a: "Google Ads & PPC pairs naturally with SEO, or you can take the full Digital Marketing course to cover social media and Meta ads as well.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real SEO work you will complete",
    text: "Each project uses a live website and real data, reviewed by your trainer before it goes into your portfolio.",
    items: [
      { n: "01", title: "Keyword map", text: "Research and map keywords to every page of a local business website, grouped by search intent.", tags: ["SEMrush", "Keyword Planner"] },
      { n: "02", title: "On-page optimisation", text: "Rewrite titles, headings and content for three pages and track their impressions in Search Console.", tags: ["WordPress", "On-page"] },
      { n: "03", title: "Google Business Profile", text: "Optimise a business profile with categories, photos, posts and a review-reply plan.", tags: ["Local SEO", "Maps"] },
      { n: "04", title: "Full SEO audit", text: "Crawl a website, list technical, on-page and off-page issues and present prioritised fixes.", tags: ["Screaming Frog", "Audit"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "Find it. Fix it. Track it.",
    text: "SEO is a cycle of spotting problems, fixing them and checking the data. Every topic is taught the same way.",
    steps: [
      { title: "Find it", text: "The trainer shows how to spot an issue or opportunity in a real tool.", example: "Pages not indexed" },
      { title: "Fix it", text: "You apply the fix on your own practice website.", example: "Updating the sitemap" },
      { title: "Track it", text: "You check Search Console to confirm the change took effect.", example: "Page now indexed" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name}`,
    text: `Many SEO courses in ${site.city} stop at theory. What matters is whether you practise on a live website and learn to read real data.`,
    items: [
      { title: "Practitioner trainers", text: "Trainers who work with Search Console and real sites, not only slides." },
      { title: "Live website practice", text: "Every change you learn is applied to a real, indexed website." },
      { title: "Small batches", text: "Your audits and keyword maps are reviewed individually." },
      { title: "Up-to-date methods", text: "Covers AI answers, helpful content and Core Web Vitals — not outdated tricks." },
      { title: "Placement support", text: "Resume and portfolio help, mock interviews and job drives with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any SEO course, including this one.",
    rows: [
      { feature: "Practice", us: "Live website you optimise yourself", them: "Theory or dummy examples" },
      { feature: "Technical SEO", us: "Crawls, sitemaps, Core Web Vitals", them: "Often skipped" },
      { feature: "Local SEO", us: "Google Business Profile in depth", them: "Briefly mentioned" },
      { feature: "Tools", us: "Search Console, GA4, SEMrush, Screaming Frog", them: "One or two free tools" },
      { feature: "Reporting", us: "Audit + monthly report templates", them: "Not covered" },
      { feature: "Batch size", us: "Small batches with individual review", them: "Large batches" },
      { feature: "Timings", us: "Morning, evening, weekend, 1-on-1", them: "Fixed single slot" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Gurpreet Singh", role: "SEO Executive · Jalandhar", text: "The technical SEO weeks were the most useful. I did a real audit in class and used it in my interview." },
    { name: "Pooja Malhotra", role: "Content Writer · Model Town", text: "I finally understand search intent. My articles now get impressions in Search Console instead of sitting unread." },
    { name: "Dr. Navjot Kaur", role: "Clinic Owner · Adarsh Nagar", text: "Learned to manage our Google Business Profile and reviews myself. More patients mention finding us on Maps." },
    { name: "Vikas Kumar", role: "Web Designer · Kapurthala", text: "I build client websites, and now I set them up properly for SEO from the start. Very practical course." },
    { name: "Mandeep Kaur", role: "B.A. Graduate · Nakodar", text: "Weekend batch, small group. The trainer checked our keyword maps one by one and explained every mistake." },
    { name: "Sahil Arora", role: "Freelancer · Phagwara", text: "Got my first local SEO client two months after the course. Starting small, but the audit template helps a lot." },
  ],
  faqs: [
    { q: "Do I need coding knowledge for SEO?", a: "No. Basic computer use and reading English are enough. Technical SEO is taught step by step using WordPress and tools, without programming." },
    { q: "What is the duration and class timing?", a: "The course runs for 2 months. Morning, evening and weekend batches are available, plus 1-on-1 slots on request." },
    { q: "Will I practise on a real website?", a: "Yes. You work on a live WordPress website connected to Search Console and GA4, so you can see the effect of your changes." },
    { q: "Do you guarantee first-page rankings?", a: "No — and you should be wary of anyone who does. Rankings depend on competition and time. We teach the methods that give a site its best chance and how to measure progress honestly." },
    { q: "Is local SEO included?", a: "Yes. Google Business Profile, reviews and local citations have a full week of their own." },
    { q: "Will I get a certificate?", a: `Yes. You receive a ${site.name} certificate on completing the course and audit project, which can be verified online.` },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, see the lab and meet the trainer before you decide." },
  ],
};

const socialMediaMarketing: CourseDetail = {
  slug: "social-media-marketing",
  seo: {
    title: `Social Media Marketing Course in ${site.city} | 2-Month Program`,
    description: `Learn Instagram, Facebook, YouTube and LinkedIn marketing at ${site.name} ${site.city}: content calendars, reels, Canva, CapCut, Meta Ads basics and insights reporting, with a certificate and placement support.`,
  },
  hero: {
    crumb: "Social Media Marketing",
    tag: "Social Media",
    badge: "Reels & Content",
    title: `Best Social Media Marketing Course in ${site.city}`,
    text: `Plan content, make reels, grow pages on Instagram, Facebook, YouTube and LinkedIn, and run your first paid promotions — a two-month, hands-on course at ${site.name} ${site.city} where you manage a real page from week one.`,
    points: ["Content calendars", "Reels & short video", "Meta Ads basics", "Placement support"],
    facts: [
      { label: "Duration", value: "2 Months" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "10th / 12th pass, smartphone users" },
      { label: "Includes", value: "Certificate + content portfolio" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "4", label: "Platforms", note: "Instagram, Facebook, YouTube, LinkedIn" },
    ],
    hub: {
      center: "meta.svg",
      nodes: [
        { logo: "canva.svg" },
        { logo: "google-analytics.svg" },
        { logo: "meta.svg" },
        { logo: "photoshop.png" },
        { logo: "google-workspace.svg" },
        { logo: "wordpress.svg" },
        { icon: "#" },
        { icon: "🎬" },
      ],
    },
  },
  overview: {
    eyebrow: "Course overview",
    title: "Run a brand's social media like a professional",
    paragraphs: [
      `${site.name}'s Social Media Marketing course in ${site.city} is for people who already spend time on Instagram and YouTube and want to turn that into a skill someone will pay for — as a social media executive, a content creator, or the person who finally runs the family business's pages properly.`,
      "You start with strategy — who the audience is, which platforms matter and what the brand should sound like — then move to content calendars, Canva designs and reels edited in CapCut. From there you grow Instagram and Facebook pages, set up and manage a YouTube channel, build a LinkedIn presence, and run simple Meta ad promotions for reach and enquiries.",
      "Every week ends with work on a real page you manage during the course, and you finish with a content calendar, a set of designed posts and reels, and an insights report showing what grew and why.",
    ],
    image: "digital-marketing.webp",
    imageAlt: "Students planning Instagram content in the techcadd lab",
    imageTag: "Create, post, measure",
    getList: [
      "A real page you manage through the course",
      "Canva and CapCut practice for posts and reels",
      "Ready-to-use content calendar templates",
      "Meta Business Suite and insights every week",
      "Certificate + a portfolio of your content",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "8", label: "Weeks" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who this course is for",
    text: "If you use a smartphone and social media daily, you have the starting point. The course adds the planning, design and measurement that make it a professional skill.",
    items: [
      { icon: "student", title: "Students (12th / college)", text: "Start with a skill that suits your interests and can lead to part-time or full-time work." },
      { icon: "design", title: "Aspiring content creators", text: "Plan, shoot and edit reels and shorts with a consistent style and posting routine." },
      { icon: "shop", title: "Shop & business owners", text: "Run your own Instagram and Facebook pages and promote offers without depending on others." },
      { icon: "freelance", title: "Freelancers", text: "Offer monthly social media handling to local businesses, one of the most requested services." },
      { icon: "job", title: "Job seekers", text: "Social media executive roles are common at agencies, institutes and local brands." },
      { icon: "home", title: "Homemakers & home businesses", text: "Grow a boutique, bakery, tiffin or tuition page with flexible weekend and 1-on-1 slots." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why learn social media properly, not just by posting",
    feature: {
      tag: "Access",
      title: "Short course, flexible timings",
      text: `Students come to the ${site.city} centre from Model Town, Basti Bawa Khel, Urban Estate and Jalandhar Cantt, with weekend learners from Phagwara, Kapurthala, Adampur and Nakodar. Morning, evening, weekend and 1-on-1 slots are available, and much of the content work continues on your phone between classes.`,
      slots: ["Morning", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Planning",
        title: "Consistency beats going viral",
        text: "Pages that grow post on a plan. You learn to build a content calendar a business can actually keep up with.",
      },
      {
        tag: "Video",
        title: "Reels and shorts, made simply",
        text: "Short video drives reach on Instagram, Facebook and YouTube. You learn to script, shoot on a phone and edit in CapCut.",
      },
      {
        tag: "Paid",
        title: "Boosting done the right way",
        text: "Instead of pressing 'Boost post', you learn Meta Ads Manager basics — audiences, objectives and budgets that bring enquiries, not just likes.",
      },
      {
        tag: "Proof",
        title: "Insights, not guesses",
        text: "Clients and employers want to see growth. You learn to read insights and present a clear monthly report.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Every business needs someone to run its pages",
    points: [
      `Immigration consultancies, coaching centres, salons, boutiques and restaurants in ${site.city} get a large share of their enquiries through Instagram and WhatsApp — and most want someone to handle it for them.`,
      "Social media executive roles in Punjab typically start around ₹10,000 – ₹18,000 a month for freshers, and many students also take on one or two local pages part-time.",
      "Short video now leads reach on every major platform, and businesses need people who can produce it regularly.",
    ],
    panel: [
      { k: "Instagram Reels", v: "Discovery & reach" },
      { k: "Facebook", v: "Local communities & leads" },
      { k: "YouTube", v: "Search & long-term views" },
      { k: "LinkedIn", v: "B2B & professional brands" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, week by week",
    text: "Eight weeks that move from planning to creating to growing to measuring, with a real page managed alongside the lessons.",
    phases: [
      {
        id: "01",
        name: "Social Media Strategy",
        weeks: "Week 1",
        summary: "Decide who you are talking to and where.",
        topics: [
          "Goals: awareness, engagement, enquiries",
          "Audience personas and competitor pages",
          "Choosing platforms for a business",
          "Brand voice, bio and profile setup",
        ],
        outcome: "A social media strategy for one brand",
      },
      {
        id: "02",
        name: "Content Planning & Calendars",
        weeks: "Week 2",
        summary: "Plan a month of content you can actually deliver.",
        topics: [
          "Content pillars and post formats",
          "Monthly content calendar in Google Sheets",
          "Designing posts and carousels in Canva",
          "Captions, hashtags and festival/occasion planning",
        ],
        outcome: "A one-month content calendar with designed posts",
      },
      {
        id: "03",
        name: "Instagram & Facebook Growth",
        weeks: "Weeks 3–4",
        summary: "Grow followers and engagement on Meta platforms.",
        topics: [
          "Reels: hooks, scripting, shooting on a phone",
          "Editing reels in CapCut",
          "Stories, highlights, collaborations and lives",
          "Meta Business Suite scheduling and inbox",
        ],
        outcome: "A set of published reels and scheduled posts",
      },
      {
        id: "04",
        name: "YouTube Channel Management",
        weeks: "Week 5",
        summary: "Set up and grow a channel that gets found.",
        topics: [
          "Channel setup, branding and playlists",
          "Titles, descriptions, tags and thumbnails",
          "YouTube Shorts vs long videos",
          "YouTube Studio analytics",
        ],
        outcome: "An optimised YouTube channel with uploaded videos",
      },
      {
        id: "05",
        name: "LinkedIn Marketing",
        weeks: "Week 6",
        summary: "Build a professional and company presence.",
        topics: [
          "Personal profile and company page setup",
          "Posts, articles and carousels for B2B audiences",
          "Networking and engagement routines",
          "LinkedIn for exporters and service businesses",
        ],
        outcome: "An optimised LinkedIn profile and company page",
      },
      {
        id: "06",
        name: "Meta Ads Basics",
        weeks: "Week 7",
        summary: "Promote posts properly with Ads Manager.",
        topics: [
          "Boost post vs Ads Manager",
          "Objectives, audiences and placements",
          "Lead forms and Click-to-WhatsApp ads",
          "Small budgets and reading ad results",
        ],
        outcome: "A small promotion campaign set up and reviewed",
      },
      {
        id: "07",
        name: "Insights & Reporting",
        weeks: "Week 8",
        summary: "Show what grew, what didn't and what to do next.",
        topics: [
          "Reach, engagement, saves, shares and follows",
          "Instagram, Facebook and YouTube insights",
          "Monthly report in Google Sheets or Slides",
          "Presenting results to a client",
        ],
        outcome: "A monthly insights report for the page you managed",
      },
    ],
  },
  tools: {
    eyebrow: "Tools you will use",
    title: "The tools social media teams use daily",
    text: "Each tool is used hands-on in class and on your phone — you create, schedule and report yourself.",
    tools: [
      { name: "Meta Business Suite", logo: "meta.svg", use: "Scheduling, inbox & insights" },
      { name: "Canva", logo: "canva.svg", use: "Posts, carousels & thumbnails" },
      { name: "CapCut", mono: "CC", use: "Reels & shorts editing" },
      { name: "YouTube Studio", mono: "YT", use: "Uploads & channel analytics" },
      { name: "LinkedIn", mono: "in", use: "Professional & B2B pages" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Get certified in Social Media Marketing",
    text: `Complete the course and your practical work to receive a ${site.name} certificate, verifiable online, along with a portfolio of the content you created.`,
    courseName: "Social Media Marketing",
    items: [
      { title: "Course certificate", text: "Verifiable online by any employer" },
      { title: "Content portfolio", text: "Posts, reels and a content calendar" },
      { title: "Insights report", text: "Real growth data from a page you managed" },
      { title: "Placement support", text: "Resume, mock interviews and job drives" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where this course takes you",
    text: "Indicative monthly starting pay for freshers in Punjab. Actual offers depend on the employer and your portfolio; creator and freelance income varies widely and usually builds slowly.",
    roles: [
      { title: "Social Media Executive", pay: "₹10k – 18k", text: "Planning, posting and reporting for brands and agencies" },
      { title: "Content Creator", pay: "₹10k – 18k", text: "Reels, shorts and posts for businesses and institutes" },
      { title: "Community Manager", pay: "₹10k – 16k", text: "Comments, DMs and enquiries across platforms" },
      { title: "Video Editor (Reels)", pay: "₹10k – 18k", text: "Short-form editing for pages and creators" },
    ],
    hiring: ["Digital marketing agencies", "Immigration consultancies", "Coaching & IELTS institutes", "Salons, boutiques & restaurants", "Real estate firms", "Schools & colleges"],
    qa: [
      {
        q: "Can I get a job with just this course?",
        a: "Yes, social media executive and content roles are common entry points. Your content portfolio and insights report matter more than the certificate in interviews.",
      },
      {
        q: "Do I need an expensive camera?",
        a: "No. Everything in the course is shot on a smartphone and edited in CapCut and Canva.",
      },
      {
        q: "Can I handle pages as a freelancer?",
        a: "Yes. Many students start with one or two local businesses on a monthly basis. Income depends on the clients you find, so treat it as something that grows over time.",
      },
      {
        q: "What should I learn next?",
        a: "The full Digital Marketing course adds SEO, Google Ads and analytics, or you can add Graphic Design to strengthen your creative skills.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real content you will create",
    text: "Every project is done on a real page and reviewed by your trainer. Together they become your content portfolio.",
    items: [
      { n: "01", title: "Brand strategy & calendar", text: "Plan a month of content for a local business with pillars, formats and posting dates.", tags: ["Strategy", "Google Sheets"] },
      { n: "02", title: "Posts & carousels", text: "Design a set of on-brand posts, carousels and story templates in Canva.", tags: ["Canva", "Design"] },
      { n: "03", title: "Reels series", text: "Script, shoot and edit a short series of reels, then publish and track them.", tags: ["CapCut", "Reels"] },
      { n: "04", title: "Monthly insights report", text: "Report reach, engagement and follower growth for the page you managed, with next steps.", tags: ["Insights", "Reporting"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "Plan it. Post it. Read it.",
    text: "Social media is a weekly cycle, and every topic is taught the same way you will do it at work.",
    steps: [
      { title: "Plan it", text: "The trainer shows the idea with real examples from local brands.", example: "A festival offer post" },
      { title: "Post it", text: "You create and publish it on the page you manage.", example: "A 20-second reel" },
      { title: "Read it", text: "You check insights and decide what to repeat or change.", example: "Comparing reach and saves" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name}`,
    text: `Plenty of people in ${site.city} offer social media tips. The difference here is structured practice on a real page, feedback on your content, and help getting work afterwards.`,
    items: [
      { title: "Practical trainers", text: "Trainers who plan and run real brand pages, not just teach the theory." },
      { title: "Real page practice", text: "You manage a live page through the course and see real results." },
      { title: "Small batches", text: "Your posts, reels and reports get individual feedback." },
      { title: "Phone-first content", text: "Everything is made with a smartphone, Canva and CapCut — no costly equipment." },
      { title: "Placement support", text: "Portfolio help, mock interviews and job drives with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any social media course, including this one.",
    rows: [
      { feature: "Practice", us: "A real page managed through the course", them: "Examples only" },
      { feature: "Platforms", us: "Instagram, Facebook, YouTube, LinkedIn", them: "Mostly Instagram" },
      { feature: "Video", us: "Reels scripting, shooting and CapCut editing", them: "Rarely covered" },
      { feature: "Planning", us: "Content calendars you actually build", them: "Tips and trends" },
      { feature: "Paid promotion", us: "Meta Ads Manager basics", them: "Only 'Boost post'" },
      { feature: "Reporting", us: "Monthly insights report", them: "Not covered" },
      { feature: "Timings", us: "Morning, evening, weekend, 1-on-1", them: "Fixed single slot" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Simranjeet Kaur", role: "Social Media Executive · Jalandhar", text: "The content calendar and reels practice helped the most. I showed my page's insights report in my interview." },
    { name: "Aman Verma", role: "College Student · Model Town", text: "I learned to edit reels properly in CapCut. Now I handle the page for a local gym part-time." },
    { name: "Parminder Kaur", role: "Boutique Owner · Basti Bawa Khel", text: "I plan my posts a month ahead now and run small Instagram promotions myself. Enquiries on WhatsApp have gone up." },
    { name: "Jatin Kapoor", role: "Content Creator · Phagwara", text: "The YouTube module fixed my titles and thumbnails. Views are steadier now, even if growth is slow." },
    { name: "Navneet Kaur", role: "Weekend Batch · Kapurthala", text: "Weekend classes suited me. Small group, and the trainer gave feedback on every post I designed." },
    { name: "Rajat Sehgal", role: "Marketing Staff · Coaching Institute", text: "Our institute's Instagram was random before. Now we have a plan and a monthly report for management." },
  ],
  faqs: [
    { q: "Do I need any design or editing experience?", a: "No. Canva and CapCut are taught from the basics, and everything can be done on a laptop or a smartphone." },
    { q: "What is the duration and class timing?", a: "The course runs for 2 months. Morning, evening and weekend batches are available, plus 1-on-1 slots on request." },
    { q: "Will I manage a real page?", a: "Yes. You manage a real page through the course — your own brand, a family business or a practice page — and report its results at the end." },
    { q: "Are paid ads covered?", a: "Yes, the basics of Meta Ads Manager are covered with small promotions. For deeper paid advertising, the full Digital Marketing course goes further." },
    { q: "Is YouTube included?", a: "Yes. Channel setup, optimisation, Shorts and YouTube Studio analytics have a full week." },
    { q: "Will I get a certificate?", a: `Yes. You receive a ${site.name} certificate on completing the course and practical work, which can be verified online.` },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, see the lab and meet the trainer before you decide." },
  ],
};

const googleAdsPpc: CourseDetail = {
  slug: "google-ads-ppc",
  seo: {
    title: `Google Ads & PPC Course in ${site.city} | 6-Week Practical Training`,
    description: `Learn Google Ads Search, Display, YouTube, Shopping and Performance Max at ${site.name} ${site.city}, with conversion tracking in Tag Manager and GA4, live account practice, certificate and placement support.`,
  },
  hero: {
    crumb: "Google Ads & PPC",
    tag: "Google Ads",
    badge: "Conversion Tracking",
    title: `Best Google Ads & PPC Course in ${site.city}`,
    text: `Plan, build and optimise paid campaigns on Google Search, Display, YouTube and Shopping — with proper conversion tracking so every rupee is accounted for. A focused six-week course at ${site.name} ${site.city} with live account practice.`,
    points: ["Live account practice", "Conversion tracking", "Certification prep", "Placement support"],
    facts: [
      { label: "Duration", value: "1.5 Months" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "Basic digital marketing knowledge" },
      { label: "Includes", value: "Certificate + campaign reports" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "6", label: "Weeks", note: "Search to Performance Max" },
    ],
    hub: {
      center: "google-ads.svg",
      nodes: [
        { logo: "google-analytics.svg" },
        { logo: "search-console.svg" },
        { logo: "google-ads.svg" },
        { logo: "excel.png" },
        { logo: "wordpress.svg" },
        { logo: "semrush.svg" },
        { icon: "₹" },
        { icon: "🎯" },
      ],
    },
  },
  overview: {
    eyebrow: "Course overview",
    title: "Run Google Ads that bring enquiries, not just clicks",
    paragraphs: [
      `${site.name}'s Google Ads & PPC course in ${site.city} is for people who want to handle paid search seriously — digital marketers moving into performance roles, agency staff who manage client budgets, and business owners who want to know exactly what their ad spend is buying.`,
      "You start with account structure, bidding and budgets, then build Search campaigns with tight keyword groups and responsive search ads. From there you cover Display, YouTube and Demand Gen, Shopping with Merchant Center, and Performance Max — including when not to use it. Conversion tracking with Google Tag Manager and GA4 has a full week, because without it no campaign can be optimised.",
      "The course ends with optimisation and reporting: search terms, negative keywords, bid strategies and a clear monthly report. It also prepares you to take Google's free Skillshop Google Ads certifications on your own account.",
    ],
    image: "digital-marketing.webp",
    imageAlt: "Student building a Google Ads search campaign in the techcadd lab",
    imageTag: "Measure every rupee",
    getList: [
      "Hands-on practice inside Google Ads",
      "Conversion tracking with Tag Manager and GA4",
      "Keyword, ad copy and reporting templates",
      "Preparation for Google Skillshop Ads exams",
      "Certificate + campaign reports for your portfolio",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "6", label: "Modules" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who this course is for",
    text: "This is an intermediate course. You should be comfortable with computers, the internet and basic marketing terms; our Digital Marketing course is the best preparation if you are new.",
    items: [
      { icon: "chart", title: "Digital marketers", text: "Move from general marketing into performance roles that manage budgets and results." },
      { icon: "office", title: "Agency executives", text: "Build and optimise client accounts with confidence, not trial and error." },
      { icon: "shop", title: "Business owners", text: "Run your own Search ads and stop overpaying for clicks that never call." },
      { icon: "freelance", title: "Freelancers", text: "Add Google Ads management — a well-paid, results-based service — to what you offer." },
      { icon: "grad", title: "Graduates with DM basics", text: "Specialise early in one of the more technical, measurable areas of marketing." },
      { icon: "job", title: "E-commerce sellers", text: "Promote products with Shopping and Performance Max campaigns linked to Merchant Center." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why a focused Google Ads course pays off",
    feature: {
      tag: "Access",
      title: "Six weeks, fitted around your work",
      text: `Students reach the ${site.city} centre from Model Town, Urban Estate, Rama Mandi and Jalandhar Cantt, and weekend learners come from Phagwara, Kapurthala, Hoshiarpur and Nakodar. Morning, evening, weekend and 1-on-1 slots suit working marketers, and account work continues from home between classes.`,
      slots: ["Morning", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Intent",
        title: "Reach people who are already searching",
        text: "Search ads appear exactly when someone types 'IELTS coaching near me' or 'Canada study visa consultant'. That intent is why businesses keep spending on Google.",
      },
      {
        tag: "Tracking",
        title: "Conversion tracking first",
        text: "Most wasted budgets come from not knowing which clicks became leads. You learn to track calls, forms and WhatsApp clicks properly.",
      },
      {
        tag: "Method",
        title: "Built and checked inside the tool",
        text: "You build campaigns in Google Ads yourself, and the trainer reviews your keywords, ads and settings line by line.",
      },
      {
        tag: "Current",
        title: "Automation, understood",
        text: "Smart bidding, Performance Max and AI-assisted ads are covered, including how to guide them with good data instead of trusting them blindly.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Ad budgets are growing, and so is wasted spend",
    points: [
      `Immigration consultancies, coaching centres, hospitals and export houses around ${site.city} spend steadily on Google Ads, and many lose money to poor structure and missing tracking.`,
      "PPC executive roles in Punjab typically start around ₹14,000 – ₹22,000 a month for freshers, because managing budgets carries responsibility.",
      "As campaigns become more automated, people who can set up clean tracking and read the data become more valuable, not less.",
    ],
    panel: [
      { k: "Search ads", v: "High-intent enquiries" },
      { k: "YouTube & Demand Gen", v: "Reach and remarketing" },
      { k: "Shopping & PMax", v: "Product sales" },
      { k: "Conversion tracking", v: "Proof of results" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, week by week",
    text: "Six weeks, one module each, following the order you would set up and grow a real account.",
    phases: [
      {
        id: "01",
        name: "Account Structure & Bidding",
        weeks: "Week 1",
        summary: "Set up an account that is easy to manage and measure.",
        topics: [
          "Google Ads account, billing and settings",
          "Campaigns, ad groups, keywords and ads",
          "Manual CPC vs smart bidding strategies",
          "Budgets, locations, languages and ad schedules",
        ],
        outcome: "A well-structured account plan for a local business",
      },
      {
        id: "02",
        name: "Search Campaigns",
        weeks: "Week 2",
        summary: "Build the campaigns that bring most local enquiries.",
        topics: [
          "Keyword Planner research and match types",
          "Negative keywords and search terms",
          "Responsive search ads and assets (sitelinks, calls)",
          "Quality Score and landing page relevance",
        ],
        outcome: "A complete Search campaign ready to launch",
      },
      {
        id: "03",
        name: "Display & YouTube Campaigns",
        weeks: "Week 3",
        summary: "Reach people before and after they search.",
        topics: [
          "Display targeting: audiences, topics, placements",
          "YouTube ad formats and video campaigns",
          "Demand Gen campaigns",
          "Remarketing audiences and frequency",
        ],
        outcome: "A remarketing campaign with display and video ads",
      },
      {
        id: "04",
        name: "Shopping & Performance Max",
        weeks: "Week 4",
        summary: "Promote products and use Google's automated campaigns wisely.",
        topics: [
          "Merchant Center and product feeds",
          "Shopping campaign structure",
          "Performance Max asset groups and audience signals",
          "When PMax helps and when it hurts",
        ],
        outcome: "A Shopping / Performance Max setup plan for an online store",
      },
      {
        id: "05",
        name: "Conversion Tracking",
        weeks: "Week 5",
        summary: "Know exactly which clicks turned into leads or sales.",
        topics: [
          "Google Tag Manager tags, triggers and variables",
          "Tracking forms, calls and WhatsApp clicks",
          "GA4 key events and linking to Google Ads",
          "Enhanced conversions and consent mode basics",
        ],
        outcome: "Working conversion tracking on a live website",
      },
      {
        id: "06",
        name: "Optimisation & Reporting",
        weeks: "Week 6",
        summary: "Improve results week by week and explain them clearly.",
        topics: [
          "Search-term reviews and negative lists",
          "Ad testing and bid strategy changes",
          "Cost per lead, conversion rate and ROAS",
          "Monthly client reports in Looker Studio",
        ],
        outcome: "An optimisation log and a monthly performance report",
      },
    ],
  },
  tools: {
    eyebrow: "Tools you will use",
    title: "The tools performance marketers use every day",
    text: "Each tool is used hands-on in class — you build, track and report inside them yourself.",
    tools: [
      { name: "Google Ads", logo: "google-ads.svg", use: "Search, Display, YouTube, PMax" },
      { name: "Google Tag Manager", mono: "GTM", use: "Conversion tags & triggers" },
      { name: "Google Analytics 4", logo: "google-analytics.svg", use: "Key events & audiences" },
      { name: "Keyword Planner", mono: "KP", use: "Keyword research & forecasts" },
      { name: "Merchant Center", mono: "GMC", use: "Product feeds for Shopping" },
      { name: "Looker Studio", mono: "LS", use: "Client reporting dashboards" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Get certified in Google Ads & PPC",
    text: `Complete the course and your campaign projects to receive a ${site.name} certificate, verifiable online. We also prepare you to sit Google's free Skillshop Google Ads certification exams, which you take on your own account.`,
    courseName: "Google Ads & PPC",
    items: [
      { title: "Course certificate", text: "Verifiable online by any employer" },
      { title: "Google Ads exam prep", text: "Practice for Skillshop Search, Display & Video" },
      { title: "Campaign reports", text: "Account plan, tracking setup and results" },
      { title: "Placement support", text: "Resume, mock interviews and job drives" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where this course takes you",
    text: "Indicative monthly starting pay for freshers in Punjab. Actual offers depend on the employer, your campaign reports and how you interview.",
    roles: [
      { title: "PPC Executive", pay: "₹14k – 22k", text: "Building and managing Google Ads for agency clients" },
      { title: "Performance Marketer", pay: "₹15k – 25k", text: "Paid campaigns measured on leads and sales" },
      { title: "Google Ads Specialist", pay: "₹14k – 22k", text: "Search, Shopping and PMax account management" },
      { title: "Campaign Analyst", pay: "₹12k – 20k", text: "Tracking, reporting and optimisation support" },
    ],
    hiring: ["Digital marketing agencies", "Immigration & study-visa consultancies", "Coaching & IELTS institutes", "E-commerce & D2C brands", "Hospitals & clinics", "Export houses"],
    qa: [
      {
        q: "Do I need prior digital marketing knowledge?",
        a: "Basic knowledge helps, since this is an intermediate course. If you are completely new, the full Digital Marketing course covers the foundations and includes Google Ads.",
      },
      {
        q: "Will I spend my own money on ads?",
        a: "Campaigns are built inside real accounts. Where a campaign is launched, it runs on a small, capped budget on your own or a practice business's account — the trainer helps you set limits first.",
      },
      {
        q: "Is the Google Ads certification included?",
        a: "Google's Skillshop certifications are free exams you take on your own account. The course prepares you for them; the certification itself is issued by Google, not by us.",
      },
      {
        q: "Can I manage Google Ads as a freelancer?",
        a: "Yes, but clients trust budgets to people with results. Most start with small local accounts and build a track record before charging more.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real campaign work you will complete",
    text: "Each project is built inside Google Ads or Tag Manager and reviewed by your trainer before it goes into your portfolio.",
    items: [
      { n: "01", title: "Search campaign build", text: "Research keywords, write responsive search ads and structure ad groups for a local service business.", tags: ["Google Ads", "Keyword Planner"] },
      { n: "02", title: "Conversion tracking setup", text: "Track form submissions, calls and WhatsApp clicks with Tag Manager and GA4 on a live website.", tags: ["GTM", "GA4"] },
      { n: "03", title: "Remarketing & YouTube", text: "Build remarketing audiences and a display/video campaign to bring visitors back.", tags: ["Display", "YouTube"] },
      { n: "04", title: "Audit & monthly report", text: "Audit an account for wasted spend and present a monthly report with next steps.", tags: ["Optimisation", "Looker Studio"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "Build it. Track it. Tune it.",
    text: "Paid search improves through small, measured changes. Every topic is taught the same way.",
    steps: [
      { title: "Build it", text: "The trainer shows the setup inside Google Ads, step by step.", example: "A new ad group" },
      { title: "Track it", text: "You make sure every result is measured before spending.", example: "A form-submit conversion" },
      { title: "Tune it", text: "You review the data and adjust keywords, ads or bids.", example: "Adding negative keywords" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name}`,
    text: `Google Ads is easy to start and easy to waste money on. What matters is learning structure and tracking properly, with someone checking your work.`,
    items: [
      { title: "Practitioner trainers", text: "Trainers who manage live ad accounts and budgets." },
      { title: "Hands-on in the tool", text: "You build campaigns in Google Ads yourself, every class." },
      { title: "Small batches", text: "Your account settings and reports are reviewed individually." },
      { title: "Tracking-first approach", text: "A full week on Tag Manager and GA4 conversions." },
      { title: "Placement support", text: "Resume and portfolio help, mock interviews and job drives with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any Google Ads course, including this one.",
    rows: [
      { feature: "Practice", us: "Campaigns built inside Google Ads", them: "Slides and screenshots" },
      { feature: "Campaign types", us: "Search, Display, YouTube, Shopping, PMax", them: "Search only" },
      { feature: "Conversion tracking", us: "Full week on GTM and GA4", them: "Briefly mentioned" },
      { feature: "Optimisation", us: "Search terms, negatives, bid strategies", them: "Not covered" },
      { feature: "Reporting", us: "Monthly report in Looker Studio", them: "Not covered" },
      { feature: "Certification prep", us: "Google Skillshop exam practice", them: "Varies" },
      { feature: "Timings", us: "Morning, evening, weekend, 1-on-1", them: "Fixed single slot" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Gagandeep Singh", role: "PPC Executive · Jalandhar", text: "The conversion tracking week changed how I look at campaigns. My tracking setup project helped me get the job." },
    { name: "Kritika Sood", role: "Digital Marketer · Model Town", text: "I already knew social media. This course gave me the Search and PMax depth I was missing." },
    { name: "Harjit Singh", role: "Immigration Consultant · Jalandhar", text: "We were spending on Google without knowing what worked. Now I read the search terms myself and our cost per lead is lower." },
    { name: "Ankit Chopra", role: "E-commerce Seller · Phagwara", text: "The Merchant Center and Shopping module was exactly what I needed for my online store." },
    { name: "Rupinder Kaur", role: "Agency Executive · Urban Estate", text: "Evening batch after work. Small group and the trainer reviewed our keyword lists one by one." },
    { name: "Deepak Sharma", role: "Freelancer · Hoshiarpur", text: "Managing two small local accounts now. The reporting template makes client updates simple." },
  ],
  faqs: [
    { q: "Is this course for beginners?", a: "It is an intermediate course. Basic computer and marketing knowledge is expected; complete beginners should start with the full Digital Marketing course." },
    { q: "What is the duration and class timing?", a: "The course runs for 1.5 months (about six weeks). Morning, evening and weekend batches are available, plus 1-on-1 slots on request." },
    { q: "Will I work on a live Google Ads account?", a: "Yes. You build campaigns inside real Google Ads accounts. Any live campaign runs on a small, capped budget that you control." },
    { q: "Does the course cover Performance Max and YouTube ads?", a: "Yes. Display, YouTube, Demand Gen, Shopping and Performance Max each get dedicated time." },
    { q: "Will I get a Google certification?", a: "We prepare you for Google's free Skillshop Google Ads exams, which you take on your own account. You also receive a verifiable institute certificate." },
    { q: "Is placement support available?", a: "Yes. We help with your resume and portfolio, run mock interviews and share openings and job drives from our hiring partners." },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, see the lab and meet the trainer before you decide." },
  ],
};

export const digitalMarketing: CourseDetail[] = [digitalMarketingCourse, seoCourse, socialMediaMarketing, googleAdsPpc];
