// Course pages for the "Graphic Design" category. See ./types.ts for what each field is.
import { site } from "../site";
import type { CourseDetail } from "./types";

const graphicDesignCourse: CourseDetail = {
  slug: "graphic-design",
  seo: {
    title: `Graphic Design Course in ${site.city} | 4-Month Photoshop, Illustrator, CorelDRAW & InDesign`,
    description: `Become a job-ready graphic designer at ${site.name} ${site.city}: design principles, Photoshop, Illustrator, CorelDRAW, InDesign, logos, print, packaging and social media creatives, with a portfolio, certificate and placement support.`,
  },
  hero: {
    crumb: "Graphic Design",
    tag: "Graphic Design",
    badge: "Portfolio of 20+ Designs",
    title: `Best Graphic Design Course in ${site.city}`,
    text: `Learn the four programs local studios, printers and agencies actually use — Photoshop, Illustrator, CorelDRAW and InDesign — and the design thinking behind them. In four months at ${site.name} ${site.city} you build logos, brochures, flex banners, packaging and social posts into a portfolio you can show at interviews.`,
    points: ["4 design programs", "Real client-style briefs", "Portfolio of 20+ designs", "Freelancing guidance"],
    facts: [
      { label: "Duration", value: "4 Months" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "10th pass, basic computer use" },
      { label: "Includes", value: "Certificate + portfolio" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "20+", label: "Portfolio pieces", note: "designed by you" },
    ],
    hub: {
      center: "illustrator.svg",
      nodes: [
        { logo: "photoshop.png" },
        { logo: "coreldraw.png" },
        { logo: "indesign.svg" },
        { logo: "canva.svg" },
        { logo: "meta.svg" },
        { logo: "photoshop.png" },
        { icon: "🎨" },
        { icon: "✎" },
      ],
    },
  },
  overview: {
    eyebrow: "Course overview",
    title: "From blank artboard to a portfolio that gets you hired",
    paragraphs: [
      `${site.name}'s Graphic Design course in ${site.city} is a complete four-month program for anyone who wants to design for a living — whether that means a job at a printing press, an ad agency, an export house's in-house team, or freelance work from home.`,
      "It starts with the rules that make a design look right: layout, colour, contrast and typography. Then you learn each program for the job it does best — Photoshop for photos and social posts, Illustrator for logos and vector artwork, CorelDRAW for flex, visiting cards and the print jobs that Punjab's printers run on, and InDesign for multi-page brochures and catalogues.",
      "The last weeks bring it together in real briefs: a full brand identity, print and packaging work, a month of social media creatives and a polished portfolio. Every piece is reviewed by a trainer the way a client or art director would review it, so you learn to take feedback as well as to design.",
    ],
    image: "graphic-design.webp",
    imageAlt: "Students working on design projects in the techcadd lab",
    imageTag: "Design every class",
    getList: [
      "Photoshop, Illustrator, CorelDRAW and InDesign in one course",
      "Client-style briefs with trainer feedback on every design",
      "Print-ready file preparation for flex, cards and brochures",
      "Portfolio of 20+ designs, print and digital",
      "Freelancing and interview guidance at the end",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "9", label: "Modules" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who this course is for",
    text: "You do not need to be good at drawing. You need basic computer use, an eye for what looks neat, and the patience to redo a design until it is right.",
    items: [
      { icon: "student", title: "12th pass students", text: "Start a creative career straight after school, with a portfolio instead of just a marksheet." },
      { icon: "grad", title: "BA / B.Com / BFA students", text: "Add a practical, paid skill alongside your degree — many students freelance while still in college." },
      { icon: "design", title: "Aspiring designers", text: "Turn a hobby with Canva or phone apps into professional work in the tools studios expect." },
      { icon: "shop", title: "Print shop & studio staff", text: "Move from operating machines to designing the flex, cards and wedding invitations yourself." },
      { icon: "freelance", title: "Freelancers & homemakers", text: "Design logos, posts and invitations for local clients from home, on your own schedule." },
      { icon: "office", title: "Marketing & business owners", text: "Make your own brochures, catalogues and social posts instead of waiting on an outside designer." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why four months here are worth it",
    feature: {
      tag: "Access",
      title: "Batches that fit around college or work",
      text: `Design students come to the ${site.city} centre from Model Town, Urban Estate, Basti Sheikh, Rama Mandi and Jalandhar Cantt, with weekend learners travelling in from Phagwara, Kapurthala, Nakodar and Hoshiarpur. Morning, evening, weekend and 1-on-1 slots mean you can keep college or a job going while you build your portfolio.`,
      slots: ["Morning", "Afternoon", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Demand",
        title: "Every business needs visuals",
        text: "Shops, schools, clinics, hotels and exporters all need logos, flex, brochures and a steady stream of social posts — and most of it is designed locally.",
      },
      {
        tag: "Range",
        title: "Four programs, one course",
        text: "Local employers rarely ask for just one tool. Knowing Photoshop, Illustrator, CorelDRAW and InDesign lets you say yes to almost any design job.",
      },
      {
        tag: "Portfolio",
        title: "Show, don't tell",
        text: "Designers are hired on their work, not their certificate. You finish with 20+ pieces across branding, print and social media to show at interviews.",
      },
      {
        tag: "Freedom",
        title: "A skill you can take anywhere",
        text: "Graphic design works in an office, a print shop or from home. Many students start freelancing on small local jobs while they look for a full-time role.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Every business in Punjab now needs a designer",
    points: [
      "Social media has made design a weekly need, not a one-time job — shops, salons, coaching centres and restaurants all post daily creatives.",
      `${site.city}'s print shops, flex printers, wedding card makers and sports goods exporters need designers who can prepare files that print correctly the first time.`,
      "Fresher graphic designers in Punjab typically start around ₹12,000 – ₹20,000 a month, and pay grows with a stronger portfolio.",
    ],
    panel: [
      { k: "Social creatives", v: "Daily posts & reels covers" },
      { k: "Print & flex", v: "Cards, banners, brochures" },
      { k: "Branding", v: "Logos & identity kits" },
      { k: "Packaging", v: "Boxes, labels, catalogues" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, week by week",
    text: "Four months, nine modules. Each program is learned through the kind of work it is actually used for, then everything comes together in branding, print and portfolio projects.",
    phases: [
      {
        id: "01",
        name: "Design Principles, Colour & Typography",
        weeks: "Weeks 1–2",
        summary: "Learn why some designs look professional and others do not.",
        topics: [
          "Layout, alignment, balance and white space",
          "Colour theory, RGB vs CMYK and colour palettes",
          "Choosing and pairing fonts, hierarchy and readability",
          "Reading a design brief and sketching ideas first",
        ],
        outcome: "Critique and fix a poorly designed poster",
      },
      {
        id: "02",
        name: "Adobe Photoshop",
        weeks: "Weeks 3–5",
        summary: "Edit photos and build image-based designs.",
        topics: [
          "Layers, selections, masks and adjustment layers",
          "Background removal, retouching and colour correction",
          "Compositing and text effects",
          "Social post and web banner sizes",
        ],
        outcome: "A retouched portrait and a festival sale poster",
      },
      {
        id: "03",
        name: "Adobe Illustrator",
        weeks: "Weeks 6–8",
        summary: "Draw clean, scalable vector artwork.",
        topics: [
          "Artboards, shapes and the Pen tool",
          "Shape Builder, Pathfinder and alignment",
          "Type on paths, outlines and logo lettering",
          "Icons, simple illustrations and patterns",
        ],
        outcome: "A vector icon set and a traced logo",
      },
      {
        id: "04",
        name: "CorelDRAW",
        weeks: "Weeks 9–10",
        summary: "Work the way Punjab's print and flex industry works.",
        topics: [
          "Drawing tools, nodes and curves",
          "Visiting cards, letterheads and bill books",
          "Flex banners and shop signage at real sizes",
          "Wedding and event invitation layouts",
        ],
        outcome: "A visiting card set and a shop flex, print-ready",
      },
      {
        id: "05",
        name: "Adobe InDesign",
        weeks: "Week 11",
        summary: "Lay out multi-page documents neatly.",
        topics: [
          "Master pages, grids and text frames",
          "Paragraph and character styles",
          "Placing images and exporting print PDFs",
        ],
        outcome: "A 4–8 page brochure or product catalogue",
      },
      {
        id: "06",
        name: "Logo & Brand Identity",
        weeks: "Weeks 12–13",
        summary: "Design a brand from brief to final files.",
        topics: [
          "Research, mood boards and sketching concepts",
          "Logo design, colour and font selection",
          "Stationery: card, letterhead, envelope",
          "A simple brand guideline sheet",
        ],
        outcome: "A complete identity kit for a local business",
      },
      {
        id: "07",
        name: "Print & Packaging Design",
        weeks: "Week 14",
        summary: "Design things that get printed, folded and sold.",
        topics: [
          "Bleed, safe margins, CMYK and resolution",
          "Brochures, tri-folds and flyers",
          "Box dielines, labels and product stickers",
        ],
        outcome: "A product label or box design with a dieline",
      },
      {
        id: "08",
        name: "Social Media Creatives",
        weeks: "Week 15",
        summary: "Design posts that stay consistent across a month.",
        topics: [
          "Post, story and ad sizes for Instagram and Facebook",
          "Templates and consistent brand styling",
          "Quick resizing with Canva for clients",
        ],
        outcome: "A 9-post Instagram grid for one brand",
      },
      {
        id: "09",
        name: "Portfolio Building",
        weeks: "Week 16",
        summary: "Present your best work the way studios expect to see it.",
        topics: [
          "Selecting and mocking up your best pieces",
          "A PDF portfolio and an online portfolio page",
          "Pricing small freelance jobs and talking to clients",
        ],
        outcome: "A finished portfolio ready for interviews",
      },
    ],
  },
  tools: {
    eyebrow: "Software you will use",
    title: "The industry's design tools, on every lab computer",
    text: "Each program is used on your own lab computer for the kind of work it is best at — not just shown on a projector.",
    tools: [
      { name: "Photoshop", logo: "photoshop.png", use: "Photo editing & social posts" },
      { name: "Illustrator", logo: "illustrator.svg", use: "Logos & vector artwork" },
      { name: "CorelDRAW", logo: "coreldraw.png", use: "Flex, cards & print jobs" },
      { name: "InDesign", logo: "indesign.svg", use: "Brochures & catalogues" },
      { name: "Canva", logo: "canva.svg", use: "Quick templates & resizing" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Get certified in Graphic Design",
    text: `Complete the course and your portfolio projects to receive a ${site.name} certificate — verifiable online — alongside the work that actually gets designers hired.`,
    courseName: "Graphic Design",
    items: [
      { title: "Course certificate", text: "Verifiable online by any employer" },
      { title: "Design portfolio", text: "20+ pieces across branding, print and social" },
      { title: "Print-ready files", text: "Your own work, prepared for real printing" },
      { title: "Placement support", text: "Portfolio review, interviews and job updates" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where this course takes you",
    text: "Indicative starting pay for freshers in Punjab. Actual offers depend on the employer, your portfolio and how you interview — design pay grows quickly with experience.",
    roles: [
      { title: "Graphic Designer", pay: "₹12k – 20k", text: "Ad agencies, studios and in-house marketing teams" },
      { title: "Brand Designer", pay: "₹15k – 25k", text: "Logos, identity kits and brand material for businesses" },
      { title: "DTP Operator", pay: "₹10k – 16k", text: "Printing presses, flex printers and publishers" },
      { title: "Freelance Designer", pay: "₹8k – 25k", text: "Income varies by client; most start small alongside a job" },
    ],
    hiring: ["Printing presses & flex printers", "Ad & digital agencies", "Sports goods & export houses", "Wedding card & studio shops", "Schools & coaching institutes", "Retail & real-estate brands"],
    qa: [
      {
        q: "Do I need to be good at drawing?",
        a: "No. Most graphic design is layout, typography and editing, not hand drawing. Sketching skills help with illustration, but they are not required to start.",
      },
      {
        q: "Can I freelance after this course?",
        a: "Yes, many students take small local jobs — logos, invitations, social posts — while they study or work. Income varies a lot, so we suggest treating it as a side income until you have steady clients.",
      },
      {
        q: "Which program do employers ask for most?",
        a: "Print shops and flex printers in Punjab mostly use CorelDRAW; agencies and social media teams lean on Photoshop and Illustrator. This course covers all of them, so you are not limited.",
      },
      {
        q: "What should I learn after this?",
        a: "Digital marketing and social media marketing pair naturally with design. Video editing or UI design are also popular next steps once your portfolio is ready.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real projects in your portfolio",
    text: "Every module ends with a client-style brief. These are the headline projects that anchor your portfolio.",
    items: [
      { n: "01", title: "Logo & brand identity", text: "Design a logo, colour palette, visiting card and letterhead for a local business brief.", tags: ["Illustrator", "Branding"] },
      { n: "02", title: "Social media campaign", text: "Plan and design a 9-post Instagram grid and festive offer creatives for one brand.", tags: ["Photoshop", "Canva"] },
      { n: "03", title: "Print-ready flex & brochure", text: "Prepare a shop flex and a tri-fold brochure with correct size, bleed and CMYK for printing.", tags: ["CorelDRAW", "InDesign"] },
      { n: "04", title: "Final portfolio", text: "Mock up, organise and present your best 20+ designs as a PDF and online portfolio.", tags: ["Portfolio", "Presentation"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "Brief. Design. Review.",
    text: "Every topic is taught the way design work happens in a studio, so you learn to work with feedback, not just with software.",
    steps: [
      { title: "Brief", text: "The trainer explains the task and demonstrates the key technique on the big screen.", example: "A café needs a menu flyer" },
      { title: "Design", text: "You create your own version on your computer while the trainer checks your progress.", example: "Layout, fonts and photos" },
      { title: "Review", text: "Your design is reviewed like a client would review it, and you revise it until it is ready.", example: "Fixing spacing and colours" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name}`,
    text: `Plenty of places in ${site.city} teach a design program or two. What differs is whether you learn all the tools employers ask for, get honest feedback on your work, and leave with a portfolio instead of just notes.`,
    items: [
      { title: "Trainers who review your work", text: "Every design gets specific feedback on layout, colour and type — not just a tick." },
      { title: "One student, one computer", text: "Every minute of lab time is spent designing on your own machine." },
      { title: "Small batches", text: "Small enough that the trainer sees and corrects your work every class." },
      { title: "Print knowledge included", text: "Bleed, CMYK and file preparation so your designs print correctly." },
      { title: "Placement support", text: "Portfolio reviews, mock interviews and job drives with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any graphic design course, including this one.",
    rows: [
      { feature: "Programs covered", us: "Photoshop, Illustrator, CorelDRAW, InDesign", them: "Often one or two programs" },
      { feature: "Design basics", us: "Colour, typography and layout taught first", them: "Straight into tool buttons" },
      { feature: "Projects", us: "Client-style briefs with feedback", them: "Copying tutorials" },
      { feature: "Print readiness", us: "Bleed, CMYK and real sizes covered", them: "Rarely covered" },
      { feature: "Portfolio", us: "20+ designs, PDF and online", them: "Left to the student" },
      { feature: "Batch size", us: "Small batches with individual attention", them: "Large, crowded batches" },
      { feature: "Timings", us: "Morning, evening, weekend, 1-on-1", them: "Fixed single slot" },
      { feature: "After the course", us: "Placement support + freelancing guidance", them: "Certificate only" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Harpreet Kaur", role: "Graphic Designer · Jalandhar", text: "The portfolio projects helped most. I showed my brand identity and brochure at the interview and they asked more about those than my certificate." },
    { name: "Rohit Bhatia", role: "BA Student · Model Town", text: "I only knew Canva before. Now I design posts and logos in Illustrator and Photoshop for two local shops alongside college." },
    { name: "Gurpreet Singh", role: "DTP Operator · Rama Mandi", text: "I worked at a flex shop printing other people's files. After the CorelDRAW and print module I design the jobs myself." },
    { name: "Sakshi Mehta", role: "Freelancer · Urban Estate", text: "The trainer's feedback was honest and specific. I redid my logo four times and it was much better for it." },
    { name: "Jaspreet Singh", role: "In-house Designer · Basti Sheikh", text: "The packaging and label work was useful for my job at a sports goods unit. Small batch, so I got real attention." },
    { name: "Navneet Kaur", role: "Homemaker · Kapurthala", text: "Weekend batch suited me well. I now make wedding invitations and festival posts for people I know." },
  ],
  faqs: [
    { q: "Do I need drawing skills or a design background?", a: "No. The course starts with design basics and each program from its first screen. Basic computer use is enough to begin." },
    { q: "What is the duration and class timing?", a: "The course runs for 4 months. Morning, afternoon, evening and weekend batches are available, plus 1-on-1 slots on request." },
    { q: "Which software will I learn?", a: "Adobe Photoshop, Adobe Illustrator, CorelDRAW and Adobe InDesign, with Canva for quick social media resizing." },
    { q: "Will I get a certificate?", a: `Yes. You receive a ${site.name} certificate on completing the course and portfolio projects, which can be verified online.` },
    { q: "Do I need my own laptop?", a: "No. Every student gets a lab computer with the software installed. A laptop helps for practice at home but is not required." },
    { q: "Do you help with jobs or freelancing?", a: "Yes. We help you finish your portfolio, prepare for interviews and share job openings, and we cover how to price and handle small freelance jobs." },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, see the lab and some student work, and meet the trainer before you decide." },
    { q: "Can I learn only one program instead?", a: "Yes. We also offer separate 1.5-month courses in Adobe Photoshop, CorelDRAW and Adobe Illustrator." },
  ],
};

const photoshop: CourseDetail = {
  slug: "adobe-photoshop",
  seo: {
    title: `Adobe Photoshop Course in ${site.city} | 1.5-Month Photo Editing & Design`,
    description: `Learn Adobe Photoshop at ${site.name} ${site.city}: layers, selections, masks, photo retouching, compositing, posters, banners and social media creatives, with a certificate and placement support.`,
  },
  hero: {
    crumb: "Adobe Photoshop",
    tag: "Adobe Photoshop",
    badge: "Beginner Friendly",
    title: `Best Adobe Photoshop Course in ${site.city}`,
    text: `Learn to edit photos, retouch portraits and design posters, banners and social posts in Photoshop — taught hands-on at ${site.name} ${site.city}, with every technique practised on real photos and real design briefs.`,
    points: ["Photo retouching", "Posters & banners", "Social media designs", "Certificate included"],
    facts: [
      { label: "Duration", value: "1.5 Months" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "Basic computer use" },
      { label: "Includes", value: "Certificate + design files" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "100%", label: "Practical", note: "real photos, every class" },
    ],
    hub: {
      center: "photoshop.png",
      nodes: [
        { logo: "meta.svg" },
        { logo: "canva.svg" },
        { logo: "illustrator.svg" },
        { logo: "indesign.svg" },
        { logo: "coreldraw.png" },
        { logo: "meta.svg" },
        { icon: "📷" },
        { icon: "🖌" },
      ],
    },
  },
  overview: {
    eyebrow: "Course overview",
    title: "Photo editing and design, the professional way",
    paragraphs: [
      `${site.name}'s Adobe Photoshop course in ${site.city} is a focused six-week program for anyone who works with photos or wants to — students, photographers, studio staff, shop owners and aspiring designers.`,
      "You start with the interface and the tools, then move to the skills everything in Photoshop depends on: selections, layers, masks and adjustment layers. With those in place you learn portrait retouching, background removal, colour correction and restoring old photos, then text effects and compositing multiple images into one design.",
      "The final week is design work: festival posters, shop banners and a set of social media creatives in the right sizes. You finish with a folder of before-and-after edits and designs you made yourself, a certificate, and a clear path into Illustrator or the full Graphic Design course.",
    ],
    image: "graphic-design.webp",
    imageAlt: "Student editing a photo in Adobe Photoshop at techcadd",
    imageTag: "Real photos, real edits",
    getList: [
      "Hands-on with real portraits and product photos",
      "Non-destructive editing with layers and masks",
      "Retouching, restoration and colour correction",
      "Posters, banners and social posts in correct sizes",
      "Certificate + a folder of before-and-after work",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "6", label: "Modules" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who can do this course",
    text: "If you can use a computer and a mouse, you can learn Photoshop. The course starts from the first screen and builds up one tool at a time.",
    items: [
      { icon: "student", title: "School & college students", text: "Learn a creative skill that is in demand and useful for projects, events and part-time work." },
      { icon: "design", title: "Aspiring designers", text: "Photoshop is the first program most designers learn — a solid start before Illustrator or CorelDRAW." },
      { icon: "shop", title: "Photo & wedding studios", text: "Retouch portraits, edit album sheets and fix lighting and colour faster and better." },
      { icon: "freelance", title: "Freelancers", text: "Offer photo editing, background removal and social posts to local clients." },
      { icon: "office", title: "Shop & business owners", text: "Make your own product photos, offer posters and WhatsApp creatives without outsourcing." },
      { icon: "home", title: "Homemakers & hobbyists", text: "Edit family photos, restore old pictures and design invitations and greetings." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why six weeks of Photoshop are worth it",
    feature: {
      tag: "Access",
      title: "Timings that fit your day",
      text: `Students reach the ${site.city} centre from Model Town, Adarsh Nagar, Garha, Maqsudan and Jalandhar Cantt, with weekend learners coming in from Phagwara, Kapurthala, Kartarpur and Adampur. Morning, evening, weekend and 1-on-1 slots let studio staff and students fit six weeks in without missing work or classes.`,
      slots: ["Morning", "Afternoon", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Demand",
        title: "Photos are everywhere",
        text: "Studios, e-commerce sellers, shops and social media pages all need clean, well-edited images every day.",
      },
      {
        tag: "Method",
        title: "Learn on real photos",
        text: "You practise on portraits, product shots and old photos — the same kind of images clients actually bring in.",
      },
      {
        tag: "Speed",
        title: "Short and focused",
        text: "Six weeks, one program. You leave able to do real editing and design work, not just knowing where the menus are.",
      },
      {
        tag: "Next step",
        title: "A foundation for design",
        text: "Photoshop skills carry straight into Illustrator, CorelDRAW and the full Graphic Design course, so the next step goes faster.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Every post, product and wedding album goes through Photoshop",
    points: [
      "Local businesses now post offers and product photos on Instagram and WhatsApp every week — and they need them to look professional.",
      `Wedding studios and photo labs in and around ${site.city} need editors who can retouch and prepare album sheets quickly, especially in the wedding season.`,
      "Fresher photo editors and junior designers in Punjab usually start around ₹10,000 – ₹18,000 a month, with more for strong portfolios.",
    ],
    panel: [
      { k: "Retouching", v: "Portraits & weddings" },
      { k: "Product photos", v: "Shops & online sellers" },
      { k: "Social posts", v: "Offers & festivals" },
      { k: "Posters & banners", v: "Events & promotions" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, week by week",
    text: "Six modules, one per week. The first three build the core skills every edit depends on; the last three put them to work.",
    phases: [
      {
        id: "01",
        name: "Interface & Tools",
        weeks: "Week 1",
        summary: "Find your way around Photoshop with confidence.",
        topics: [
          "Workspace, panels and document setup",
          "Resolution, image size and canvas size",
          "Move, crop, brush, eraser and clone tools",
          "Saving as PSD, JPG and PNG correctly",
        ],
        outcome: "Crop, resize and export photos for print and web",
      },
      {
        id: "02",
        name: "Selections & Layers",
        weeks: "Week 2",
        summary: "Control exactly what you edit.",
        topics: [
          "Marquee, lasso, quick selection and Select Subject",
          "Refining edges for hair and fine detail",
          "Working with layers, groups and blend modes",
          "Layer styles: shadows, strokes and glows",
        ],
        outcome: "A clean background removal on a portrait",
      },
      {
        id: "03",
        name: "Masks & Adjustment Layers",
        weeks: "Week 3",
        summary: "Edit without damaging the original photo.",
        topics: [
          "Layer masks and clipping masks",
          "Levels, Curves, Hue/Saturation and Color Balance",
          "Selective colour changes",
          "Non-destructive editing workflow",
        ],
        outcome: "A colour-corrected product photo set",
      },
      {
        id: "04",
        name: "Photo Retouching & Restoration",
        weeks: "Week 4",
        summary: "Make people and old photos look their best.",
        topics: [
          "Spot healing, healing brush and patch tool",
          "Skin retouching that still looks natural",
          "Restoring torn, faded and scratched photos",
          "Camera Raw basics for exposure and tone",
        ],
        outcome: "A retouched portrait and a restored old photo",
      },
      {
        id: "05",
        name: "Text Effects & Compositing",
        weeks: "Week 5",
        summary: "Combine images and type into one design.",
        topics: [
          "Type tools, fonts and text effects",
          "Blending multiple photos into one scene",
          "Matching light, shadow and colour",
          "Smart objects and filters",
        ],
        outcome: "A composite poster with custom text effects",
      },
      {
        id: "06",
        name: "Posters, Banners & Social Creatives",
        weeks: "Week 6",
        summary: "Design the work clients ask for most.",
        topics: [
          "Festival and sale posters",
          "Web banners and print banner sizes",
          "Instagram post, story and Facebook cover sizes",
          "Mockups and presenting your work",
        ],
        outcome: "A set of social creatives and a poster for one brand",
      },
    ],
  },
  tools: {
    eyebrow: "Software you will use",
    title: "Photoshop and the tools around it",
    text: "Everything below is used in class on your own lab computer.",
    tools: [
      { name: "Photoshop", logo: "photoshop.png", use: "Editing, retouching & design" },
      { name: "Camera Raw", mono: "Cr", use: "Exposure & colour correction" },
      { name: "Adobe Bridge", mono: "Br", use: "Organising photo shoots" },
      { name: "Meta Business Suite", logo: "meta.svg", use: "Post sizes & previews" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Get certified in Adobe Photoshop",
    text: `Finish the course and your practical projects to receive a ${site.name} certificate you can attach to any job application — verifiable online.`,
    courseName: "Adobe Photoshop",
    items: [
      { title: "Course certificate", text: "Verifiable online by any employer" },
      { title: "Before-and-after folder", text: "Retouching and restoration you did yourself" },
      { title: "Design samples", text: "Posters, banners and social posts" },
      { title: "Placement support", text: "Portfolio help and job updates" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where this course takes you",
    text: "Indicative starting pay for freshers in Punjab. Actual offers depend on the employer, your work samples and how you interview.",
    roles: [
      { title: "Photo Editor", pay: "₹10k – 18k", text: "Wedding studios, photo labs and e-commerce sellers" },
      { title: "Graphic Designer", pay: "₹12k – 20k", text: "Agencies and in-house teams, usually with Illustrator too" },
      { title: "Studio Designer", pay: "₹10k – 16k", text: "Album design, prints and studio promotions" },
      { title: "Social Media Designer", pay: "₹10k – 18k", text: "Posts and creatives for local brands and agencies" },
    ],
    hiring: ["Wedding & photo studios", "Photo labs & album makers", "Digital marketing agencies", "E-commerce sellers", "Printing presses", "Retail & showroom brands"],
    qa: [
      {
        q: "Is Photoshop alone enough for a job?",
        a: "It is enough for photo editing and studio roles. For graphic designer jobs, most employers also want Illustrator or CorelDRAW, which is why many students go on to the full Graphic Design course.",
      },
      {
        q: "Can I earn from home with Photoshop?",
        a: "Some students take small jobs like background removal, photo edits and social posts. Income is irregular at first, so treat it as a side income until you have regular clients.",
      },
      {
        q: "Does this cover AI features in Photoshop?",
        a: "We show the built-in AI tools like Select Subject and Generative Fill where they help, but the course focuses on the manual skills you need to fix and control the result.",
      },
      {
        q: "What should I learn after this?",
        a: "Adobe Illustrator or CorelDRAW are the natural next steps. The 4-month Graphic Design course covers all of them plus InDesign and a full portfolio.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real tasks you will complete",
    text: "Each module ends with a task you finish on your own. Together they become your Photoshop work folder.",
    items: [
      { n: "01", title: "Portrait retouch", text: "Clean up skin, fix lighting and colour, and remove the background from a portrait — keeping it natural.", tags: ["Retouching", "Masks"] },
      { n: "02", title: "Old photo restoration", text: "Repair tears, scratches and fading on an old family photograph.", tags: ["Healing", "Restoration"] },
      { n: "03", title: "Social media set", text: "Design a festive offer post, story and Facebook cover for a local shop.", tags: ["Social posts", "Typography"] },
      { n: "04", title: "Event poster", text: "Composite photos, text effects and branding into a print-ready event or sale poster.", tags: ["Compositing", "Print"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "See it. Edit it. Own it.",
    text: "Every technique follows the same three steps, so nothing is left as theory.",
    steps: [
      { title: "See it", text: "The trainer demonstrates one technique on a real photo on the big screen.", example: "Refining a hair selection" },
      { title: "Edit it", text: "You apply it to your own photo while the trainer checks your screen.", example: "Cutting out a portrait" },
      { title: "Own it", text: "A short task at the end proves you can do it on a new photo without help.", example: "Placing it on a new background" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name}`,
    text: `YouTube can show you Photoshop tools. What it cannot do is look at your edit and tell you exactly what to fix — which is most of what a trainer in a small ${site.city} batch is for.`,
    items: [
      { title: "Trainers who check your edits", text: "Specific feedback on every retouch and design, not just a demo." },
      { title: "One student, one computer", text: "Every minute of lab time is spent editing on your own machine." },
      { title: "Small batches", text: "Small enough that the trainer sees your screen every class." },
      { title: "Real practice photos", text: "Portraits, products and old photos like the ones clients bring." },
      { title: "Placement support", text: "Portfolio help, mock interviews and job drives with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any Photoshop course, including this one.",
    rows: [
      { feature: "Practice time", us: "One computer per student, every class", them: "Shared computers or demo-only classes" },
      { feature: "Practice material", us: "Real portraits, products and old photos", them: "Generic sample files" },
      { feature: "Editing method", us: "Non-destructive layers and masks", them: "Quick fixes that are hard to undo" },
      { feature: "Design work", us: "Posters, banners and social sizes included", them: "Photo editing only" },
      { feature: "Feedback", us: "Trainer reviews every task", them: "Limited or none" },
      { feature: "Batch size", us: "Small batches with individual attention", them: "Large, crowded batches" },
      { feature: "Timings", us: "Morning, evening, weekend, 1-on-1", them: "Fixed single slot" },
      { feature: "Certificate", us: "Verifiable certificate + work folder", them: "Varies" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Amandeep Singh", role: "Studio Assistant · Jalandhar", text: "I used to only print photos at our studio. Now I do the retouching and album edits myself. The masks and adjustment layers module was the turning point." },
    { name: "Priya Sharma", role: "B.Com Student · Adarsh Nagar", text: "Six weeks was just right. I make posters for college events and a few posts for my uncle's shop." },
    { name: "Karanveer Singh", role: "Photographer · Kartarpur", text: "Learned to edit my own wedding shoots properly instead of relying on presets. Small batch, lots of practice." },
    { name: "Ritika Kapoor", role: "Homemaker · Model Town", text: "I restored my grandparents' old photos as my class project. The trainer was patient with every question." },
    { name: "Mandeep Kaur", role: "Social Media Designer · Phagwara", text: "The social media sizes and poster work got me a junior role at a small agency." },
    { name: "Sahil Arora", role: "Shop Owner · Rama Mandi", text: "I design my own offer posts for WhatsApp and Instagram now. Practical and straight to the point." },
  ],
  faqs: [
    { q: "Do I need any design experience?", a: "No. The course starts from the Photoshop interface. Basic computer use — mouse, keyboard and saving files — is enough." },
    { q: "What is the duration and class timing?", a: "The course runs for 1.5 months (about six weeks). Morning, afternoon, evening and weekend batches are available, plus 1-on-1 slots on request." },
    { q: "Which version of Photoshop is taught?", a: "A current version of Adobe Photoshop is installed in the lab. The skills taught work the same way across recent versions." },
    { q: "Will I get a certificate?", a: `Yes. You receive a ${site.name} certificate on completing the course and practical tasks, which can be verified online.` },
    { q: "Can I bring my own photos to practise?", a: "Yes. Once the basics are covered, trainers are happy to help you work on your own photos and studio work." },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, see the lab and meet the trainer before you decide." },
    { q: "What should I learn after this course?", a: "Adobe Illustrator or CorelDRAW, or the 4-month Graphic Design course that covers all the major design programs." },
  ],
};

const coreldraw: CourseDetail = {
  slug: "coreldraw",
  seo: {
    title: `CorelDRAW Course in ${site.city} | 1.5-Month Print, Flex & Logo Design`,
    description: `Learn CorelDRAW at ${site.name} ${site.city}: drawing tools, curves, typography, visiting cards, letterheads, brochures, flex banners, signage and print preparation, with a certificate and placement support.`,
  },
  hero: {
    crumb: "CorelDRAW",
    tag: "CorelDRAW",
    badge: "Print-Ready Files",
    title: `Best CorelDRAW Course in ${site.city}`,
    text: `Design visiting cards, flex banners, brochures, invitations and logos in CorelDRAW — the program most print shops and flex printers in Punjab run on. Taught hands-on at ${site.name} ${site.city}, with every file prepared to print correctly.`,
    points: ["Flex & signage", "Visiting cards & brochures", "Print preparation", "Certificate included"],
    facts: [
      { label: "Duration", value: "1.5 Months" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "Basic computer use" },
      { label: "Includes", value: "Certificate + print files" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "100%", label: "Practical", note: "real print jobs, every class" },
    ],
    hub: {
      center: "coreldraw.png",
      nodes: [
        { logo: "photoshop.png" },
        { logo: "illustrator.svg" },
        { logo: "indesign.svg" },
        { logo: "canva.svg" },
        { logo: "meta.svg" },
        { logo: "photoshop.png" },
        { icon: "🖨" },
        { icon: "✎" },
      ],
    },
  },
  overview: {
    eyebrow: "Course overview",
    title: "The design program behind Punjab's print shops",
    paragraphs: [
      `${site.name}'s CorelDRAW course in ${site.city} is a six-week, print-focused program for anyone who wants to design the everyday jobs that keep printers busy — visiting cards, bill books, letterheads, flex banners, shop boards and wedding cards.`,
      "You start with the drawing tools, shapes, curves and nodes, then learn text, typography, colour and fills. From week four the course is job work: cards, letterheads and brochures, then flex banners and signage at real sizes, and finally print preparation — CMYK, bleed, resolution, fonts and sending files that the printer can use without calling you back.",
      "You finish with a set of print-ready files you designed yourself, a certificate, and the skills local print shops, flex printers and DTP counters look for when they hire.",
    ],
    image: "graphic-design.webp",
    imageAlt: "Student designing a flex banner in CorelDRAW at techcadd",
    imageTag: "Designed to be printed",
    getList: [
      "Visiting cards, letterheads and bill books",
      "Flex banners and signage at real print sizes",
      "Brochures and wedding / event invitations",
      "CMYK, bleed and print file preparation",
      "Certificate + a folder of print-ready work",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "7", label: "Modules" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who can do this course",
    text: "No design background is needed. If you can use a computer, you can learn CorelDRAW — the course moves from basic shapes to real print jobs step by step.",
    items: [
      { icon: "student", title: "10th / 12th pass students", text: "A practical skill that leads straight to DTP and print design jobs in the local market." },
      { icon: "shop", title: "Print & flex shop staff", text: "Design jobs yourself instead of only operating the machine — and become more valuable to the shop." },
      { icon: "job", title: "Job seekers", text: "DTP operator and flex designer roles are steady, local and open to freshers with good samples." },
      { icon: "design", title: "Aspiring designers", text: "Add the print industry's main program to your Photoshop or Illustrator skills." },
      { icon: "freelance", title: "Freelancers", text: "Take visiting card, invitation and flex design jobs from local shops and printers." },
      { icon: "office", title: "Business owners", text: "Design your own cards, rate lists, boards and pamphlets and send them straight to the printer." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why six weeks of CorelDRAW are worth it",
    feature: {
      tag: "Access",
      title: "Timings that fit around work",
      text: `Students reach the ${site.city} centre from Basti Nau, Basti Sheikh, Rama Mandi, Maqsudan and Adarsh Nagar, with weekend learners coming in from Phagwara, Nakodar, Kapurthala and Hoshiarpur. Morning, evening, weekend and 1-on-1 slots let print shop staff learn without leaving their job.`,
      slots: ["Morning", "Afternoon", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Demand",
        title: "Print never stopped",
        text: "Shop boards, flex, cards, bill books, wedding invitations and election material — local printing work is steady all year and peaks every season.",
      },
      {
        tag: "Industry fit",
        title: "The printers' program",
        text: "Most print shops and flex printers in Punjab share files in CorelDRAW. Knowing it well means you can work with them from day one.",
      },
      {
        tag: "Method",
        title: "Designed at real sizes",
        text: "You set up flex at feet-and-inches sizes, cards at 3.5 × 2 inches and brochures with bleed — exactly as the printer needs them.",
      },
      {
        tag: "Next step",
        title: "Grows into full design",
        text: "CorelDRAW pairs naturally with Photoshop for photo work and leads into the full Graphic Design course when you are ready.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: `${site.city} prints every day. Printers need designers.`,
    points: [
      `${site.city}'s flex printers, offset presses and wedding card shops handle design jobs daily, and many struggle to find staff who can design and prepare files correctly.`,
      "Sports goods and export houses in the city need catalogues, labels and cartons designed for print, often in CorelDRAW.",
      "Fresher DTP operators and flex designers in Punjab usually start around ₹10,000 – ₹16,000 a month, with more for faster, experienced designers.",
    ],
    panel: [
      { k: "Flex & boards", v: "Shops, events, elections" },
      { k: "Stationery", v: "Cards, letterheads, bills" },
      { k: "Invitations", v: "Weddings & functions" },
      { k: "Catalogues & labels", v: "Exporters & manufacturers" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, week by week",
    text: "Three weeks of core tools, then three weeks of real print jobs — ending with how to prepare files that print correctly the first time.",
    phases: [
      {
        id: "01",
        name: "Interface & Drawing Tools",
        weeks: "Week 1",
        summary: "Get comfortable with CorelDRAW's workspace and basic tools.",
        topics: [
          "Workspace, page setup, units and rulers",
          "Rectangle, ellipse, polygon and freehand tools",
          "Selecting, grouping, aligning and distributing",
          "Saving CDR files and working with versions",
        ],
        outcome: "Set up a correctly sized document and lay out basic shapes",
      },
      {
        id: "02",
        name: "Shapes, Curves & Nodes",
        weeks: "Week 2",
        summary: "Draw any shape precisely.",
        topics: [
          "Converting to curves and editing nodes",
          "Bezier and Pen tools",
          "Weld, trim, intersect and combine",
          "Tracing a logo from a sketch or image",
        ],
        outcome: "A clean vector redraw of a simple logo",
      },
      {
        id: "03",
        name: "Text, Typography, Colour & Fills",
        weeks: "Week 3",
        summary: "Make layouts readable and colours print true.",
        topics: [
          "Artistic and paragraph text, fitting text to path",
          "Font pairing, spacing and Punjabi / Hindi fonts",
          "CMYK colour, palettes and spot colours",
          "Fountain fills, patterns, transparency and outlines",
        ],
        outcome: "A rate list or notice with clear typography",
      },
      {
        id: "04",
        name: "Visiting Cards, Letterheads & Brochures",
        weeks: "Week 4",
        summary: "Design the stationery every business orders.",
        topics: [
          "Visiting cards, front and back",
          "Letterheads, envelopes and bill books",
          "Tri-fold brochures and pamphlets",
          "Wedding and event invitation layouts",
        ],
        outcome: "A stationery set and an invitation card",
      },
      {
        id: "05",
        name: "Flex, Banners & Signage",
        weeks: "Week 5",
        summary: "Design big, readable work at real print sizes.",
        topics: [
          "Setting up flex in feet and inches",
          "Readability from a distance, contrast and hierarchy",
          "Shop boards, standees and event backdrops",
          "Placing and preparing photos from Photoshop",
        ],
        outcome: "A shop flex board and an event banner",
      },
      {
        id: "06",
        name: "Print Preparation",
        weeks: "Week 6",
        summary: "Send files the printer can use without calling you back.",
        topics: [
          "Bleed, safe margins and crop marks",
          "Image resolution for offset vs flex",
          "Converting text to curves and checking fonts",
          "Exporting PDF, JPG and TIFF for printers, imposition basics",
        ],
        outcome: "A checked, print-ready file set for every project",
      },
    ],
  },
  tools: {
    eyebrow: "Software you will use",
    title: "CorelDRAW and the print workflow around it",
    text: "Everything below is used in class on your own lab computer.",
    tools: [
      { name: "CorelDRAW", logo: "coreldraw.png", use: "Layouts, logos & print jobs" },
      { name: "Corel PHOTO-PAINT", mono: "PP", use: "Quick photo fixes" },
      { name: "Photoshop", logo: "photoshop.png", use: "Preparing photos for print" },
      { name: "PDF Export & Check", mono: "PDF", use: "Print-ready files for printers" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Get certified in CorelDRAW",
    text: `Finish the course and your print projects to receive a ${site.name} certificate you can show to any print shop or employer — verifiable online.`,
    courseName: "CorelDRAW",
    items: [
      { title: "Course certificate", text: "Verifiable online by any employer" },
      { title: "Print-ready samples", text: "Cards, flex, brochure and invitation" },
      { title: "Print preparation skills", text: "Bleed, CMYK and export done correctly" },
      { title: "Placement support", text: "Work samples, interviews and job updates" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where this course takes you",
    text: "Indicative starting pay for freshers in Punjab. Actual offers depend on the employer, your speed and your work samples.",
    roles: [
      { title: "DTP Operator", pay: "₹10k – 16k", text: "Printing presses, publishers and DTP counters" },
      { title: "Print Designer", pay: "₹10k – 18k", text: "Offset presses, card shops and packaging units" },
      { title: "Flex Designer", pay: "₹10k – 15k", text: "Flex printers, sign makers and ad boards" },
      { title: "Catalogue / Label Designer", pay: "₹12k – 18k", text: "In-house roles at manufacturers and export houses" },
    ],
    hiring: ["Flex & sign printers", "Offset printing presses", "Wedding card shops", "Sports goods & export houses", "Packaging units", "Advertising agencies"],
    qa: [
      {
        q: "Is CorelDRAW still used?",
        a: "Yes, very widely in Punjab's print trade. Most flex printers, card shops and DTP counters exchange files in CorelDRAW, which is why local demand stays steady.",
      },
      {
        q: "Can I get a job with only CorelDRAW?",
        a: "Yes, DTP and flex design jobs often ask mainly for CorelDRAW. Adding Photoshop makes you stronger, since many print jobs include photos.",
      },
      {
        q: "Can I do freelance print design?",
        a: "Some students design cards, invitations and flex for local shops and printers on a per-job basis. Earnings vary, so it usually starts as extra income.",
      },
      {
        q: "What should I learn after this?",
        a: "Adobe Photoshop is the most useful next step. The 4-month Graphic Design course adds Illustrator, InDesign, branding and a full portfolio.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real print jobs you will complete",
    text: "Each project is the kind of job a print shop gets every week, finished and prepared exactly as it would be sent to print.",
    items: [
      { n: "01", title: "Logo & visiting card", text: "Draw a simple logo and design a double-sided visiting card for a local business.", tags: ["Logo", "Stationery"] },
      { n: "02", title: "Shop flex board", text: "Design a readable shop board at real size with contact details, photos and offers.", tags: ["Flex", "Signage"] },
      { n: "03", title: "Tri-fold brochure", text: "Lay out a tri-fold brochure for a school, clinic or coaching centre with correct folds and bleed.", tags: ["Brochure", "Print"] },
      { n: "04", title: "Wedding invitation", text: "Design an invitation card with English and Punjabi text, ready for the printer.", tags: ["Invitation", "Typography"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "See it. Design it. Print it.",
    text: "Every topic ends with a file that could go straight to a printer.",
    steps: [
      { title: "See it", text: "The trainer demonstrates one technique on the big screen using a real print job.", example: "Setting up a 6 × 3 ft flex" },
      { title: "Design it", text: "You create your own version while the trainer checks your screen.", example: "Laying out the shop board" },
      { title: "Print it", text: "You prepare and check the file for printing, as you would for a client.", example: "Bleed, curves and PDF export" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name}`,
    text: `Many people in ${site.city} learn CorelDRAW informally at a shop counter. A proper course means you learn the tools fully, the right way to prepare files, and have a certificate to show for it.`,
    items: [
      { title: "Print-focused trainers", text: "Taught with the sizes, colours and file checks real printers need." },
      { title: "One student, one computer", text: "Every minute of lab time is spent designing on your own machine." },
      { title: "Small batches", text: "Small enough that the trainer checks your file every class." },
      { title: "Punjabi text included", text: "Gurmukhi and Hindi fonts for invitations, boards and notices." },
      { title: "Placement support", text: "Work samples, mock interviews and job drives with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any CorelDRAW course, including this one.",
    rows: [
      { feature: "Practice time", us: "One computer per student, every class", them: "Shared computers or learning at a shop counter" },
      { feature: "Projects", us: "Cards, flex, brochures and invitations", them: "Random practice files" },
      { feature: "Print preparation", us: "Bleed, CMYK, curves and PDF export", them: "Rarely taught properly" },
      { feature: "Punjabi fonts", us: "Gurmukhi and Hindi text covered", them: "Often skipped" },
      { feature: "Feedback", us: "Trainer checks every file", them: "Limited or none" },
      { feature: "Batch size", us: "Small batches with individual attention", them: "Large, crowded batches" },
      { feature: "Timings", us: "Morning, evening, weekend, 1-on-1", them: "Fixed single slot" },
      { feature: "Certificate", us: "Verifiable certificate + print samples", them: "Varies or none" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Lovepreet Singh", role: "Flex Designer · Jalandhar", text: "I was running the flex machine and wanted to design too. After this course the shop gives me the design work, and I learned why files were printing wrong before." },
    { name: "Pooja Rani", role: "DTP Operator · Basti Sheikh", text: "The visiting card and brochure projects were exactly the work I now do at a press. Clear, practical teaching." },
    { name: "Harjit Singh", role: "Card Shop Owner · Rama Mandi", text: "I design my own wedding cards in Punjabi and English now. The print preparation week saved me a lot of reprints." },
    { name: "Anmol Sharma", role: "12th Pass · Nakodar", text: "Weekend batch, small group. Got a job at a printing press within a month of finishing." },
    { name: "Kuldeep Kaur", role: "Freelancer · Kapurthala", text: "I take card and invitation jobs from two local printers. The trainer helped me build a good sample set." },
    { name: "Vikas Kumar", role: "In-house Designer · Basti Nau", text: "Needed CorelDRAW for catalogues and cartons at a sports goods unit. The course covered exactly that." },
  ],
  faqs: [
    { q: "Do I need any design experience?", a: "No. The course starts from the CorelDRAW workspace and basic shapes. Basic computer use is enough." },
    { q: "What is the duration and class timing?", a: "The course runs for 1.5 months (about six weeks). Morning, afternoon, evening and weekend batches are available, plus 1-on-1 slots on request." },
    { q: "Will I learn Punjabi text in CorelDRAW?", a: "Yes. Using Gurmukhi and Hindi fonts for invitations, boards and notices is part of the typography module." },
    { q: "Will I get a certificate?", a: `Yes. You receive a ${site.name} certificate on completing the course and print projects, which can be verified online.` },
    { q: "Will I learn how to send files to a printer?", a: "Yes. The final week covers bleed, CMYK, resolution, converting text to curves and exporting files printers can use directly." },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, see the lab and meet the trainer before you decide." },
    { q: "What should I learn after this course?", a: "Adobe Photoshop for photo work, or the 4-month Graphic Design course, which adds Illustrator, InDesign and a full portfolio." },
  ],
};

const illustrator: CourseDetail = {
  slug: "adobe-illustrator",
  seo: {
    title: `Adobe Illustrator Course in ${site.city} | 1.5-Month Logo & Vector Design`,
    description: `Learn Adobe Illustrator at ${site.name} ${site.city}: vector basics, the Pen tool, Shape Builder, typography, logo design, icons, illustration and exporting for print and web, with a certificate and placement support.`,
  },
  hero: {
    crumb: "Adobe Illustrator",
    tag: "Adobe Illustrator",
    badge: "Vector Logos",
    title: `Best Adobe Illustrator Course in ${site.city}`,
    text: `Create logos, icons, illustrations and brand artwork that stay sharp at any size — from a visiting card to a hoarding. Taught hands-on at ${site.name} ${site.city}, with the Pen tool practised until it feels natural.`,
    points: ["Pen tool mastery", "Logo design", "Icons & illustration", "Certificate included"],
    facts: [
      { label: "Duration", value: "1.5 Months" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "Basic computer use" },
      { label: "Includes", value: "Certificate + vector files" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "100%", label: "Practical", note: "design every class" },
    ],
    hub: {
      center: "illustrator.svg",
      nodes: [
        { logo: "photoshop.png" },
        { logo: "indesign.svg" },
        { logo: "coreldraw.png" },
        { logo: "canva.svg" },
        { logo: "meta.svg" },
        { logo: "indesign.svg" },
        { icon: "✒" },
        { icon: "◆" },
      ],
    },
  },
  overview: {
    eyebrow: "Course overview",
    title: "Logos and vector artwork that scale to any size",
    paragraphs: [
      `${site.name}'s Adobe Illustrator course in ${site.city} is a six-week program for anyone who wants to design logos, icons and illustrations — the clean, scalable artwork that sits at the centre of every brand.`,
      "You begin with how vectors work, artboards and basic shapes, then spend a full week on the Pen tool, the skill that separates beginners from designers. Shape Builder, Pathfinder and typography follow, and then you put it all together: logo design from sketch to final files, icons and simple illustrations, and exporting correctly for print and web.",
      "You finish with a set of logos, an icon set and illustrations in proper vector formats, a certificate, and a strong base for the full Graphic Design course or freelance logo work.",
    ],
    image: "graphic-design.webp",
    imageAlt: "Student drawing a vector logo in Adobe Illustrator at techcadd",
    imageTag: "Sharp at every size",
    getList: [
      "The Pen tool, practised until it is second nature",
      "Logo design from brief and sketch to final files",
      "Icons, patterns and simple illustrations",
      "Typography and custom lettering for logos",
      "Certificate + a folder of vector work",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "7", label: "Modules" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who can do this course",
    text: "You do not need to draw well by hand. Illustrator is about precise shapes and clean lines, which you learn step by step on the computer.",
    items: [
      { icon: "student", title: "College students", text: "Learn the logo and branding tool used by agencies — a strong skill to build a portfolio around." },
      { icon: "design", title: "Photoshop & Canva users", text: "Move from editing and templates to creating original, scalable artwork of your own." },
      { icon: "freelance", title: "Freelancers", text: "Logo and icon design are among the most common small design jobs clients ask for." },
      { icon: "shop", title: "Print & studio staff", text: "Redraw client logos cleanly so they print sharp on flex, cards and merchandise." },
      { icon: "office", title: "Business & marketing teams", text: "Create and edit brand assets in-house instead of waiting on an outside designer." },
      { icon: "grad", title: "Fine arts & design students", text: "Turn hand sketches and illustrations into digital vector artwork." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why six weeks of Illustrator are worth it",
    feature: {
      tag: "Access",
      title: "Timings that fit your day",
      text: `Students reach the ${site.city} centre from Model Town, Urban Estate, Lajpat Nagar, Garha and Jalandhar Cantt, with weekend learners coming in from Phagwara, Hoshiarpur, Kapurthala and Adampur. Morning, evening, weekend and 1-on-1 slots mean college or a job can carry on while you learn.`,
      slots: ["Morning", "Afternoon", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Demand",
        title: "Every brand starts with a logo",
        text: "New shops, startups, coaching centres and exporters all need a logo — and a clean vector version for every place it will be printed.",
      },
      {
        tag: "Method",
        title: "Pen tool, properly",
        text: "A full week is spent on the Pen tool and curves, so you can draw any shape precisely instead of relying on templates.",
      },
      {
        tag: "Quality",
        title: "Scales to any size",
        text: "Vector files print sharp on a visiting card, a T-shirt, a product box or a 20-foot hoarding — the reason agencies insist on Illustrator.",
      },
      {
        tag: "Next step",
        title: "The core of brand design",
        text: "Illustrator leads naturally into brand identity, packaging and the full Graphic Design course.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Brands need clean vector artwork, everywhere",
    points: [
      "New businesses need a logo before they open — and a vector version for flex, cards, uniforms and social media.",
      `${site.city}'s sports goods and export houses need logos, labels, icons and product artwork prepared to print on apparel, balls and packaging.`,
      "Fresher logo and graphic designers in Punjab usually start around ₹12,000 – ₹20,000 a month, and a strong logo portfolio makes a clear difference.",
    ],
    panel: [
      { k: "Logos", v: "New shops & startups" },
      { k: "Brand assets", v: "Cards, uniforms, merch" },
      { k: "Icons", v: "Apps, websites, menus" },
      { k: "Product artwork", v: "Labels & packaging" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, week by week",
    text: "Seven modules across six weeks — core vector skills first, then logos, icons and illustration, ending with exporting files the right way.",
    phases: [
      {
        id: "01",
        name: "Vector Basics & Artboards",
        weeks: "Week 1",
        summary: "Understand how vector design works.",
        topics: [
          "Vector vs raster, and when to use each",
          "Workspace, artboards and document setup",
          "Shapes, fills, strokes and colour swatches",
          "Selection, direct selection, align and arrange",
        ],
        outcome: "A multi-artboard layout built from basic shapes",
      },
      {
        id: "02",
        name: "Pen Tool Mastery",
        weeks: "Week 2",
        summary: "Draw any shape precisely with curves and anchor points.",
        topics: [
          "Straight lines, curves and anchor points",
          "Editing handles and smoothing paths",
          "Tracing sketches and existing logos",
          "Curvature tool and shortcuts for speed",
        ],
        outcome: "A clean vector trace of a hand-drawn sketch",
      },
      {
        id: "03",
        name: "Shape Builder, Pathfinder & Typography",
        weeks: "Week 3",
        summary: "Build complex shapes and work with type.",
        topics: [
          "Shape Builder and Pathfinder operations",
          "Type tools, type on a path and outlines",
          "Font pairing, kerning and custom lettering",
          "Gradients and simple patterns",
        ],
        outcome: "A wordmark with custom-adjusted lettering",
      },
      {
        id: "04",
        name: "Logo Design",
        weeks: "Week 4",
        summary: "Design a logo from brief to final versions.",
        topics: [
          "Understanding the brief and research",
          "Sketching concepts and choosing a direction",
          "Grids, proportions and colour choices",
          "Colour, black-and-white and horizontal / stacked versions",
        ],
        outcome: "A finished logo with all its variations",
      },
      {
        id: "05",
        name: "Icons & Illustrations",
        weeks: "Week 5",
        summary: "Draw consistent icons and simple illustrations.",
        topics: [
          "Icon grids and consistent stroke styles",
          "Flat illustration and simple characters",
          "Image Trace and cleaning up traced artwork",
          "Patterns for packaging and backgrounds",
        ],
        outcome: "A matching 12-icon set and one illustration",
      },
      {
        id: "06",
        name: "Exporting for Print & Web",
        weeks: "Week 6",
        summary: "Deliver the right file for every use.",
        topics: [
          "CMYK vs RGB and spot colours",
          "AI, EPS, PDF, SVG and PNG exports",
          "Asset Export for social media and web",
          "Packaging files and a simple brand sheet for clients",
        ],
        outcome: "A complete, correctly exported logo file pack",
      },
    ],
  },
  tools: {
    eyebrow: "Software you will use",
    title: "Illustrator and the tools around it",
    text: "Everything below is used in class on your own lab computer.",
    tools: [
      { name: "Illustrator", logo: "illustrator.svg", use: "Logos, icons & vector art" },
      { name: "Photoshop", logo: "photoshop.png", use: "Logo mockups & presentation" },
      { name: "InDesign", logo: "indesign.svg", use: "Simple brand sheet layout" },
      { name: "Adobe Fonts", mono: "Af", use: "Licensed fonts for logos" },
      { name: "Adobe Color", mono: "Co", use: "Building colour palettes" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Get certified in Adobe Illustrator",
    text: `Finish the course and your practical projects to receive a ${site.name} certificate you can attach to any job application — verifiable online.`,
    courseName: "Adobe Illustrator",
    items: [
      { title: "Course certificate", text: "Verifiable online by any employer" },
      { title: "Logo portfolio", text: "Logos with full variations, designed by you" },
      { title: "Vector file pack", text: "AI, PDF, SVG and PNG exports done correctly" },
      { title: "Placement support", text: "Portfolio help and job updates" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where this course takes you",
    text: "Indicative starting pay for freshers in Punjab. Actual offers depend on the employer, your portfolio and how you interview.",
    roles: [
      { title: "Logo Designer", pay: "₹12k – 20k", text: "Agencies, branding studios and print shops" },
      { title: "Illustrator", pay: "₹12k – 22k", text: "Packaging, apparel prints and publishing" },
      { title: "Graphic Designer", pay: "₹12k – 20k", text: "In-house and agency roles, usually with Photoshop too" },
      { title: "Apparel / Label Artist", pay: "₹12k – 18k", text: "Sports goods, garment and export units" },
    ],
    hiring: ["Branding & ad agencies", "Sports goods & export houses", "Garment & print-on-demand units", "Packaging companies", "Printing presses", "Startups & local brands"],
    qa: [
      {
        q: "Do I need to be good at drawing?",
        a: "No. Illustrator is about precise shapes and lines made with the mouse. Sketching ideas on paper helps, but rough sketches are enough.",
      },
      {
        q: "Illustrator or CorelDRAW — which should I learn?",
        a: "Agencies and brands mostly use Illustrator; local print shops mostly use CorelDRAW. Many designers learn both, and the skills transfer easily between them.",
      },
      {
        q: "Can I earn from logo design?",
        a: "Logo design is a common freelance job, but local rates vary widely and new designers usually start with small projects. A good portfolio matters more than the number of logos.",
      },
      {
        q: "What should I learn after this?",
        a: "Adobe Photoshop is the usual next step. The 4-month Graphic Design course adds Photoshop, CorelDRAW, InDesign, branding and packaging.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real projects you will complete",
    text: "Each module ends with a task you finish on your own. Together they become your vector portfolio.",
    items: [
      { n: "01", title: "Logo & brand identity", text: "Design a logo for a local business brief, with colour, mono and stacked versions and a card mockup.", tags: ["Logo", "Branding"] },
      { n: "02", title: "Icon set", text: "Draw a consistent 12-icon set for a restaurant menu, website or app.", tags: ["Icons", "Grids"] },
      { n: "03", title: "Sports apparel artwork", text: "Design a team logo or jersey graphic ready for printing on apparel.", tags: ["Illustration", "Print"] },
      { n: "04", title: "Social post & label", text: "Use your logo and icons in a social media post and a product label, exported correctly for each.", tags: ["Export", "Social"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "See it. Draw it. Own it.",
    text: "Every technique follows the same three steps, so nothing is left as theory.",
    steps: [
      { title: "See it", text: "The trainer demonstrates one technique slowly on the big screen.", example: "Drawing a curve with the Pen tool" },
      { title: "Draw it", text: "You repeat it on your own computer while the trainer checks your paths.", example: "Tracing a logo sketch" },
      { title: "Own it", text: "A short task at the end proves you can do it on a new shape without help.", example: "Drawing your own icon" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name}`,
    text: `The Pen tool is where most self-taught learners give up. In a small ${site.city} batch, a trainer watches your paths and corrects them until it clicks.`,
    items: [
      { title: "Trainers who check your paths", text: "Feedback on anchor points, curves and spacing — the details that make a logo look professional." },
      { title: "One student, one computer", text: "Every minute of lab time is spent drawing on your own machine." },
      { title: "Small batches", text: "Small enough that the trainer sees your screen every class." },
      { title: "Brief-based logo work", text: "Logos designed from a real brief, not copied from the internet." },
      { title: "Placement support", text: "Portfolio help, mock interviews and job drives with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any Illustrator course, including this one.",
    rows: [
      { feature: "Practice time", us: "One computer per student, every class", them: "Shared computers or demo-only classes" },
      { feature: "Pen tool", us: "A full week of guided practice", them: "Covered in one class" },
      { feature: "Logo design", us: "From brief and sketch to final variations", them: "Copying existing logos" },
      { feature: "Exporting", us: "Print and web formats done correctly", them: "Rarely covered" },
      { feature: "Feedback", us: "Trainer reviews every task", them: "Limited or none" },
      { feature: "Batch size", us: "Small batches with individual attention", them: "Large, crowded batches" },
      { feature: "Timings", us: "Morning, evening, weekend, 1-on-1", them: "Fixed single slot" },
      { feature: "Certificate", us: "Verifiable certificate + vector portfolio", them: "Varies" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Gagandeep Singh", role: "Logo Designer · Jalandhar", text: "I kept giving up on the Pen tool with YouTube. A week of guided practice here and it finally made sense." },
    { name: "Ishita Malhotra", role: "BFA Student · Model Town", text: "I can now turn my sketches into clean vector illustrations. The icon project was my favourite." },
    { name: "Raman Kumar", role: "Print Shop · Garha", text: "Customers bring blurry logos all the time. Now I redraw them properly in Illustrator and they print sharp." },
    { name: "Tanvir Kaur", role: "Freelancer · Phagwara", text: "The logo module taught me to work from a brief and show variations. My first small clients came from people I knew." },
    { name: "Arshdeep Singh", role: "Apparel Artist · Basti Nau", text: "I work on jersey and team logo artwork for a sports goods unit. The course was very practical for that." },
    { name: "Mehak Bansal", role: "Marketing Executive · Urban Estate", text: "Evening batch fit my job. I make our brand graphics myself now instead of waiting for the agency." },
  ],
  faqs: [
    { q: "Do I need any design experience?", a: "No. The course starts from how vectors work and the Illustrator workspace. Basic computer use is enough." },
    { q: "What is the duration and class timing?", a: "The course runs for 1.5 months (about six weeks). Morning, afternoon, evening and weekend batches are available, plus 1-on-1 slots on request." },
    { q: "Do I need a drawing tablet?", a: "No. Everything in the course is done with a mouse. A tablet can help for illustration later but is not needed." },
    { q: "Will I get a certificate?", a: `Yes. You receive a ${site.name} certificate on completing the course and practical projects, which can be verified online.` },
    { q: "Should I learn Photoshop first?", a: "It is not required. Many students start with Illustrator; others add it after Photoshop. The skills complement each other either way." },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, see the lab and meet the trainer before you decide." },
    { q: "What should I learn after this course?", a: "Adobe Photoshop, or the 4-month Graphic Design course, which adds Photoshop, CorelDRAW, InDesign, branding and packaging." },
  ],
};

export const graphicDesign: CourseDetail[] = [graphicDesignCourse, photoshop, coreldraw, illustrator];
