// Course pages for MS Office & Advanced Excel, DCA and ADCA. See ./types.ts for what each field is.
import { site } from "../site";
import type { CourseDetail } from "./types";

const msOfficeAdvancedExcel: CourseDetail = {
  slug: "advanced-excel-training-in-jalandhar",
  seo: {
    title: `MS Office & Advanced Excel Course in ${site.city} | 2-Month MIS Program`,
    description: `Learn Word, PowerPoint and Advanced Excel at ${site.name} ${site.city}: XLOOKUP, INDEX-MATCH, pivot tables, dashboards, MIS reports and macro basics, with a certificate and placement support.`,
  },
  hero: {
    crumb: "MS Office & Advanced Excel",
    tag: "Advanced Excel",
    badge: "MIS Ready",
    title: `Best MS Office & Advanced Excel Course in ${site.city}`,
    text: `Learn Excel the way offices actually use it — lookups, pivot tables, clean data and one-click MIS reports — plus professional Word documents and business presentations, built on real sample data in the ${site.name} ${site.city} lab.`,
    points: ["Real business datasets", "Lookups & pivot tables", "MIS dashboards", "Certificate included"],
    facts: [
      { label: "Duration", value: "2 Months" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "Basic computer use" },
      { label: "Includes", value: "Certificate + Excel templates" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "8", label: "Modules", note: "from formulas to macros" },
    ],
    hub: {
      center: "excel.png",
      nodes: [
        { logo: "word.png" },
        { logo: "powerpoint.svg" },
        { logo: "outlook.svg" },
        { logo: "excel.png" },
        { logo: "google-workspace.svg" },
        { logo: "windows.svg" },
        { icon: "📊" },
        { icon: "∑" },
      ],
    },
  },
  overview: {
    eyebrow: "Course overview",
    title: "From typing numbers into cells to building reports people rely on",
    paragraphs: [
      `${site.name}'s MS Office & Advanced Excel course in ${site.city} is for people who can already use a computer but want to be the person in the office who handles the data — the one who can merge two lists, find the mismatch, and send a clean monthly report before lunch.`,
      "The first week tightens up Word: styles, tables, mail merge and documents that look like they came from a proper office. The bulk of the course is Excel — formulas and named ranges, VLOOKUP, XLOOKUP and INDEX-MATCH, conditional formatting, data validation, pivot tables and pivot charts — ending in dashboards and MIS reports built from sales, attendance and stock data. The last weeks cover recording simple macros, business presentations in PowerPoint and handling reports over Outlook.",
      "Every module uses realistic sample files — a sales register, a staff attendance sheet, a stock list — so by the end you have a set of working templates and a small MIS dashboard you can show in an interview.",
    ],
    image: "ms-office-excel.webp",
    imageAlt: "Student building an Excel pivot table in the techcadd lab",
    imageTag: "Built on real business data",
    getList: [
      "One computer per student, every class",
      "Practice workbooks with sales, stock and attendance data",
      "Formula cheat-sheet and shortcut list",
      "Ready-to-use Excel and Word templates",
      "Certificate + your own MIS dashboard",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "8", label: "Modules" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who this course is for",
    text: "You should be comfortable with a mouse, keyboard and saving files. Beyond that, what matters is working with data every day of the course — no maths degree required.",
    items: [
      { icon: "grad", title: "Graduates (B.Com, BBA, BA)", text: "Add the Excel skills that back-office, MIS and accounts job ads ask for by name." },
      { icon: "job", title: "Job seekers", text: "Clear the Excel test that many office interviews now include — lookups and pivots are the usual questions." },
      { icon: "office", title: "Working office staff", text: "Stop spending hours on reports that a pivot table or XLOOKUP can finish in minutes." },
      { icon: "chart", title: "Sales & accounts teams", text: "Track targets, collections and stock with formulas and dashboards instead of manual totals." },
      { icon: "shop", title: "Business owners", text: "Understand your own sales, expenses and stock numbers without waiting for someone else's report." },
      { icon: "student", title: "College students", text: "Handle project data, surveys and presentations properly — and have a skill on your resume before you graduate." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why two months of Excel pay off for years",
    feature: {
      tag: "Access",
      title: "Batches around your work hours",
      text: `Many students in this course already work, so we run early-morning, evening and weekend batches alongside regular daytime slots. Learners come from Model Town, Urban Estate, Rama Mandi and the industrial areas, with weekend students travelling in from Phagwara, Kapurthala and Nakodar. 1-on-1 slots are available for staff who need to fit around office timings.`,
      slots: ["Morning", "Afternoon", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Demand",
        title: "Excel is on every office job ad",
        text: "Back office, MIS, accounts, sales coordination and HR roles all list \"good knowledge of Excel\" — and interviews increasingly test it on a computer.",
      },
      {
        tag: "Method",
        title: "Messy data, not textbook examples",
        text: "You practise on files with duplicates, blanks and spelling mismatches, because that is what real office data looks like.",
      },
      {
        tag: "Speed",
        title: "Hours of work in minutes",
        text: "A report that takes a full afternoon by hand is a refresh of a pivot table once you know how. That is the difference employers notice.",
      },
      {
        tag: "Next step",
        title: "A base for accounts or analytics",
        text: "Strong Excel makes Tally Prime with GST, accounts roles and later data analysis far easier to pick up.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Every business runs on spreadsheets. Few people use them well.",
    points: [
      "Small and mid-sized firms in Punjab track sales, stock, attendance and dispatch in Excel — and need someone who can report on it.",
      "Entry-level MIS and back-office roles in Punjab typically start around ₹10,000 – ₹20,000 a month, with Excel as the deciding skill.",
      "Eight weeks of focused practice covers the functions used in the large majority of day-to-day office reports.",
    ],
    panel: [
      { k: "Lookups", v: "Matching two lists" },
      { k: "Pivot tables", v: "Monthly summaries" },
      { k: "Dashboards", v: "MIS reporting" },
      { k: "Word & PPT", v: "Letters and reviews" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, week by week",
    text: "One short Word refresher, six weeks of Excel from formulas to automation, then presentations and reporting — the order in which an office actually uses these tools.",
    phases: [
      {
        id: "01",
        name: "Professional Documents in Word",
        weeks: "Week 1",
        summary: "Make documents that look consistent and are quick to update.",
        topics: [
          "Styles, headings and automatic table of contents",
          "Tables, section breaks, headers and footers",
          "Mail merge for letters and certificates",
          "Templates, track changes and PDF export",
        ],
        outcome: "A company letterhead template and a mail-merged letter set",
      },
      {
        id: "02",
        name: "Excel Formulas, Functions & Named Ranges",
        weeks: "Week 2",
        summary: "Build the formula habits everything else depends on.",
        topics: [
          "Relative, absolute and mixed references",
          "IF, AND, OR, IFERROR and nested logic",
          "SUMIFS, COUNTIFS, AVERAGEIFS",
          "Text and date functions, named ranges and Excel tables",
        ],
        outcome: "A salary and attendance calculator driven entirely by formulas",
      },
      {
        id: "03",
        name: "VLOOKUP, XLOOKUP & INDEX-MATCH",
        weeks: "Week 3",
        summary: "Pull matching data from one sheet into another without copy-paste.",
        topics: [
          "VLOOKUP and HLOOKUP, exact vs approximate match",
          "XLOOKUP with default values and reverse search",
          "INDEX-MATCH for two-way lookups",
          "Finding missing and duplicate records between lists",
        ],
        outcome: "Reconcile a price list against an order sheet in minutes",
      },
      {
        id: "04",
        name: "Conditional Formatting & Data Validation",
        weeks: "Week 4",
        summary: "Make sheets that flag problems and resist wrong entries.",
        topics: [
          "Highlight rules, data bars and colour scales",
          "Formula-based conditional formatting",
          "Drop-down lists and dependent drop-downs",
          "Input rules, error messages and sheet protection",
        ],
        outcome: "A data-entry form sheet that only accepts valid entries",
      },
      {
        id: "05",
        name: "Pivot Tables & Pivot Charts",
        weeks: "Week 5",
        summary: "Summarise thousands of rows in a few clicks.",
        topics: [
          "Cleaning data before a pivot: blanks, duplicates, text to columns",
          "Pivot tables with grouping by month, region and product",
          "Calculated fields, slicers and timelines",
          "Pivot charts and refreshing with new data",
        ],
        outcome: "Month-wise and region-wise sales summary from a raw register",
      },
      {
        id: "06",
        name: "Dashboards & MIS Reports",
        weeks: "Week 6",
        summary: "Turn summaries into a one-page report a manager can read.",
        topics: [
          "Choosing the right chart for the data",
          "KPI cards, slicer-driven dashboards",
          "Daily, weekly and monthly MIS formats",
          "Printing, page setup and sharing as PDF",
        ],
        outcome: "An interactive sales MIS dashboard",
      },
      {
        id: "07",
        name: "Macros Basics",
        weeks: "Week 7",
        summary: "Automate the repetitive steps you do every day.",
        topics: [
          "Recording and running a macro",
          "Relative vs absolute recording",
          "Assigning macros to buttons, saving as .xlsm",
          "Reading and editing simple recorded VBA",
        ],
        outcome: "A one-click macro that formats a daily report",
      },
      {
        id: "08",
        name: "Business Presentations & Outlook",
        weeks: "Week 8",
        summary: "Present your numbers clearly and send them professionally.",
        topics: [
          "Slide masters, layouts and consistent design",
          "Linking Excel charts into PowerPoint",
          "Presenting a monthly review",
          "Outlook: formal email, attachments, calendar and rules",
        ],
        outcome: "A monthly review deck built on your own dashboard",
      },
    ],
  },
  tools: {
    eyebrow: "Software you will use",
    title: "The Office tools every desk uses",
    text: "All software is installed on every lab computer. You work in it yourself from the first class.",
    tools: [
      { name: "MS Excel", logo: "excel.png", use: "Formulas, pivots, dashboards" },
      { name: "MS Word", logo: "word.png", use: "Letters, templates, mail merge" },
      { name: "PowerPoint", logo: "powerpoint.svg", use: "Business presentations" },
      { name: "Outlook", logo: "outlook.svg", use: "Email, calendar, reports" },
      { name: "VBA Editor", mono: "VBA", use: "Recorded macros" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Get certified in MS Office & Advanced Excel",
    text: "Complete the course and your practical assignments to receive a techcadd certificate you can attach to job applications — verifiable online.",
    courseName: "MS Office & Advanced Excel",
    items: [
      { title: "Course certificate", text: "Verifiable online by employers" },
      { title: "MIS dashboard", text: "A working dashboard to show in interviews" },
      { title: "Template set", text: "Excel and Word templates you built" },
      { title: "Placement support", text: "Resume help and Excel interview practice" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where Advanced Excel takes you",
    text: "Indicative starting pay for entry-level roles in Punjab. Actual offers depend on the employer, your Excel test in the interview and prior experience.",
    roles: [
      { title: "MIS Executive", pay: "₹12k – 20k", text: "Daily and monthly reports for sales, production or HR" },
      { title: "Back Office Executive", pay: "₹10k – 16k", text: "Records, reconciliations and data updates" },
      { title: "Office Coordinator", pay: "₹11k – 18k", text: "Documents, schedules, reports and follow-ups" },
      { title: "Data Entry Operator", pay: "₹9k – 14k", text: "Accurate entry and cleaning of business data" },
    ],
    hiring: ["Manufacturing & export units", "Distributors & wholesalers", "Hospitals & diagnostic labs", "CA & tax offices", "Schools & colleges", "Showrooms & dealerships"],
    qa: [
      {
        q: "What jobs can I get after Advanced Excel?",
        a: "MIS executive, back office executive, office coordinator and data entry roles are the common starting points. Excel also strengthens applications for accounts and sales coordination jobs.",
      },
      {
        q: "Do interviews really test Excel?",
        a: "Many do. Typical tasks are a VLOOKUP or XLOOKUP between two sheets, a pivot table summary or a SUMIFS. We practise exactly these in class.",
      },
      {
        q: "Is this useful if I already have a job?",
        a: "Yes. Most working students join to cut the time they spend on reports. Lookups, pivots and simple macros save hours every week.",
      },
      {
        q: "What should I learn after this?",
        a: "Tally Prime with GST is a natural next step for accounts roles. If you want broader computer skills with a diploma, ADCA includes Advanced Excel along with accounting and design.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real files you will build",
    text: "Each project uses a realistic dataset and is checked by your trainer before you move on.",
    items: [
      { n: "01", title: "Sales MIS dashboard", text: "Clean a raw sales register, summarise it with pivot tables and build a one-page dashboard with slicers.", tags: ["Pivot tables", "Dashboard"] },
      { n: "02", title: "Payroll & attendance sheet", text: "Calculate working days, overtime and deductions with SUMIFS, IF and date functions.", tags: ["Formulas", "Named ranges"] },
      { n: "03", title: "Stock reconciliation", text: "Match a purchase list against stock records with XLOOKUP and flag mismatches with conditional formatting.", tags: ["XLOOKUP", "Formatting"] },
      { n: "04", title: "Monthly review presentation", text: "Present your dashboard findings in a clean PowerPoint deck with linked Excel charts.", tags: ["PowerPoint", "Charts"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "Learn it. Apply it. Report it.",
    text: "Every function is taught on data, used on a fresh file, and then turned into something a manager could read.",
    steps: [
      { title: "Learn it", text: "The trainer explains one function on a small, clear example.", example: "XLOOKUP on 10 rows" },
      { title: "Apply it", text: "You use it on a larger, messier file on your own computer.", example: "Matching 2,000 orders" },
      { title: "Report it", text: "You summarise the result in a format someone else can use.", example: "A mismatch report" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name} for Excel`,
    text: `Plenty of places in ${site.city} teach "Excel". The difference is whether you practise on realistic data, how many functions you actually get to use yourself, and whether you leave able to build a report without notes.`,
    items: [
      { title: "Trainers who use Excel for work", text: "Examples come from real office reporting, not just the textbook." },
      { title: "One student, one computer", text: "Every formula is typed by you, not watched on a projector." },
      { title: "Small batches", text: "The trainer can check your formulas and fix mistakes as they happen." },
      { title: "Practice datasets", text: "Sales, stock and attendance files to keep practising at home." },
      { title: "Placement support", text: "Resume help, Excel test practice and job drives with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any Excel course, including this one.",
    rows: [
      { feature: "Lookups", us: "VLOOKUP, XLOOKUP and INDEX-MATCH", them: "Often VLOOKUP only" },
      { feature: "Pivot tables", us: "Grouping, slicers, calculated fields", them: "Basic pivot only" },
      { feature: "Practice data", us: "Realistic, messy business files", them: "Small textbook examples" },
      { feature: "Reporting", us: "Dashboards and MIS formats", them: "Rarely covered" },
      { feature: "Automation", us: "Macro recording basics", them: "Usually skipped" },
      { feature: "Batch size", us: "Small batches with individual attention", them: "Large, crowded batches" },
      { feature: "Timings", us: "Morning, evening, weekend, 1-on-1", them: "Fixed single slot" },
      { feature: "Certificate", us: "Verifiable certificate + dashboard project", them: "Varies" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Harpreet Kaur", role: "B.Com Graduate · Jalandhar", text: "Pivot tables and XLOOKUP were asked in my interview and I could do both on the spot. Got the back office job." },
    { name: "Rohit Bansal", role: "Accounts Staff · Focal Point", text: "I joined the evening batch after work. My monthly report now takes a few minutes instead of a whole afternoon." },
    { name: "Amandeep Singh", role: "Store In-charge · Kapurthala", text: "The stock reconciliation project was almost the same as my daily work. Very practical course." },
    { name: "Priya Mehta", role: "MBA Student · Model Town", text: "Clear explanations and lots of practice files. The dashboard I built helped in my college project too." },
    { name: "Jaspreet Singh", role: "Shop Owner · Rama Mandi", text: "Now I check my own sales and stock numbers every week. Trainer was patient with my questions." },
    { name: "Komal Sharma", role: "MIS Executive · Phagwara", text: "Weekend batch, small group. Macros part was new for me and I use one every day now." },
  ],
  faqs: [
    { q: "Do I need to know Excel before joining?", a: "You should know basic computer use. Excel is taught from formulas upwards, so you do not need prior Excel experience, though some familiarity helps." },
    { q: "What is the duration and class timing?", a: "The course runs for 2 months. Morning, afternoon, evening and weekend batches are available, plus 1-on-1 slots for working professionals." },
    { q: "Which version of Excel is taught?", a: "We teach on a current version of Microsoft Excel, including XLOOKUP. We also show the older alternatives so you can work on any office computer." },
    { q: "Is VBA programming included?", a: "The course covers macro recording and reading simple recorded VBA — enough to automate routine tasks. Full VBA programming is beyond this course." },
    { q: "Will I get a certificate?", a: "Yes. You receive a techcadd certificate on completing the course and projects, which can be verified online." },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, see the lab and meet the trainer before you decide." },
    { q: "What should I learn after this course?", a: "Tally Prime with GST for accounts roles, or the ADCA diploma if you want a broader one-year programme." },
  ],
};

const dca: CourseDetail = {
  slug: "dca-course-in-jalandhar",
  seo: {
    title: `DCA Course in ${site.city} | 6-Month Diploma in Computer Applications`,
    description: `Diploma in Computer Applications at ${site.name} ${site.city}: computer fundamentals, MS Office, internet, Tally Prime basics, English/Punjabi typing and basic Photoshop, with a diploma certificate and placement support.`,
  },
  hero: {
    crumb: "DCA",
    tag: "DCA Diploma",
    badge: "Ideal after 10th / 12th",
    title: `Best DCA Course in ${site.city}`,
    text: `A six-month diploma that covers the full set of computer skills an office job expects — Windows, MS Office, internet, Tally Prime basics, typing and basic Photoshop — taught hands-on in the ${site.name} ${site.city} lab and finished with a project of your own.`,
    points: ["6-month diploma", "Office + Tally basics", "Daily typing practice", "Placement support"],
    facts: [
      { label: "Duration", value: "6 Months" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "10th pass or above" },
      { label: "Includes", value: "Diploma + internship letter" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "7", label: "Modules", note: "office, accounts, design" },
    ],
    hub: {
      center: "windows.svg",
      nodes: [
        { logo: "word.png" },
        { logo: "excel.png" },
        { logo: "powerpoint.svg" },
        { logo: "tally.png" },
        { logo: "photoshop.png" },
        { logo: "punjabi.png" },
        { icon: "⌨" },
        { icon: "🎓" },
      ],
    },
  },
  overview: {
    eyebrow: "Course overview",
    title: "One diploma for the computer skills every office needs",
    paragraphs: [
      `${site.name}'s Diploma in Computer Applications (DCA) in ${site.city} is a six-month foundation programme for students after 10th or 12th, graduates and job seekers who want more than a short course — a recognised diploma and a broad, practical skill set in one go.`,
      "It starts with the computer and operating system, then spends real time on MS Word, Excel and PowerPoint, followed by internet, email and online services. The second half adds Tally Prime basics for billing and simple accounts, and an introduction to Photoshop for photos and simple designs. English and Punjabi typing practice runs alongside every module, so your speed builds steadily over six months.",
      "The diploma ends with a project that pulls the tools together — documents, sheets, a set of Tally vouchers and a small design — so you finish with a diploma certificate, a typing speed record and a portfolio of your own work.",
    ],
    image: "basic-computer.webp",
    imageAlt: "DCA students practising on computers in the techcadd lab",
    imageTag: "Six months of hands-on practice",
    getList: [
      "One computer per student, every class",
      "Office, Tally basics and Photoshop in one diploma",
      "Daily English and Punjabi typing with speed tracking",
      "Module tests and a final project",
      "Diploma certificate + internship letter",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "6", label: "Months" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who should do DCA",
    text: "DCA is open to anyone who has passed 10th. It starts from the basics, so earlier computer experience is helpful but not required.",
    items: [
      { icon: "student", title: "After 10th / 12th", text: "A practical diploma to do alongside college or before choosing your next step." },
      { icon: "grad", title: "Graduates", text: "Add a computer diploma to a BA, B.Com or B.Sc for office and clerical applications." },
      { icon: "job", title: "Job seekers", text: "Cover Office, typing and billing basics in one course instead of three short ones." },
      { icon: "govt", title: "Government job aspirants", text: "Many state posts ask for computer knowledge and a typing test — DCA covers both." },
      { icon: "home", title: "Homemakers returning to work", text: "A structured six months to rebuild confidence and get job-ready." },
      { icon: "shop", title: "Family business members", text: "Handle billing, records, letters and simple shop designs yourself." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why a six-month diploma instead of a short course",
    feature: {
      tag: "Access",
      title: "Six months that fit around college or work",
      text: `DCA students often attend alongside college or a job, so morning, evening and weekend batches run through the year. Students come in from Model Town, Adarsh Nagar, Basti Sheikh, Jawahar Nagar and Urban Estate, with weekend learners from Phagwara, Kapurthala, Nakodar and Kartarpur. Missed a class? Your trainer helps you catch up in lab time.`,
      slots: ["Morning", "Afternoon", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Breadth",
        title: "Office, accounts and design in one",
        text: "Instead of stitching together separate courses, DCA covers Office, Tally basics, typing and Photoshop in a planned order.",
      },
      {
        tag: "Depth",
        title: "Enough time to actually practise",
        text: "Six months means every tool gets weeks, not days — enough repetition for the skills to stay with you.",
      },
      {
        tag: "Credential",
        title: "A diploma on your resume",
        text: "Employers and many job forms ask for a computer diploma. DCA gives you one, verifiable online.",
      },
      {
        tag: "Next step",
        title: "Upgrade path to ADCA",
        text: "If you want to go further, ADCA builds on DCA with Advanced Excel, Tally with GST, CorelDRAW and web basics.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Computer skills are no longer a bonus on a job form.",
    points: [
      "Office, billing and clerical vacancies in Punjab routinely list \"computer diploma\" or \"DCA/PGDCA\" as a requirement.",
      "Entry-level computer operator and office assistant roles typically start around ₹9,000 – ₹15,000 a month.",
      "Six months after 10th or 12th is enough to build a skill set most applicants in your batch will not have.",
    ],
    panel: [
      { k: "MS Office", v: "Every office desk" },
      { k: "Tally basics", v: "Billing & shops" },
      { k: "Typing", v: "Govt. recruitment" },
      { k: "Diploma", v: "Job forms ask for it" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, month by month",
    text: "Six months, planned in the order you will use these skills at work — with typing practice every single day.",
    phases: [
      {
        id: "01",
        name: "Computer Fundamentals & Operating Systems",
        weeks: "Weeks 1–3",
        summary: "Understand the computer and work confidently in Windows.",
        topics: [
          "Hardware, software, input/output and storage devices",
          "Windows: desktop, settings, users and control panel",
          "Files, folders, drives and keyboard shortcuts",
          "Installing software, antivirus and basic troubleshooting",
        ],
        outcome: "Set up and manage a Windows PC on your own",
      },
      {
        id: "02",
        name: "MS Word",
        weeks: "Weeks 4–6",
        summary: "Create and format every common office document.",
        topics: [
          "Formatting, paragraphs, bullets and page setup",
          "Tables, images, headers, footers and page numbers",
          "Letters, applications, resumes and notices",
          "Mail merge, templates and printing",
        ],
        outcome: "Resume, formal letters and a mail-merged notice",
      },
      {
        id: "03",
        name: "MS Excel",
        weeks: "Weeks 7–10",
        summary: "Work with numbers, lists and formulas.",
        topics: [
          "Cells, formatting and sheet management",
          "SUM, AVERAGE, IF, COUNTIF and percentage formulas",
          "Sorting, filtering and charts",
          "VLOOKUP basics and printing reports",
        ],
        outcome: "A marksheet and a monthly expense report with charts",
      },
      {
        id: "04",
        name: "MS PowerPoint",
        weeks: "Weeks 11–12",
        summary: "Build and deliver clear presentations.",
        topics: [
          "Slides, layouts, themes and slide master",
          "Images, charts, SmartArt and transitions",
          "Presenting and exporting as PDF or video",
        ],
        outcome: "A 10-slide presentation you deliver to the batch",
      },
      {
        id: "05",
        name: "Internet & Email",
        weeks: "Weeks 13–14",
        summary: "Use online services safely and efficiently.",
        topics: [
          "Browsing, search and downloading safely",
          "Gmail, attachments, folders and formal email",
          "Online forms, government portals and DigiLocker",
          "Google Drive, cloud storage and fraud awareness",
        ],
        outcome: "Apply for a job online with a professional email and documents",
      },
      {
        id: "06",
        name: "Tally Prime Basics",
        weeks: "Weeks 15–18",
        summary: "Understand basic accounting and record everyday entries.",
        topics: [
          "Basic accounting terms: debit, credit, ledgers",
          "Creating a company, groups and ledgers",
          "Sales, purchase, payment and receipt vouchers",
          "Stock items, day book and simple reports",
        ],
        outcome: "A month of entries for a small shop, with reports",
      },
      {
        id: "07",
        name: "Basic Photoshop",
        weeks: "Weeks 19–21",
        summary: "Edit photos and make simple designs.",
        topics: [
          "Workspace, layers and selection tools",
          "Cropping, resizing and passport-size photos",
          "Photo correction and background removal",
          "Simple banners, posters and text effects",
        ],
        outcome: "A passport photo sheet and a shop poster",
      },
      {
        id: "08",
        name: "Project Work",
        weeks: "Weeks 22–24",
        summary: "Bring every tool together in one real project.",
        topics: [
          "Choosing a project for a school, shop or office",
          "Documents, sheets and Tally entries for it",
          "A presentation and design material",
          "Final review and diploma assessment",
        ],
        outcome: "A complete project file presented to your trainer",
      },
      {
        id: "09",
        name: "English & Punjabi Typing",
        weeks: "Every day",
        summary: "Build speed and accuracy steadily over six months.",
        topics: [
          "Touch typing and correct finger placement",
          "English typing speed and accuracy drills",
          "Punjabi (Gurmukhi) typing in Raavi",
          "Monthly speed tests with progress tracking",
        ],
        outcome: "Tested typing speed recorded on your diploma file",
      },
    ],
  },
  tools: {
    eyebrow: "Software you will use",
    title: "Every tool on your own lab computer",
    text: "You work in each of these yourself, from the first class of each module.",
    tools: [
      { name: "Windows", logo: "windows.svg", use: "Operating system" },
      { name: "MS Word", logo: "word.png", use: "Documents & resumes" },
      { name: "MS Excel", logo: "excel.png", use: "Sheets & formulas" },
      { name: "PowerPoint", logo: "powerpoint.svg", use: "Presentations" },
      { name: "Tally Prime", logo: "tally.png", use: "Vouchers & billing" },
      { name: "Photoshop", logo: "photoshop.png", use: "Photo editing basics" },
      { name: "Punjabi Typing", logo: "punjabi.png", use: "Raavi / Gurmukhi" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Earn your Diploma in Computer Applications",
    text: "Complete the six months, module tests and final project to receive a techcadd DCA diploma certificate — verifiable online.",
    courseName: "Diploma in Computer Applications (DCA)",
    items: [
      { title: "DCA diploma", text: "Verifiable online by employers" },
      { title: "Internship letter", text: "For the six-month programme" },
      { title: "Typing speed record", text: "English and Punjabi, in writing" },
      { title: "Placement support", text: "Resume help, mock interviews, job drives" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where DCA takes you",
    text: "Indicative starting pay for entry-level roles in Punjab. Actual offers depend on the employer, your typing speed and how you interview.",
    roles: [
      { title: "Computer Operator", pay: "₹9k – 15k", text: "Offices, clinics, institutes and government contractors" },
      { title: "Office Assistant", pay: "₹10k – 15k", text: "Documents, email, filing and daily office work" },
      { title: "Data Entry Operator", pay: "₹8k – 14k", text: "Back offices and record-keeping teams" },
      { title: "Billing Executive", pay: "₹10k – 16k", text: "Shops, showrooms and distributors using Tally" },
    ],
    hiring: ["Shops & showrooms", "Hospitals & clinics", "Schools & coaching centres", "Distributors & wholesalers", "CA & tax offices", "Government contractors"],
    qa: [
      {
        q: "What jobs can I get after DCA?",
        a: "Computer operator, office assistant, data entry and billing roles are the common starting points. Good typing speed and Tally basics make you a stronger candidate.",
      },
      {
        q: "Is DCA useful for government jobs?",
        a: "Many Punjab government posts ask for computer knowledge and a typing test. DCA covers both; always check the specific eligibility in each recruitment notice.",
      },
      {
        q: "Can I do DCA along with college?",
        a: "Yes. Many students take a morning or evening batch alongside college. Weekend batches are also available.",
      },
      {
        q: "What should I learn after DCA?",
        a: "Tally Prime with GST for accounts roles, Advanced Excel for MIS roles, or upgrade to ADCA for a full one-year diploma.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real work you will complete",
    text: "Every module ends with a task you finish on your own. Together they become your DCA portfolio.",
    items: [
      { n: "01", title: "Resume & letter set", text: "A formatted resume, a job application and a mail-merged notice in MS Word.", tags: ["MS Word", "Mail merge"] },
      { n: "02", title: "Student marksheet", text: "Totals, percentages, grades with IF and a result chart in Excel.", tags: ["MS Excel", "Formulas"] },
      { n: "03", title: "Shop accounts in Tally", text: "Create a company and enter a month of sales, purchases and payments, then print reports.", tags: ["Tally Prime", "Vouchers"] },
      { n: "04", title: "Poster & photo sheet", text: "Design a shop offer poster and a passport-size photo sheet in Photoshop.", tags: ["Photoshop", "Design"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "Learn. Practise. Test.",
    text: "Every topic follows the same three steps, and every module ends with a short test.",
    steps: [
      { title: "Learn", text: "The trainer demonstrates one task on the big screen.", example: "Creating a Tally ledger" },
      { title: "Practise", text: "You repeat it on your own computer until it is smooth.", example: "Ten sales vouchers" },
      { title: "Test", text: "A short task at the end of the module checks you can do it alone.", example: "Day book for a week" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name} for DCA`,
    text: `Many institutes in ${site.city} offer DCA. What differs is how much time you spend practising, whether the syllabus is kept up to date, and whether anyone helps you after the diploma.`,
    items: [
      { title: "Experienced trainers", text: "Trainers who teach beginners every day and explain things simply." },
      { title: "One student, one computer", text: "No sharing — you practise every minute of lab time." },
      { title: "Small batches", text: "Your trainer checks your work in every class." },
      { title: "Up-to-date syllabus", text: "Tally Prime, current Office versions and online services used today." },
      { title: "Placement support", text: "Resume help, mock interviews and job drives with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any DCA course, including this one.",
    rows: [
      { feature: "Practice time", us: "One computer per student, every class", them: "Shared computers or theory-heavy" },
      { feature: "Syllabus", us: "Office, internet, Tally, typing, Photoshop", them: "Often Office only" },
      { feature: "Accounting", us: "Tally Prime basics with practice entries", them: "Rarely included" },
      { feature: "Typing", us: "English + Punjabi, tested monthly", them: "Optional or missing" },
      { feature: "Project", us: "Final project reviewed by trainer", them: "Written exam only" },
      { feature: "Batch size", us: "Small batches with individual attention", them: "Large, crowded batches" },
      { feature: "Timings", us: "Morning, evening, weekend, 1-on-1", them: "Fixed single slot" },
      { feature: "Certificate", us: "Verifiable diploma + internship letter", them: "Varies" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Karanveer Singh", role: "Computer Operator · Jalandhar", text: "Did DCA after 12th. Typing and Excel practice every day helped me clear the test for my current job." },
    { name: "Ritika Sharma", role: "College Student · Adarsh Nagar", text: "Took the morning batch alongside my BA. Six months felt well planned and the teachers were helpful." },
    { name: "Gurpreet Kaur", role: "Homemaker · Urban Estate", text: "I wanted to go back to work. After DCA I am confident with Word, Excel and email again." },
    { name: "Mandeep Singh", role: "Billing Executive · Kartarpur", text: "The Tally part was very useful. I now handle billing at a wholesale shop." },
    { name: "Sukhmani Kaur", role: "12th Pass · Kapurthala", text: "Good for Punjabi typing. My speed improved steadily and the monthly tests kept me practising." },
    { name: "Vikas Kumar", role: "Office Assistant · Phagwara", text: "Weekend batch worked for me. Practical classes and small group, as they said." },
  ],
  faqs: [
    { q: "What is the eligibility for DCA?", a: "10th pass or above. No prior computer knowledge is required — the diploma starts from the basics." },
    { q: "What is the duration and class timing?", a: "DCA runs for 6 months. Morning, afternoon, evening and weekend batches are available, plus 1-on-1 slots on request." },
    { q: "What is the difference between DCA and ADCA?", a: "DCA is a 6-month foundation diploma. ADCA is a 12-month programme that includes everything in DCA plus Advanced Excel & MIS, Tally Prime with GST, CorelDRAW and HTML basics." },
    { q: "Will I get a diploma certificate?", a: "Yes. You receive a techcadd DCA diploma after completing the course, module tests and project, verifiable online, along with an internship letter." },
    { q: "Is Punjabi typing included?", a: "Yes. English and Punjabi (Gurmukhi) typing practice runs through all six months, with monthly speed tests." },
    { q: "Can I do DCA along with school or college?", a: "Yes. Many students join a morning, evening or weekend batch alongside their studies." },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, see the lab and meet the trainer before you decide." },
  ],
};

const adca: CourseDetail = {
  slug: "adca-course-in-jalandhar",
  seo: {
    title: `ADCA Course in ${site.city} | 1-Year Advanced Diploma in Computer Applications`,
    description: `Advanced Diploma in Computer Applications at ${site.name} ${site.city}: MS Office, Advanced Excel & MIS, Tally Prime with GST, Photoshop, CorelDRAW and HTML basics, with an internship letter and placement support.`,
  },
  hero: {
    crumb: "ADCA",
    tag: "ADCA Diploma",
    badge: "1-Year Diploma",
    title: `Best ADCA Course in ${site.city}`,
    text: `A one-year advanced diploma that takes you from computer basics to Advanced Excel, Tally Prime with GST, design in Photoshop and CorelDRAW, and simple web pages in HTML — practised daily in the ${site.name} ${site.city} lab and finished with an internship letter.`,
    points: ["12-month diploma", "Accounts + design + office", "Final project", "Internship letter"],
    facts: [
      { label: "Duration", value: "12 Months" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "10th pass or above" },
      { label: "Includes", value: "Diploma + internship letter" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "12", label: "Months", note: "office, accounts, design, web" },
    ],
    hub: {
      center: "excel.png",
      nodes: [
        { logo: "tally.png" },
        { logo: "coreldraw.png" },
        { logo: "photoshop.png" },
        { logo: "word.png" },
        { logo: "powerpoint.svg" },
        { logo: "windows.svg" },
        { icon: "</>" },
        { icon: "🎓" },
      ],
    },
  },
  overview: {
    eyebrow: "Course overview",
    title: "A full year of computer skills that open several career doors",
    paragraphs: [
      `${site.name}'s Advanced Diploma in Computer Applications (ADCA) in ${site.city} is a twelve-month programme for students after 10th or 12th, graduates and job seekers who want one qualification that covers office work, accounts and design — and the time to get properly good at each.`,
      "The first months cover everything in DCA: computer fundamentals, Windows, MS Word, Excel, PowerPoint, internet and typing. The year then goes deeper — Advanced Excel with lookups, pivot tables and MIS reports; Tally Prime with GST including invoices, returns data and reports; Photoshop and CorelDRAW for print and social designs; and HTML basics to build a simple web page.",
      "The diploma ends with a final project and an internship letter, so you leave with a verifiable diploma, a typing speed record and a portfolio that shows accounts, spreadsheet and design work — useful whether you apply for an accounts desk, a DTP job or a general office role.",
    ],
    image: "tally-gst.webp",
    imageAlt: "ADCA student working on Tally Prime and Excel in the techcadd lab",
    imageTag: "Office, accounts and design",
    getList: [
      "One computer per student, every class",
      "Advanced Excel, Tally with GST, CorelDRAW and HTML",
      "Daily English and Punjabi typing practice",
      "Module tests, a final project and portfolio",
      "Diploma certificate + internship letter",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "12", label: "Months" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who should do ADCA",
    text: "ADCA is open to anyone who has passed 10th. It starts from the basics and builds up over the year, so you do not need prior computer experience.",
    items: [
      { icon: "student", title: "After 10th / 12th", text: "A full year of job-ready skills and a diploma before or alongside college." },
      { icon: "grad", title: "B.Com, BA and BBA graduates", text: "Combine your degree with Tally, GST and Excel for accounts and office roles." },
      { icon: "job", title: "Job seekers", text: "Apply for accounts, DTP and office jobs from one qualification instead of one narrow skill." },
      { icon: "govt", title: "Government job aspirants", text: "Computer knowledge and typing speed for clerical posts, with a one-year diploma." },
      { icon: "design", title: "Aspiring DTP operators", text: "Learn CorelDRAW and Photoshop for flex, visiting cards and print shop work." },
      { icon: "shop", title: "Family business members", text: "Run billing and GST in Tally, keep records in Excel and design your own offers." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why a full year is worth it",
    feature: {
      tag: "Access",
      title: "A year-long plan that fits your routine",
      text: `ADCA students often study alongside college or part-time work, so batches run in the morning, afternoon, evening and on weekends. Students come from Model Town, Jawahar Nagar, Basti Bawa Khel, Rama Mandi and Urban Estate, with regulars from Phagwara, Kapurthala, Nakodar and Adampur. If you miss a class, your trainer helps you catch up in lab time.`,
      slots: ["Morning", "Afternoon", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Range",
        title: "Three job directions in one diploma",
        text: "Office and MIS, accounts with GST, and DTP/design — ADCA gives you the skills to apply in all three.",
      },
      {
        tag: "Depth",
        title: "Advanced, not just introductory",
        text: "Where DCA introduces Tally and Photoshop, ADCA goes on to GST, Advanced Excel, CorelDRAW and web basics.",
      },
      {
        tag: "Experience",
        title: "Project and internship letter",
        text: "A final project and an internship letter give you something concrete to talk about in interviews.",
      },
      {
        tag: "Value",
        title: "One plan instead of five courses",
        text: "Everything is taught in a planned order by the same team, so each module builds on the last without repetition.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Employers want people who can do more than one thing.",
    points: [
      "Small firms in Punjab often want one person who can handle billing in Tally, reports in Excel and simple designs — ADCA trains exactly that mix.",
      "Entry-level accounts assistant and office executive roles typically start around ₹12,000 – ₹18,000 a month, with GST and Excel skills making the difference.",
      "A year of steady practice turns separate tools into real, job-ready confidence.",
    ],
    panel: [
      { k: "Tally + GST", v: "Accounts desks" },
      { k: "Advanced Excel", v: "MIS & reports" },
      { k: "CorelDRAW", v: "Print & DTP work" },
      { k: "HTML basics", v: "Simple web pages" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn over the year",
    text: "The first months build the DCA foundation; the rest of the year adds advanced office, accounts, design and web skills, with typing practice every day.",
    phases: [
      {
        id: "01",
        name: "Computer Fundamentals, Windows & Internet",
        weeks: "Weeks 1–4",
        summary: "Build a solid base in the computer, operating system and online work.",
        topics: [
          "Hardware, software and storage basics",
          "Windows settings, files, folders and shortcuts",
          "Internet, Gmail, online forms and cloud storage",
          "Online safety, antivirus and basic troubleshooting",
        ],
        outcome: "Manage a Windows PC and handle online work independently",
      },
      {
        id: "02",
        name: "MS Word, Excel & PowerPoint",
        weeks: "Weeks 5–10",
        summary: "Core Office skills for documents, sheets and presentations.",
        topics: [
          "Word: letters, resumes, tables and mail merge",
          "Excel: formulas, IF, COUNTIF, charts and sorting",
          "PowerPoint: slide masters, charts and presenting",
          "Printing, PDF export and file sharing",
        ],
        outcome: "Resume, marksheet and a presentation you deliver",
      },
      {
        id: "03",
        name: "Advanced Excel & MIS",
        weeks: "Weeks 11–16",
        summary: "Handle business data the way offices do.",
        topics: [
          "SUMIFS, COUNTIFS, text and date functions",
          "VLOOKUP, XLOOKUP and INDEX-MATCH",
          "Data validation, conditional formatting",
          "Pivot tables, pivot charts and MIS dashboards",
        ],
        outcome: "A sales MIS dashboard built from a raw register",
      },
      {
        id: "04",
        name: "Tally Prime with GST",
        weeks: "Weeks 17–24",
        summary: "Keep a business's accounts and GST records correctly.",
        topics: [
          "Accounting basics, company, groups and ledgers",
          "Vouchers, inventory, godowns and stock reports",
          "GST setup, tax invoices, CGST/SGST/IGST",
          "GSTR-1 / GSTR-3B data, balance sheet and P&L",
        ],
        outcome: "Three months of a trading firm's accounts with GST reports",
      },
      {
        id: "05",
        name: "Photoshop",
        weeks: "Weeks 25–30",
        summary: "Edit photos and create social and print designs.",
        topics: [
          "Layers, masks and selection tools",
          "Photo retouching and background removal",
          "Passport photos, banners and social posts",
          "Exporting for print and web",
        ],
        outcome: "A set of edited photos and social media creatives",
      },
      {
        id: "06",
        name: "CorelDRAW",
        weeks: "Weeks 31–36",
        summary: "Design print material used by shops and businesses.",
        topics: [
          "Shapes, curves, text and colour",
          "Logos and visiting cards",
          "Flex banners, pamphlets and letterheads",
          "Print settings, bleed and file export",
        ],
        outcome: "Visiting card, pamphlet and flex design for a local business",
      },
      {
        id: "07",
        name: "HTML & Web Basics",
        weeks: "Weeks 37–42",
        summary: "Understand how web pages are built and make a simple one.",
        topics: [
          "How websites work: browsers, domains, hosting",
          "HTML tags, headings, lists, links and images",
          "Tables and forms",
          "Basic CSS for colours, fonts and layout",
        ],
        outcome: "A simple multi-page website for a shop or yourself",
      },
      {
        id: "08",
        name: "Final Project & Internship",
        weeks: "Weeks 43–48",
        summary: "Apply the whole year's skills to one real project.",
        topics: [
          "Choosing a business or institute as your project",
          "Tally accounts, Excel MIS and documents for it",
          "Print designs and a simple web page",
          "Presentation, review and diploma assessment",
        ],
        outcome: "A complete project portfolio and internship letter",
      },
      {
        id: "09",
        name: "English & Punjabi Typing",
        weeks: "Every day",
        summary: "Steady speed and accuracy practice through the whole year.",
        topics: [
          "Touch typing and correct finger placement",
          "English speed and accuracy drills",
          "Punjabi (Gurmukhi) typing in Raavi",
          "Monthly speed tests with progress tracking",
        ],
        outcome: "Tested typing speed recorded on your diploma file",
      },
    ],
  },
  tools: {
    eyebrow: "Software you will use",
    title: "Office, accounts, design and web tools",
    text: "Everything below is installed on every lab computer and used by you in class.",
    tools: [
      { name: "MS Office", logo: "word.png", use: "Word, PowerPoint, Outlook" },
      { name: "Advanced Excel", logo: "excel.png", use: "Lookups, pivots, MIS" },
      { name: "Tally Prime", logo: "tally.png", use: "Accounts & GST" },
      { name: "Photoshop", logo: "photoshop.png", use: "Photo editing & social posts" },
      { name: "CorelDRAW", logo: "coreldraw.png", use: "Print & DTP design" },
      { name: "HTML", mono: "HTML", use: "Simple web pages" },
      { name: "Punjabi Typing", logo: "punjabi.png", use: "Raavi / Gurmukhi" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Earn your Advanced Diploma in Computer Applications",
    text: "Complete the year, module tests and final project to receive a techcadd ADCA diploma certificate and internship letter — verifiable online.",
    courseName: "Advanced Diploma in Computer Applications (ADCA)",
    items: [
      { title: "ADCA diploma", text: "Verifiable online by employers" },
      { title: "Internship letter", text: "Issued with the one-year programme" },
      { title: "Project portfolio", text: "Accounts, Excel, design and web work" },
      { title: "Placement support", text: "Resume help, mock interviews, job drives" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where ADCA takes you",
    text: "Indicative starting pay for entry-level roles in Punjab. Actual offers depend on the employer, the role and how you interview.",
    roles: [
      { title: "Accounts Assistant", pay: "₹12k – 18k", text: "Tally entries, GST invoices and reports for firms and CA offices" },
      { title: "Computer Operator", pay: "₹10k – 16k", text: "Offices, institutes, hospitals and contractors" },
      { title: "DTP Operator", pay: "₹10k – 16k", text: "Print shops, flex printers and publishers" },
      { title: "Office Executive", pay: "₹12k – 18k", text: "Reports, records, correspondence and coordination" },
    ],
    hiring: ["CA & tax offices", "Traders & distributors", "Print & flex shops", "Manufacturing & export units", "Hospitals & clinics", "Schools & institutes"],
    qa: [
      {
        q: "What jobs can I get after ADCA?",
        a: "Accounts assistant, computer operator, DTP operator and office executive are the common starting roles. Your project portfolio helps show which direction suits you.",
      },
      {
        q: "Is ADCA better than DCA?",
        a: "ADCA includes everything in DCA and adds Advanced Excel, Tally with GST, CorelDRAW and HTML. If you can give a full year, it opens more job options; if you need to start work sooner, DCA is the shorter route.",
      },
      {
        q: "Will ADCA help for government jobs?",
        a: "Many Punjab government posts ask for computer knowledge and a typing test, and ADCA covers both. Always check the exact eligibility in each recruitment notice.",
      },
      {
        q: "Can I specialise after ADCA?",
        a: "Yes. Students often go on to specialised graphic design, digital marketing or web courses, and the ADCA foundation makes those faster to learn.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real projects in your portfolio",
    text: "Across the year you build work in each area. These four form the core of your ADCA portfolio.",
    items: [
      { n: "01", title: "GST accounts for a trading firm", text: "Three months of purchases, sales and payments in Tally Prime with GST invoices and reports.", tags: ["Tally Prime", "GST"] },
      { n: "02", title: "Sales MIS dashboard", text: "Clean a raw sales register and build pivot-based summaries and a one-page dashboard in Excel.", tags: ["Advanced Excel", "Pivot tables"] },
      { n: "03", title: "Print kit for a local shop", text: "A logo, visiting card, pamphlet and flex banner in CorelDRAW, plus social posts in Photoshop.", tags: ["CorelDRAW", "Photoshop"] },
      { n: "04", title: "Simple business website", text: "A small multi-page site in HTML and CSS with contact details, products and a form.", tags: ["HTML", "CSS"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "Learn. Practise. Build.",
    text: "Every topic is taught, practised on your own computer and then used in a piece of real work.",
    steps: [
      { title: "Learn", text: "The trainer demonstrates one feature on the big screen.", example: "A GST sales invoice" },
      { title: "Practise", text: "You repeat it on your own computer with fresh data.", example: "Twenty invoices for a week" },
      { title: "Build", text: "You use it in a module project that goes into your portfolio.", example: "Month-end GST report" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name} for ADCA`,
    text: `A one-year diploma is a real commitment. In ${site.city}, what separates courses is whether the advanced modules are actually taught in depth, how much practice time you get, and what support you get at the end.`,
    items: [
      { title: "Subject-wise trainers", text: "Accounts, Excel and design modules are taught by trainers who work with those tools." },
      { title: "One student, one computer", text: "Every entry, formula and design is done by you." },
      { title: "Small batches", text: "Your trainer reviews your work in every class." },
      { title: "Portfolio from day one", text: "Module projects collected into a portfolio you can show employers." },
      { title: "Internship & placement", text: "Internship letter, resume help and job drives with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any ADCA course, including this one.",
    rows: [
      { feature: "Excel depth", us: "Lookups, pivot tables and MIS dashboards", them: "Basic formulas only" },
      { feature: "Accounting", us: "Tally Prime with full GST module", them: "Tally basics without GST" },
      { feature: "Design", us: "Photoshop and CorelDRAW with print projects", them: "Short introduction or none" },
      { feature: "Web", us: "HTML and CSS basics with a small site", them: "Theory only" },
      { feature: "Practice time", us: "One computer per student, every class", them: "Shared computers" },
      { feature: "Batch size", us: "Small batches with individual attention", them: "Large, crowded batches" },
      { feature: "Timings", us: "Morning, evening, weekend, 1-on-1", them: "Fixed single slot" },
      { feature: "Certificate", us: "Verifiable diploma + internship letter", them: "Varies" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Navdeep Kaur", role: "Accounts Assistant · Jalandhar", text: "The Tally with GST module was detailed and practical. I got a job at a CA office soon after finishing." },
    { name: "Lovepreet Singh", role: "DTP Operator · Nakodar", text: "CorelDRAW and Photoshop were my favourite part. Now I make flex and visiting card designs at a print shop." },
    { name: "Anjali Verma", role: "B.Com Student · Model Town", text: "Did ADCA alongside college. Excel pivot tables and Tally both helped me in my internship." },
    { name: "Harmanjot Singh", role: "12th Pass · Kapurthala", text: "A full year felt long at first, but the monthly projects kept it interesting. Learned a lot of different things." },
    { name: "Pooja Rani", role: "Office Executive · Phagwara", text: "Good teachers and small batches. The portfolio helped me explain my skills in the interview." },
    { name: "Gagandeep Singh", role: "Family Business · Basti Bawa Khel", text: "I handle our shop's GST billing in Tally now and design our own offer pamphlets. Very useful course." },
  ],
  faqs: [
    { q: "What is the eligibility for ADCA?", a: "10th pass or above. No prior computer knowledge is needed — the course starts from the basics." },
    { q: "What is the duration and class timing?", a: "ADCA runs for 12 months. Morning, afternoon, evening and weekend batches are available, plus 1-on-1 slots on request." },
    { q: "What is the difference between DCA and ADCA?", a: "DCA is a 6-month foundation diploma. ADCA includes everything in DCA and adds Advanced Excel & MIS, Tally Prime with GST, Photoshop, CorelDRAW and HTML basics over 12 months." },
    { q: "Is GST taught in detail?", a: "Yes. The Tally module covers GST setup, tax invoices, CGST/SGST/IGST and preparing GSTR-1 and GSTR-3B data from Tally reports." },
    { q: "Will I get a diploma and internship letter?", a: "Yes. On completing the year, module tests and final project you receive a techcadd ADCA diploma, verifiable online, and an internship letter." },
    { q: "I already did DCA. Can I join ADCA?", a: "Yes. Speak to us about your DCA syllabus and we will guide you on the right starting point and batch." },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, see the lab and meet the trainers before you decide." },
  ],
};

export const office: CourseDetail[] = [msOfficeAdvancedExcel, dca, adca];
