// Course pages for the "Punjabi Typing" category. See ./types.ts for what each field is.
import { site } from "../site";
import type { CourseDetail } from "./types";

const punjabiTyping: CourseDetail = {
  slug: "punjabi-typing",
  seo: {
    title: `Punjabi Typing Course in ${site.city} | Raavi & Asees, 1 Month`,
    description: `Learn fast, accurate Gurmukhi typing in Raavi (Unicode) and Asees at ${site.name} ${site.city}, with daily speed drills and exam-pattern mock tests for Punjab government recruitment.`,
  },
  hero: {
    crumb: "Punjabi Typing",
    tag: "Punjabi Typing",
    badge: "Govt. Exam Ready",
    title: `Best Punjabi Typing Course in ${site.city}`,
    text: `Learn to type Gurmukhi by touch in Raavi and Asees — the fonts used in Punjab government offices and recruitment typing tests — with timed drills every day at the ${site.name} ${site.city} lab until speed and accuracy both show up on the test screen.`,
    points: ["Raavi + Asees", "Daily timed tests", "Exam-pattern mocks", "Certificate included"],
    facts: [
      { label: "Duration", value: "1 Month" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "Can read Punjabi" },
      { label: "Includes", value: "Certificate + speed record" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "Daily", label: "Speed tests", note: "WPM & accuracy tracked" },
    ],
    hub: {
      center: "punjabi.png",
      nodes: [
        { logo: "word.png" },
        { logo: "windows.svg" },
        { logo: "punjabi.png" },
        { logo: "google-workspace.svg" },
        { logo: "excel.png" },
        { logo: "word.png" },
        { icon: "ੳ" },
        { icon: "⌨" },
      ],
    },
  },
  overview: {
    eyebrow: "Course overview",
    title: "Gurmukhi typing that holds up in a timed test",
    paragraphs: [
      `${site.name}'s Punjabi Typing course in ${site.city} is for anyone who needs to type Gurmukhi quickly and correctly — mostly candidates preparing for Punjab government clerk, data entry and similar posts, where recruitment commonly includes a typing test in Punjabi and English, and people who type Punjabi documents for offices and courts.`,
      "The first week is spent on the keyboard layout and correct finger placement, so you stop hunting for keys. You then learn Raavi, the Unicode font now standard in government offices, and Asees, the older legacy font many tests and offices still use — including how the two layouts differ. Matras, half letters (pairin), nasal signs and special characters get their own drills, because that is where most marks are lost.",
      "The final part of the month is pure speed and accuracy: timed passages, error analysis and full mock tests set in the same pattern as recruitment typing tests. Your words per minute and accuracy are recorded each week, so you can see exactly where you stand before the real exam.",
    ],
    image: "punjabi-typing.webp",
    imageAlt: "Student practising Punjabi typing on a lab computer at techcadd",
    imageTag: "Timed practice every day",
    getList: [
      "One computer per student for daily typing",
      "Raavi (Unicode) and Asees both covered",
      "Printed Gurmukhi key charts for home revision",
      "Weekly WPM and accuracy record",
      "Exam-pattern mock tests before you finish",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "6", label: "Modules" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who can do this course",
    text: "You only need to be able to read Punjabi. No typing experience is required — the course starts from finger placement on the home row.",
    items: [
      { icon: "govt", title: "Govt. job aspirants", text: "Clerk, data entry and similar Punjab posts commonly include a Punjabi typing test — prepare for it properly." },
      { icon: "grad", title: "Graduates", text: "Add a practical, test-ready skill to your degree while you apply for jobs and exams." },
      { icon: "student", title: "12th pass students", text: "Start typing practice early so speed is already built when recruitment notices come out." },
      { icon: "office", title: "Office staff", text: "Type Punjabi letters, notices and records in Raavi without copying from others or using slow phonetic tools." },
      { icon: "job", title: "Typists & operators", text: "Move from slow two-finger typing to touch typing, and switch confidently between Raavi and Asees." },
      { icon: "freelance", title: "Home-based typing work", text: "Take Punjabi typing work for advocates, schools, printers and religious organisations." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why one focused month is worth it",
    feature: {
      tag: "Access",
      title: "Practice slots around your exam prep",
      text: `Aspirants come to the ${site.city} centre from Model Town, Adarsh Nagar, Basti Sheikh, Rama Mandi and Urban Estate, and from Kartarpur, Nakodar, Phagwara and Kapurthala for weekend batches. Morning, evening, weekend and 1-on-1 slots let you fit typing practice around coaching classes or a job — each class is guided teaching plus timed lab practice.`,
      slots: ["Morning", "Afternoon", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Demand",
        title: "The test that decides the post",
        text: "For many Punjab clerical posts, clearing the written exam is not the end — the typing test still has to be passed. Candidates lose selections here every year.",
      },
      {
        tag: "Method",
        title: "Touch typing, not hunting",
        text: "You learn correct finger placement from day one. Looking at the keyboard is slow, and it does not survive a timed test.",
      },
      {
        tag: "Fonts",
        title: "Raavi and Asees, both",
        text: "Offices have moved to Unicode Raavi, but Asees and other legacy layouts are still in use. You practise both, so the font on test day is not a surprise.",
      },
      {
        tag: "Proof",
        title: "Numbers you can see",
        text: "Every week you get a recorded speed and accuracy score. You always know how far you are from where you need to be.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Recruitment notices do not wait for your speed to catch up.",
    points: [
      "Punjab government clerical and data-entry recruitments commonly require a typing test in Punjabi and English — speed takes weeks to build, so start before the notice.",
      "Government posts offer pay as per government scale; in private offices and courts, Punjabi typists and operators typically start around ₹8k – 15k a month.",
      "One month of daily, measured practice is enough to go from hunting keys to steady touch typing in Gurmukhi.",
    ],
    panel: [
      { k: "Raavi (Unicode)", v: "Govt. offices" },
      { k: "Asees / legacy", v: "Older tests & records" },
      { k: "Speed + accuracy", v: "Both are checked" },
      { k: "Typing tests", v: "Punjab recruitment" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, week by week",
    text: "The month moves from layout to fonts to speed: first your fingers learn where every letter lives, then the tricky characters, then timed passages until the numbers are steady.",
    phases: [
      {
        id: "01",
        name: "Gurmukhi Keyboard & Finger Placement",
        weeks: "Week 1",
        summary: "Learn the layout properly so your fingers stop searching for keys.",
        topics: [
          "Correct sitting posture and hand position",
          "Home row keys and finger zones",
          "Gurmukhi letters on the top and bottom rows",
          "Short daily drills without looking at the keyboard",
        ],
        outcome: "Type every Gurmukhi letter by touch",
      },
      {
        id: "02",
        name: "Raavi (Unicode) Typing",
        weeks: "Week 2",
        summary: "Type in the Unicode font now used across government offices.",
        topics: [
          "Setting up Punjabi (Unicode) input in Windows",
          "Raavi font in MS Word and online forms",
          "Word and sentence practice in Raavi",
          "Saving and sharing Unicode documents correctly",
        ],
        outcome: "Type full Punjabi paragraphs in Raavi",
      },
      {
        id: "03",
        name: "Asees & Legacy Font Typing",
        weeks: "Week 2",
        summary: "Handle the older font layouts still found in offices and tests.",
        topics: [
          "How the Asees layout differs from Raavi",
          "Switching between Unicode and legacy fonts",
          "Common mistakes when changing layouts",
          "Paragraph practice in Asees",
        ],
        outcome: "Switch between Raavi and Asees without slowing down",
      },
      {
        id: "04",
        name: "Matras, Half Letters & Special Characters",
        weeks: "Week 3",
        summary: "Fix the characters where most typing-test errors happen.",
        topics: [
          "Laga matras: sihari, bihari, aunkar, dulainkar and more",
          "Pairin (half) letters, tippi, bindi and addak",
          "Numbers, punctuation and the danda (।)",
          "Error-heavy word lists for targeted practice",
        ],
        outcome: "Clean, correct Gurmukhi with fewer spelling errors",
      },
      {
        id: "05",
        name: "Speed Building Drills",
        weeks: "Week 3",
        summary: "Raise words per minute without losing accuracy.",
        topics: [
          "Timed passages of increasing length",
          "Common word and phrase drills",
          "Rhythm and consistency exercises",
          "Daily WPM and accuracy tracking",
        ],
        outcome: "A steady, recorded rise in your typing speed",
      },
      {
        id: "06",
        name: "Mock Typing Tests",
        weeks: "Week 4",
        summary: "Practise under the conditions you will face on test day.",
        topics: [
          "Exam-pattern timed passages in Raavi and Asees",
          "Error counting and accuracy calculation",
          "Reviewing mistakes and re-testing weak areas",
          "Test-day routine: setup, nerves and pacing",
        ],
        outcome: "Test-ready speed and accuracy on record",
      },
    ],
  },
  tools: {
    eyebrow: "Software you will use",
    title: "The same setup you will meet in a typing test",
    text: "Every lab computer is set up with Punjabi Unicode input, the Raavi and Asees fonts and typing-test software for timed practice.",
    tools: [
      { name: "Raavi", logo: "punjabi.png", use: "Unicode Gurmukhi font" },
      { name: "Asees", mono: "ਅ", use: "Legacy Punjabi font" },
      { name: "MS Word", logo: "word.png", use: "Punjabi documents" },
      { name: "Typing Tutor", mono: "TT", use: "Timed tests & WPM" },
      { name: "Windows", logo: "windows.svg", use: "Punjabi input setup" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Get certified in Punjabi Typing",
    text: `Complete the course and your final mock tests to receive a ${site.name} certificate that records your typing speed — verifiable online.`,
    courseName: "Punjabi Typing (Raavi & Asees)",
    items: [
      { title: "Course certificate", text: "Raavi and Asees typing, verifiable online" },
      { title: "Typing speed record", text: "Your final tested WPM and accuracy" },
      { title: "Mock test history", text: "Weekly scores showing your progress" },
      { title: "Placement support", text: "Job-drive updates and resume help" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where this course takes you",
    text: "Indicative starting pay for private roles in Punjab. Government posts are paid as per government scale; private offers depend on the employer and your tested speed.",
    roles: [
      { title: "Punjabi Typist", pay: "₹8k – 15k", text: "Court complexes, advocates' chambers and offices" },
      { title: "Data Entry Operator", pay: "₹9k – 15k", text: "Offices, contractors and record-keeping teams" },
      { title: "Computer Operator", pay: "₹10k – 16k", text: "Schools, clinics, offices and government contractors" },
      { title: "Punjabi DTP Operator", pay: "₹10k – 18k", text: "Printing presses, publishers and newspapers" },
    ],
    hiring: ["Court complexes & advocates", "Printing presses", "Schools & colleges", "Government contractors", "Newspapers & publishers", "Private offices"],
    qa: [
      {
        q: "Does this course help for Punjab government jobs?",
        a: "Yes. Many Punjab clerical and data-entry posts include a typing test in Punjabi and English. This course prepares the Punjabi side; the English & Punjabi Typing course covers both.",
      },
      {
        q: "Which font should I learn, Raavi or Asees?",
        a: "Both. Raavi (Unicode) is now the office standard, but Asees and other legacy layouts are still used. Always check the font named in the recruitment notice — we train you on both.",
      },
      {
        q: "Can I earn without a government job?",
        a: "Yes. Punjabi typists are needed at courts, advocates' chambers, printing presses and offices, and many students take home-based Punjabi typing work.",
      },
      {
        q: "What should I learn after this?",
        a: "English typing is the natural next step, since many tests include both. Basic Computer or MS Office also help for clerical roles.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real tasks you will complete",
    text: "Alongside the drills, you type the kind of Punjabi documents that offices actually produce.",
    items: [
      { n: "01", title: "Official Punjabi letter", text: "Type and format a government-style application or office letter in Raavi, ready to print.", tags: ["Raavi", "MS Word"] },
      { n: "02", title: "Asees to Raavi retyping", text: "Retype a legacy Asees document in Unicode Raavi and compare accuracy line by line.", tags: ["Asees", "Raavi"] },
      { n: "03", title: "Error-free passage", text: "Type a passage full of matras and half letters with zero mistakes, then time it.", tags: ["Accuracy", "Matras"] },
      { n: "04", title: "Full mock typing test", text: "Sit a complete exam-pattern typing test and get your WPM and error report.", tags: ["Mock test", "WPM"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "Learn it. Time it. Fix it.",
    text: "Every session ends with a number, so you always know whether you improved.",
    steps: [
      { title: "Learn it", text: "The trainer shows the keys, characters or technique for the day on the big screen.", example: "Typing pairin letters" },
      { title: "Time it", text: "You type a timed passage on your own computer while your speed is measured.", example: "5-minute Raavi passage" },
      { title: "Fix it", text: "Your errors are reviewed and you drill the exact words you got wrong.", example: "Re-testing weak matras" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name}`,
    text: `Plenty of places in ${site.city} let you sit at a computer and type. What matters for a typing test is correct technique from day one, both fonts, and someone checking your errors every day.`,
    items: [
      { title: "Trainers who know typing tests", text: "Practice built around exam-pattern passages, speed and error counting." },
      { title: "One student, one computer", text: "Every minute of lab time is your own typing practice." },
      { title: "Small batches", text: "Your trainer checks your posture, fingers and errors every class." },
      { title: "Both fonts covered", text: "Raavi (Unicode) and Asees, with practice switching between them." },
      { title: "Placement support", text: "Job-drive updates and resume help with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any Punjabi typing course, including this one.",
    rows: [
      { feature: "Technique", us: "Touch typing with correct finger placement", them: "Self-practice, often two-finger typing" },
      { feature: "Fonts", us: "Raavi (Unicode) and Asees", them: "Often only one font" },
      { feature: "Speed tracking", us: "Weekly recorded WPM and accuracy", them: "Rarely measured" },
      { feature: "Mock tests", us: "Exam-pattern timed tests", them: "Random passages" },
      { feature: "Error review", us: "Mistakes reviewed and re-drilled", them: "Limited or none" },
      { feature: "Batch size", us: "Small batches with individual attention", them: "Large, crowded batches" },
      { feature: "Timings", us: "Morning, evening, weekend, 1-on-1", them: "Fixed single slot" },
      { feature: "Certificate", us: "Verifiable certificate with speed record", them: "Varies" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Harpreet Kaur", role: "Clerk Aspirant · Jalandhar", text: "I used to look at the keyboard for every letter. After a month of daily tests I type Raavi without looking, and my accuracy is much better." },
    { name: "Jaspreet Singh", role: "Graduate · Kartarpur", text: "The matras and half letters were my weak point. The trainer gave me word lists just for those and it really helped." },
    { name: "Ramandeep Kaur", role: "Typist · Court Complex", text: "I learned Asees years ago but offices now want Raavi. This course made the switch easy." },
    { name: "Lovepreet Singh", role: "Student · Nakodar", text: "Weekend batch suited me because of college. The mock tests felt close to a real typing test." },
    { name: "Kulwinder Kaur", role: "Office Assistant · Model Town", text: "Now I type Punjabi letters and notices myself instead of asking someone else. Simple and practical classes." },
    { name: "Gurpreet Singh", role: "Data Entry Operator · Phagwara", text: "Seeing my speed written down every week kept me practising. Good trainers, small batch." },
  ],
  faqs: [
    { q: "Do I need to know typing before joining?", a: "No. You only need to be able to read Punjabi. The course starts from finger placement on the home row." },
    { q: "What is the duration and class timing?", a: "The course runs for 1 month. Morning, afternoon, evening and weekend batches are available, plus 1-on-1 slots on request." },
    { q: "Will I learn Raavi or Asees?", a: "Both. Raavi (Unicode) is the current office standard and Asees is still used in places, so you practise both and learn to switch between them." },
    { q: "Does the course follow the government typing test pattern?", a: "Mock tests follow the general pattern of Punjab recruitment typing tests — timed passages checked for speed and errors. Always read the official notice for the exact rules of your exam." },
    { q: "Will I get a certificate?", a: `Yes. You receive a ${site.name} certificate with your tested typing speed, which can be verified online.` },
    { q: "Is English typing included?", a: "This course focuses on Punjabi. If your exam needs both, the 2-month English & Punjabi Typing course covers both languages." },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, try the lab setup and meet the trainer before you decide." },
  ],
};

const englishPunjabiTyping: CourseDetail = {
  slug: "english-punjabi-typing",
  seo: {
    title: `English & Punjabi Typing Course in ${site.city} | 2-Month Exam Prep`,
    description: `Build exam-level English and Gurmukhi typing speed at ${site.name} ${site.city}: touch typing, Raavi and Asees, accuracy drills and daily timed mock tests for clerk and data-entry recruitment.`,
  },
  hero: {
    crumb: "English & Punjabi Typing",
    tag: "English + Punjabi Typing",
    badge: "Clerk Exam Prep",
    title: `Best English & Punjabi Typing Course in ${site.city}`,
    text: `Build test-ready speed in both English and Gurmukhi — touch typing first, then Raavi and Asees, then daily timed tests — at the ${site.name} ${site.city} lab, with your WPM and accuracy recorded every week.`,
    points: ["English + Gurmukhi", "Daily timed tests", "Raavi + Asees", "Certificate included"],
    facts: [
      { label: "Duration", value: "2 Months" },
      { label: "Mode", value: "Classroom · Weekend · 1-on-1" },
      { label: "Eligibility", value: "Can read Punjabi & English" },
      { label: "Includes", value: "Certificate + speed record" },
    ],
    stats: [
      { value: "25,000+", label: "Students trained", note: `since ${site.since}` },
      { value: "4.9★", label: "Google rating", note: "from our students" },
      { value: "2", label: "Languages", note: "English & Gurmukhi" },
    ],
    hub: {
      center: "punjabi.png",
      nodes: [
        { logo: "word.png" },
        { logo: "windows.svg" },
        { logo: "excel.png" },
        { logo: "punjabi.png" },
        { logo: "google-workspace.svg" },
        { logo: "outlook.svg" },
        { icon: "⌨" },
        { icon: "ੳ" },
      ],
    },
  },
  overview: {
    eyebrow: "Course overview",
    title: "Two languages, one steady typing speed",
    paragraphs: [
      `${site.name}'s English & Punjabi Typing course in ${site.city} is built for candidates preparing for Punjab clerk, data-entry and steno-typist style recruitment, where posts commonly require a typing test in both Punjabi and English — and for anyone whose office work switches between the two languages every day.`,
      "The first weeks are pure touch typing on the English keyboard: posture, home row and every finger's zone, until you type without looking. English speed building follows, then Gurmukhi in Raavi (Unicode) and Asees, so you learn two layouts on the same keyboard without mixing them up. Punctuation, numbers and symbols get dedicated practice because tests and office documents are full of them.",
      "The second month turns speed into reliable, test-ready typing: accuracy work, error correction, and timed mock tests in both languages set in the same pattern as recruitment typing tests. Your WPM and accuracy are recorded every week, in English and in Punjabi.",
    ],
    image: "punjabi-typing.webp",
    imageAlt: "Students practising English and Punjabi typing in the techcadd lab",
    imageTag: "Timed tests in both languages",
    getList: [
      "One computer per student for daily typing",
      "English touch typing plus Raavi and Asees",
      "Separate WPM and accuracy record for each language",
      "Error analysis after every timed test",
      "Exam-pattern mock tests in both languages",
    ],
    miniStats: [
      { value: "25K+", label: "Students" },
      { value: "4.9★", label: "Google rating" },
      { value: `${site.since}`, label: "Established" },
      { value: "6", label: "Modules" },
    ],
  },
  audience: {
    eyebrow: "Eligibility",
    title: "Who can do this course",
    text: "You need to read Punjabi and English. No typing experience is required — the course starts with finger placement and builds up from there.",
    items: [
      { icon: "govt", title: "Clerk & data-entry aspirants", text: "Prepare for recruitment typing tests that commonly check both Punjabi and English." },
      { icon: "grad", title: "Graduates", text: "Build a measurable, job-ready skill while you prepare for exams and applications." },
      { icon: "student", title: "12th pass students", text: "Two months of practice now means your speed is ready when the next notice comes out." },
      { icon: "office", title: "Office staff", text: "Type English and Punjabi letters, notices and records quickly, without switching mistakes." },
      { icon: "job", title: "Job seekers", text: "Data entry, computer operator and typist roles all ask for a tested typing speed." },
      { icon: "freelance", title: "Home-based typists", text: "Take bilingual typing work from advocates, schools, printers and small offices." },
    ],
  },
  case: {
    eyebrow: "The case for it",
    title: "Why two months here are worth it",
    feature: {
      tag: "Access",
      title: "Daily practice that fits your routine",
      text: `Students reach the ${site.city} centre from Model Town, Adarsh Nagar, Basti Bawa Khel, Rama Mandi and Urban Estate, and from Phagwara, Kapurthala, Nakodar and Adampur for weekend batches. Morning, evening, weekend and 1-on-1 slots let you practise daily around coaching, college or work — every class is guided teaching plus timed lab time.`,
      slots: ["Morning", "Afternoon", "Evening", "Weekend", "1-on-1"],
    },
    cards: [
      {
        tag: "Demand",
        title: "Two tests, not one",
        text: "Many clerical posts check typing in both languages. Being fast in only one of them is not enough to clear the test.",
      },
      {
        tag: "Method",
        title: "Touch typing first",
        text: "English touch typing comes first, so the same correct finger habits carry into Gurmukhi instead of two sets of bad habits.",
      },
      {
        tag: "Accuracy",
        title: "Speed is useless with errors",
        text: "Typing tests check mistakes as well as speed. Every timed test is followed by error review and targeted re-drilling.",
      },
      {
        tag: "Proof",
        title: "Weekly scores in both languages",
        text: "Your English and Punjabi WPM and accuracy are recorded separately each week, so you know exactly which side needs work.",
      },
    ],
  },
  whyNow: {
    eyebrow: "Why now",
    title: "Speed takes weeks to build. Start before the notice.",
    points: [
      "Punjab clerk and data-entry recruitments commonly require a typing test in Punjabi and English, usually soon after the written stage.",
      "Government posts offer pay as per government scale; private data entry and typist roles in Punjab typically start around ₹9k – 16k a month.",
      "Two months of daily, timed practice is enough to build steady, test-ready speed in both languages.",
    ],
    panel: [
      { k: "English typing", v: "Clerk & data-entry tests" },
      { k: "Raavi (Unicode)", v: "Govt. offices" },
      { k: "Asees / legacy", v: "Older tests & records" },
      { k: "Speed + accuracy", v: "Both are checked" },
    ],
  },
  syllabus: {
    eyebrow: "Syllabus",
    title: "What you will learn, week by week",
    text: "English touch typing lays the foundation, Gurmukhi is added on top, and the second month is spent turning speed into accurate, timed test performance in both languages.",
    phases: [
      {
        id: "01",
        name: "Touch Typing Fundamentals",
        weeks: "Weeks 1–2",
        summary: "Build correct technique before chasing speed.",
        topics: [
          "Posture, hand position and screen distance",
          "Home row and finger zones on the QWERTY keyboard",
          "Top and bottom row keys, shift and space",
          "Typing without looking at the keyboard",
        ],
        outcome: "Type every English letter by touch",
      },
      {
        id: "02",
        name: "English Typing Speed Building",
        weeks: "Weeks 3–4",
        summary: "Raise English WPM with steady, rhythmic typing.",
        topics: [
          "Common words, phrases and letter combinations",
          "Timed paragraphs of increasing length",
          "Capital letters and sentence structure",
          "Daily WPM and accuracy tracking",
        ],
        outcome: "A steady, recorded English typing speed",
      },
      {
        id: "03",
        name: "Gurmukhi Typing in Raavi & Asees",
        weeks: "Weeks 3–5",
        summary: "Add Punjabi typing without mixing up layouts.",
        topics: [
          "Setting up Punjabi (Unicode) input in Windows",
          "Gurmukhi layout and finger placement in Raavi",
          "Matras, pairin (half) letters, tippi and bindi",
          "Asees legacy layout and switching between fonts",
        ],
        outcome: "Type Punjabi paragraphs in Raavi and Asees",
      },
      {
        id: "04",
        name: "Punctuation, Numbers & Symbols",
        weeks: "Week 6",
        summary: "Handle the characters that slow most typists down.",
        topics: [
          "Number row and numeric keypad",
          "Punctuation in English and the danda (।) in Punjabi",
          "Symbols used in official letters, dates and amounts",
          "Mixed text with names, numbers and references",
        ],
        outcome: "Type official text with numbers and symbols cleanly",
      },
      {
        id: "05",
        name: "Accuracy & Error Correction",
        weeks: "Week 7",
        summary: "Cut the mistakes that cost marks in a typing test.",
        topics: [
          "Counting and classifying your errors",
          "Common English and Punjabi spelling traps",
          "Targeted drills on your weakest words and keys",
          "Proofreading typed passages quickly",
        ],
        outcome: "Higher accuracy in both languages",
      },
      {
        id: "06",
        name: "Timed Mock Tests",
        weeks: "Week 8",
        summary: "Practise under test-day conditions in both languages.",
        topics: [
          "Exam-pattern timed passages in English",
          "Exam-pattern timed passages in Raavi and Asees",
          "Speed and error calculation after every test",
          "Test-day routine: setup, pacing and nerves",
        ],
        outcome: "Test-ready English and Punjabi scores on record",
      },
    ],
  },
  tools: {
    eyebrow: "Software you will use",
    title: "The same setup you will meet in a typing test",
    text: "Every lab computer has English and Punjabi Unicode input, the Raavi and Asees fonts and typing software for timed tests.",
    tools: [
      { name: "Raavi", logo: "punjabi.png", use: "Unicode Gurmukhi font" },
      { name: "Asees", mono: "ਅ", use: "Legacy Punjabi font" },
      { name: "MS Word", logo: "word.png", use: "Bilingual documents" },
      { name: "Typing Tutor", mono: "TT", use: "Timed tests & WPM" },
      { name: "Windows", logo: "windows.svg", use: "Language & input setup" },
    ],
  },
  certificate: {
    eyebrow: "Certification",
    title: "Get certified in English & Punjabi Typing",
    text: `Complete the course and your final mock tests to receive a ${site.name} certificate recording your typing speed in both languages — verifiable online.`,
    courseName: "English & Punjabi Typing",
    items: [
      { title: "Course certificate", text: "English and Punjabi typing, verifiable online" },
      { title: "Typing speed record", text: "Tested WPM and accuracy in both languages" },
      { title: "Mock test history", text: "Weekly scores showing your progress" },
      { title: "Placement support", text: "Job-drive updates and resume help" },
    ],
  },
  careers: {
    eyebrow: "Future scope",
    title: "Where this course takes you",
    text: "Indicative starting pay for private roles in Punjab. Government clerk and steno posts are paid as per government scale; private offers depend on the employer and your tested speed.",
    roles: [
      { title: "Data Entry Operator", pay: "₹9k – 15k", text: "Offices, back offices and government contractors" },
      { title: "Computer Operator", pay: "₹10k – 16k", text: "Schools, clinics, offices and service centres" },
      { title: "Bilingual Typist", pay: "₹9k – 16k", text: "Court complexes, advocates and private offices" },
      { title: "Office Assistant", pay: "₹10k – 16k", text: "Letters, records and correspondence in both languages" },
    ],
    hiring: ["Court complexes & advocates", "Government contractors", "Schools & colleges", "Hospitals & clinics", "CA & tax offices", "Private offices"],
    qa: [
      {
        q: "Does this course help for clerk and steno-typist exams?",
        a: "Yes. Many Punjab clerical and data-entry posts include a typing test in Punjabi and English, and this course prepares both. Steno posts also need shorthand, which is separate.",
      },
      {
        q: "Should I learn English or Punjabi typing first?",
        a: "English touch typing first. It builds correct finger habits, which then carry over to Gurmukhi. The course follows that order.",
      },
      {
        q: "Can I earn without a government job?",
        a: "Yes. Data entry, computer operator and bilingual typist roles are common in private offices, courts and contractors, and home-based typing work is also possible.",
      },
      {
        q: "What should I learn after this?",
        a: "Basic Computer or MS Office & Advanced Excel pair well with typing for clerical and office roles. Tally Prime is a good next step for accounts work.",
      },
    ],
  },
  projects: {
    eyebrow: "Practical work",
    title: "Real tasks you will complete",
    text: "Alongside the drills, you type the kind of documents offices actually produce in both languages.",
    items: [
      { n: "01", title: "English official letter", text: "Type and format a formal English application with dates, references and numbers — error-free.", tags: ["English", "MS Word"] },
      { n: "02", title: "Punjabi office notice", text: "Type a government-style notice in Raavi with correct matras and punctuation.", tags: ["Raavi", "MS Word"] },
      { n: "03", title: "Bilingual data sheet", text: "Enter names, addresses and figures in English and Punjabi into a clean, checked record.", tags: ["Data entry", "Accuracy"] },
      { n: "04", title: "Full mock typing test", text: "Sit timed tests in both languages and get a combined WPM and error report.", tags: ["Mock test", "WPM"] },
    ],
  },
  loop: {
    eyebrow: "How every class works",
    title: "Learn it. Time it. Fix it.",
    text: "Every session ends with a measured score, so progress is never a guess.",
    steps: [
      { title: "Learn it", text: "The trainer demonstrates the keys, characters or technique for the day.", example: "Number row in English" },
      { title: "Time it", text: "You type a timed passage on your own computer while speed and errors are measured.", example: "5-minute Punjabi passage" },
      { title: "Fix it", text: "Mistakes are reviewed and you re-drill exactly what went wrong.", example: "Re-testing punctuation errors" },
    ],
  },
  why: {
    eyebrow: `Why ${site.name}`,
    title: `Why students choose ${site.name}`,
    text: `Typing practice is easy to find in ${site.city}. What makes the difference in a test is correct technique, both languages practised properly, and someone reviewing your errors every day.`,
    items: [
      { title: "Trainers who know typing tests", text: "Practice built around exam-pattern passages, speed and error counting." },
      { title: "One student, one computer", text: "Every minute of lab time is your own typing practice." },
      { title: "Small batches", text: "Your trainer checks your posture, fingers and errors every class." },
      { title: "Both languages, both fonts", text: "English plus Punjabi in Raavi and Asees, tracked separately." },
      { title: "Placement support", text: "Job-drive updates and resume help with 500+ hiring partners." },
      { title: "Trusted since " + site.since, text: "25,000+ students trained across Punjab, rated 4.9★ on Google." },
    ],
  },
  compare: {
    eyebrow: "Compare",
    title: `How ${site.name} compares`,
    text: "Questions worth asking before you join any typing course, including this one.",
    rows: [
      { feature: "Technique", us: "Touch typing with correct finger placement", them: "Self-practice, often two-finger typing" },
      { feature: "Languages", us: "English and Punjabi, both tracked", them: "Often only one language" },
      { feature: "Punjabi fonts", us: "Raavi (Unicode) and Asees", them: "Often only one font" },
      { feature: "Speed tracking", us: "Weekly recorded WPM and accuracy", them: "Rarely measured" },
      { feature: "Mock tests", us: "Exam-pattern timed tests in both languages", them: "Random passages" },
      { feature: "Batch size", us: "Small batches with individual attention", them: "Large, crowded batches" },
      { feature: "Timings", us: "Morning, evening, weekend, 1-on-1", them: "Fixed single slot" },
      { feature: "Certificate", us: "Verifiable certificate with speed record", them: "Varies" },
    ],
    note: "The right-hand column describes what is commonly offered in the market, not any particular institute.",
  },
  reviews: [
    { name: "Navneet Kaur", role: "Clerk Aspirant · Jalandhar", text: "My English was fine but Punjabi was slow. Separate weekly scores showed me exactly where to practise, and both improved." },
    { name: "Amandeep Singh", role: "Graduate · Kapurthala", text: "Starting with English touch typing helped a lot. By the time Raavi came, my fingers already knew what to do." },
    { name: "Sukhwinder Kaur", role: "Office Assistant · Adarsh Nagar", text: "I type English and Punjabi letters at work every day. The punctuation and numbers practice was very useful." },
    { name: "Parminder Singh", role: "Data Entry Operator · Adampur", text: "The error review after each test was the best part. My accuracy went up before my speed did, which is what I needed." },
    { name: "Rajdeep Kaur", role: "Student · Urban Estate", text: "Evening batch fitted around my coaching classes. The mock tests felt close to the real thing." },
    { name: "Manjit Singh", role: "Typist · Nakodar", text: "Small batch, patient trainer and daily timed tests. Two months well spent." },
  ],
  faqs: [
    { q: "Do I need to know typing before joining?", a: "No. The course starts from finger placement and touch typing. You only need to read English and Punjabi." },
    { q: "What is the duration and class timing?", a: "The course runs for 2 months. Morning, afternoon, evening and weekend batches are available, plus 1-on-1 slots on request." },
    { q: "Is Punjabi taught in Raavi or Asees?", a: "Both. Raavi (Unicode) is the current office standard and Asees is still used in places, so you practise both." },
    { q: "Does the course follow the recruitment typing test pattern?", a: "Mock tests follow the general pattern of Punjab recruitment typing tests — timed passages checked for speed and errors, in both languages. Always read the official notice for the exact rules of your exam." },
    { q: "Is shorthand included for steno posts?", a: "No. This course covers typing in English and Punjabi. Steno posts usually also require shorthand, which is a separate skill." },
    { q: "Will I get a certificate?", a: `Yes. You receive a ${site.name} certificate with your tested typing speed in both languages, which can be verified online.` },
    { q: "Can I attend a demo class first?", a: "Yes. Book a free demo class, try the lab setup and meet the trainer before you decide." },
  ],
};

export const typing: CourseDetail[] = [punjabiTyping, englishPunjabiTyping];
